In [1]:
import pandas as pd 
pd.set_option('display.max_columns', None)

df_1 = pd.read_excel("/data/home/yansn/naojiye/data/入组表_20250814.xlsx")
df_2 = pd.read_csv("/data/home/yansn/naojiye/data/入组患者时间窗内检验清洗数据_20250814.csv")

df_1['备注说明'] = df_1['备注说明'].fillna('空值')

/tmp/ipykernel_4014900/2247489155.py:5: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2 = pd.read_csv("/data/home/yansn/naojiye/data/入组患者时间窗内检验清洗数据_20250814.csv")

In [2]:
df_2.shape

(441661, 46)

In [3]:
df_1.head()

        PID       入组时间  组别 性别  年龄 备注说明
0  86600553 2022-07-08   8  男  32   空值
1  86600617 2022-08-15   2  男  41    优
2  86601650 2024-01-04   6  男  25   空值
3  86601774 2024-03-19   3  女  47    优
4  86601850 2024-04-30   0  男  18   空值

In [4]:
df_2.head()

,_id,error,errorMsg,visitId,inputNumber,patientId,gender,age,testNo,labResultItemNo,testItemName,originalSpecimen,standardSpecimen,specimenMemo,resultStatus,laboratoryId,laboratoryTree,clinicalDiagnose,laboratoryName,originalLaboratoryName,laboratoryStandardVersion,instrumentId,originalAbnormalIndicator,abnormalIndicator,standardResult,standardResultNorm,originalResult,originalReferenceInterval,referenceInterval,standardUnits,originalUnits,resultDateTime,standardResultType,memo,synchronizeTime,reportDateTime,standardQuantitativeResult,abnormal,originalSpecimenId,originalLaboratoryId,reportApplyTime,specimenCollectTime,cleanState,standardNormalizedQuantitative,departmentName,departmentCode
0,99000785_163_99000785_2020-03-20 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD002863,NaN,NaN,"1,3-β-D-葡聚糖",G试验(血浆1-3-B-D葡聚糖),Vb24.33,NaN,M,NaN,"[0,31.25)",31.24,<31.25,"参考值:; 60pg/ml以下,无深部真菌感染;(隐球菌、接合菌除外);60-100pg/m...","[60,100]",pg/ml,pg/ml,2020-03-20T00:00,QUANTIFY,NaN,2025-08-13T15:49:34,2020-03-20T00:00,31.24,True,NaN,NaN,NaN,NaN,清洗成功,-0.719000,西院感染科,NaN
1,99000785_164_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD005052,NaN,NaN,抗桥粒芯糖蛋白1抗体,抗桥粒芯糖蛋白1,Vb24.33,NaN,M,NaN,0.70,0.70,0.70,0.1--20,"[0.1,20]",U/ml,U/ml,2020-03-25T00:00,QUANTIFY,NaN,2025-08-13T15:49:37,2020-03-25T00:00,0.70,False,NaN,NaN,NaN,NaN,清洗成功,0.030151,西院感染科,NaN
2,99000785_165_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD005053,NaN,NaN,抗桥粒芯糖蛋白3抗体,抗桥粒芯糖蛋白3,Vb24.33,NaN,M,NaN,0.10,0.10,0.10,0.1--20,"[0.1,20]",U/ml,U/mL,2020-03-25T00:00,QUANTIFY,NaN,2025-08-13T15:49:37,2020-03-25T00:00,0.10,False,NaN,NaN,NaN,NaN,清洗成功,0.000000,西院感染科,NaN
3,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,脑脊液,脑脊液,NaN,NaN,LTI_SD002984,NaN,NaN,细菌培养,细菌培养,Vb24.33,NaN,M,NaN,【细菌培养】未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN
4,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,脑脊液,脑脊液,NaN,NaN,LTI_SD002984,NaN,NaN,细菌培养,细菌培养,Vb24.33,NaN,M,NaN,未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN

In [14]:
df_1['PID'].nunique() == len(df_1)

True

In [8]:
df_1['备注说明'].value_counts()

备注说明
空值    659
优     205
良      25
Name: count, dtype: int64

In [9]:
df_1['组别'].value_counts()

组别
5    149
6    140
8    131
0    124
4    111
2    107
1     64
3     63
Name: count, dtype: int64

In [16]:
cnt_df = df_1.groupby(['组别', '备注说明'])['PID'].count().reset_index().rename(columns={'PID':'PID个数'})
cnt_df

    组别 备注说明  PID个数
0    0   空值    124
1    1    优     40
2    1    良     24
3    2    优    103
4    2   空值      4
5    3    优     62
6    3    良      1
7    4   空值    111
8    5   空值    149
9    6   空值    140
10   8   空值    131

In [17]:
df_2.shape, df_2.columns

((441661, 46),
 Index(['_id', 'error', 'errorMsg', 'visitId', 'inputNumber', 'patientId',
        'gender', 'age', 'testNo', 'labResultItemNo', 'testItemName',
        'originalSpecimen', 'standardSpecimen', 'specimenMemo', 'resultStatus',
        'laboratoryId', 'laboratoryTree', 'clinicalDiagnose', 'laboratoryName',
        'originalLaboratoryName', 'laboratoryStandardVersion', 'instrumentId',
        'originalAbnormalIndicator', 'abnormalIndicator', 'standardResult',
        'standardResultNorm', 'originalResult', 'originalReferenceInterval',
        'referenceInterval', 'standardUnits', 'originalUnits', 'resultDateTime',
        'standardResultType', 'memo', 'synchronizeTime', 'reportDateTime',
        'standardQuantitativeResult', 'abnormal', 'originalSpecimenId',
        'originalLaboratoryId', 'reportApplyTime', 'specimenCollectTime',
        'cleanState', 'standardNormalizedQuantitative', 'departmentName',
        'departmentCode'],
       dtype='object'))

In [19]:
df_2.head()

,_id,error,errorMsg,visitId,inputNumber,patientId,gender,age,testNo,labResultItemNo,...,standardQuantitativeResult,abnormal,originalSpecimenId,originalLaboratoryId,reportApplyTime,specimenCollectTime,cleanState,standardNormalizedQuantitative,departmentName,departmentCode
0,99000785_163_99000785_2020-03-20 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,...,31.24,True,NaN,NaN,NaN,NaN,清洗成功,-0.719000,西院感染科,NaN
1,99000785_164_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,...,0.70,False,NaN,NaN,NaN,NaN,清洗成功,0.030151,西院感染科,NaN
2,99000785_165_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,...,0.10,False,NaN,NaN,NaN,NaN,清洗成功,0.000000,西院感染科,NaN
3,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN
4,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,...,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN

In [21]:
df_2['cleanState'].value_counts()

cleanState
清洗成功     411952
清洗失败      13145
黑名单       10080
不完整数据      6484
Name: count, dtype: int64