In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [ ]:
ruzu_df = pd.read_excel('/data/home/yansn/naojiye/data/入组表_20250814.xlsx')

group_map = {
 0:"阴性组"
,1:"细菌性脑膜炎"
,2:"病毒性脑膜炎"
,3:"结核性脑膜炎"
,4:"真菌性脑膜炎"
,5:"肿瘤性脑膜炎"  
,6:"自身免疫性脑膜炎"
# ,7:"神经梅毒性脑膜炎" # 这一期不含有神经梅毒性脑膜炎
,8:"病毒性脑炎"
}

ruzu_df['组名'] = ruzu_df['组别'].apply(lambda x:group_map[x])

In [6]:
ruzu_df.head()

        PID       入组时间  组别 性别  年龄 备注说明        组名
0  86600553 2022-07-08   8  男  32  NaN     病毒性脑炎
1  86600617 2022-08-15   2  男  41    优    病毒性脑膜炎
2  86601650 2024-01-04   6  男  25  NaN  自身免疫性脑膜炎
3  86601774 2024-03-19   3  女  47    优    结核性脑膜炎
4  86601850 2024-04-30   0  男  18  NaN       阴性组

In [ ]:
ruzu_df.to_csv('/data/home/yansn/naojiye/data/ruzu_20250814.csv',index=False)

In [ ]:
ruzu_df = pd.read_csv('/data/home/yansn/naojiye/data/ruzu_20250814.csv')

In [10]:
ruzu_df.head()

        PID        入组时间  组别 性别  年龄 备注说明        组名
0  86600553  2022-07-08   8  男  32  NaN     病毒性脑炎
1  86600617  2022-08-15   2  男  41    优    病毒性脑膜炎
2  86601650  2024-01-04   6  男  25  NaN  自身免疫性脑膜炎
3  86601774  2024-03-19   3  女  47    优    结核性脑膜炎
4  86601850  2024-04-30   0  男  18  NaN       阴性组

In [11]:
ruzu_df.shape

(889, 7)

In [14]:
ruzu_df['组别'].value_counts()

组别
5    149
6    140
8    131
0    124
4    111
2    107
1     64
3     63
Name: count, dtype: int64

In [15]:
ruzu_df.head()

        PID        入组时间  组别 性别  年龄 备注说明        组名
0  86600553  2022-07-08   8  男  32  NaN     病毒性脑炎
1  86600617  2022-08-15   2  男  41    优    病毒性脑膜炎
2  86601650  2024-01-04   6  男  25  NaN  自身免疫性脑膜炎
3  86601774  2024-03-19   3  女  47    优    结核性脑膜炎
4  86601850  2024-04-30   0  男  18  NaN       阴性组

In [ ]:
merged_df = pd.read_csv('/data/home/yansn/naojiye/data/入组患者时间窗内检验清洗数据_20250814.csv')

/tmp/ipykernel_1540988/3899876906.py:1: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_df = pd.read_csv('/home/liuchenzhu/naojiye/data_20250814/data/入组患者时间窗内检验清洗数据_20250814.csv')

In [19]:
merged_df.head()

,_id,error,errorMsg,visitId,inputNumber,patientId,gender,age,testNo,labResultItemNo,testItemName,originalSpecimen,standardSpecimen,specimenMemo,resultStatus,laboratoryId,laboratoryTree,clinicalDiagnose,laboratoryName,originalLaboratoryName,laboratoryStandardVersion,instrumentId,originalAbnormalIndicator,abnormalIndicator,standardResult,standardResultNorm,originalResult,originalReferenceInterval,referenceInterval,standardUnits,originalUnits,resultDateTime,standardResultType,memo,synchronizeTime,reportDateTime,standardQuantitativeResult,abnormal,originalSpecimenId,originalLaboratoryId,reportApplyTime,specimenCollectTime,cleanState,standardNormalizedQuantitative,departmentName,departmentCode
0,99000785_163_99000785_2020-03-20 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD002863,NaN,NaN,"1,3-β-D-葡聚糖",G试验(血浆1-3-B-D葡聚糖),Vb24.33,NaN,M,NaN,"[0,31.25)",31.24,<31.25,"参考值:; 60pg/ml以下,无深部真菌感染;(隐球菌、接合菌除外);60-100pg/m...","[60,100]",pg/ml,pg/ml,2020-03-20T00:00,QUANTIFY,NaN,2025-08-13T15:49:34,2020-03-20T00:00,31.24,True,NaN,NaN,NaN,NaN,清洗成功,-0.719000,西院感染科,NaN
1,99000785_164_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD005052,NaN,NaN,抗桥粒芯糖蛋白1抗体,抗桥粒芯糖蛋白1,Vb24.33,NaN,M,NaN,0.70,0.70,0.70,0.1--20,"[0.1,20]",U/ml,U/ml,2020-03-25T00:00,QUANTIFY,NaN,2025-08-13T15:49:37,2020-03-25T00:00,0.70,False,NaN,NaN,NaN,NaN,清洗成功,0.030151,西院感染科,NaN
2,99000785_165_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD005053,NaN,NaN,抗桥粒芯糖蛋白3抗体,抗桥粒芯糖蛋白3,Vb24.33,NaN,M,NaN,0.10,0.10,0.10,0.1--20,"[0.1,20]",U/ml,U/mL,2020-03-25T00:00,QUANTIFY,NaN,2025-08-13T15:49:37,2020-03-25T00:00,0.10,False,NaN,NaN,NaN,NaN,清洗成功,0.000000,西院感染科,NaN
3,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,脑脊液,脑脊液,NaN,NaN,LTI_SD002984,NaN,NaN,细菌培养,细菌培养,Vb24.33,NaN,M,NaN,【细菌培养】未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN
4,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,脑脊液,脑脊液,NaN,NaN,LTI_SD002984,NaN,NaN,细菌培养,细菌培养,Vb24.33,NaN,M,NaN,未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN

In [20]:
merged_df.columns

Index(['_id', 'error', 'errorMsg', 'visitId', 'inputNumber', 'patientId',
       'gender', 'age', 'testNo', 'labResultItemNo', 'testItemName',
       'originalSpecimen', 'standardSpecimen', 'specimenMemo', 'resultStatus',
       'laboratoryId', 'laboratoryTree', 'clinicalDiagnose', 'laboratoryName',
       'originalLaboratoryName', 'laboratoryStandardVersion', 'instrumentId',
       'originalAbnormalIndicator', 'abnormalIndicator', 'standardResult',
       'standardResultNorm', 'originalResult', 'originalReferenceInterval',
       'referenceInterval', 'standardUnits', 'originalUnits', 'resultDateTime',
       'standardResultType', 'memo', 'synchronizeTime', 'reportDateTime',
       'standardQuantitativeResult', 'abnormal', 'originalSpecimenId',
       'originalLaboratoryId', 'reportApplyTime', 'specimenCollectTime',
       'cleanState', 'standardNormalizedQuantitative', 'departmentName',
       'departmentCode'],
      dtype='object')

In [5]:
# 获取清洗成功的行
cleaned_df = merged_df[merged_df['error'] == False].copy()
# 删除全为空的列
empty_cols = cleaned_df.columns[cleaned_df.isna().all()].tolist()
print(f"全为空的列有{len(empty_cols)}列：{empty_cols}")
# 删除无意义的id列，以及与清洗状态相关的列
cleaned_df = cleaned_df[[col for col in cleaned_df.columns if col not in empty_cols + ['_id', 'error', 'errorMsg','cleanState']]].copy()
# 删除只有1个取值的列（nunique=1的列）
unique_cols = cleaned_df.columns[cleaned_df.nunique() == 1].tolist()
cleaned_df = cleaned_df[[col for col in cleaned_df.columns if col not in unique_cols]]
# 发现两个时间列完全相同：cleaned_df["resultDateTime"].equals(cleaned_df["reportDateTime"]), 去掉其中一列
if cleaned_df["resultDateTime"].equals(cleaned_df["reportDateTime"]):
    print("两列完全相同，删除reportDateTime")
    cleaned_df = cleaned_df[[col for col in cleaned_df.columns if col not in ['reportDateTime']]]

# 去掉original特征列
original_col = ['originalLaboratoryName', 'originalAbnormalIndicator',
                 'originalSpecimen', 'originalResult', 'originalReferenceInterval', 'originalUnits']

cleaned_df = cleaned_df[[col for col in cleaned_df.columns if col not in original_col]]

print(f"清洗后数据集有{cleaned_df.shape[0]}行，{cleaned_df.shape[1]}列")

全为空的列有17列：['errorMsg', 'visitId', 'inputNumber', 'testNo', 'labResultItemNo', 'testItemName', 'specimenMemo', 'resultStatus', 'laboratoryTree', 'clinicalDiagnose', 'instrumentId', 'memo', 'originalSpecimenId', 'originalLaboratoryId', 'reportApplyTime', 'specimenCollectTime', 'departmentCode']
两列完全相同，删除reportDateTime
清洗后数据集有412122行，18列

In [ ]:
# 保存清洗后的数据
cleaned_df.to_csv("/data/home/yansn/naojiye/data/all_cleaned_data.csv", index=False)

In [ ]:
cleaned_df = pd.read_csv("/data/home/yansn/naojiye/data/all_cleaned_data.csv")

In [34]:
cleaned_df.shape

(412122, 24)

In [14]:
cleaned_df.dtypes

patientId                           int64
gender                             object
age                                 int64
originalSpecimen                   object
standardSpecimen                   object
laboratoryId                       object
laboratoryName                     object
originalLaboratoryName             object
originalAbnormalIndicator          object
abnormalIndicator                  object
standardResult                     object
standardResultNorm                 object
originalResult                     object
originalReferenceInterval          object
referenceInterval                  object
standardUnits                      object
originalUnits                      object
resultDateTime                     object
standardResultType                 object
standardQuantitativeResult        float64
abnormal                           object
standardNormalizedQuantitative    float64
departmentName                     object
dtype: object

In [13]:
cleaned_df.columns

Index(['patientId', 'gender', 'age', 'originalSpecimen', 'standardSpecimen',
       'laboratoryId', 'laboratoryName', 'originalLaboratoryName',
       'originalAbnormalIndicator', 'abnormalIndicator', 'standardResult',
       'standardResultNorm', 'originalResult', 'originalReferenceInterval',
       'referenceInterval', 'standardUnits', 'originalUnits', 'resultDateTime',
       'standardResultType', 'standardQuantitativeResult', 'abnormal',
       'standardNormalizedQuantitative', 'departmentName'],
      dtype='object')

In [37]:
cleaned_df.head()

,patientId,gender,age,originalSpecimen,standardSpecimen,laboratoryId,laboratoryName,originalLaboratoryName,originalAbnormalIndicator,abnormalIndicator,standardResult,standardResultNorm,originalResult,originalReferenceInterval,referenceInterval,standardUnits,originalUnits,resultDateTime,standardResultType,synchronizeTime,standardQuantitativeResult,abnormal,standardNormalizedQuantitative,departmentName
0,99000785,男,36.0,血,血,LTI_SD002863,"1,3-β-D-葡聚糖",G试验(血浆1-3-B-D葡聚糖),M,NaN,"[0,31.25)",31.24,<31.25,"参考值:; 60pg/ml以下,无深部真菌感染;(隐球菌、接合菌除外);60-100pg/m...","[60,100]",pg/ml,pg/ml,2020-03-20T00:00,QUANTIFY,2025-08-13T15:49:34,31.24,True,-0.719000,西院感染科
1,99000785,男,36.0,血,血,LTI_SD005052,抗桥粒芯糖蛋白1抗体,抗桥粒芯糖蛋白1,M,NaN,0.70,0.70,0.70,0.1--20,"[0.1,20]",U/ml,U/ml,2020-03-25T00:00,QUANTIFY,2025-08-13T15:49:37,0.70,False,0.030151,西院感染科
2,99000785,男,36.0,血,血,LTI_SD005053,抗桥粒芯糖蛋白3抗体,抗桥粒芯糖蛋白3,M,NaN,0.10,0.10,0.10,0.1--20,"[0.1,20]",U/ml,U/mL,2020-03-25T00:00,QUANTIFY,2025-08-13T15:49:37,0.10,False,0.000000,西院感染科
3,99000785,男,36.0,脑脊液,脑脊液,LTI_SD002984,细菌培养,细菌培养,M,NaN,【细菌培养】未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,2025-08-13T15:49:41,NaN,False,NaN,西院感染科
4,99000785,男,36.0,脑脊液,脑脊液,LTI_SD002984,细菌培养,细菌培养,M,NaN,未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,2025-08-13T15:49:41,NaN,False,NaN,西院感染科

In [15]:
# 一个患者可能有多次result记录
dict(cleaned_df.groupby(['patientId'])['resultDateTime'].nunique())

{86600553: 16,
 86601650: 6,
 86601774: 11,
 86601850: 3,
 86602056: 8,
 91101790: 3,
 91106432: 4,
 91138055: 8,
 91147528: 5,
 91148248: 31,
 91154329: 101,
 91159563: 7,
 91163064: 4,
 91173371: 2,
 91174804: 1,
 91195121: 4,
 91195867: 25,
 91205423: 22,
 91207998: 4,
 91214679: 20,
 91215446: 9,
 91216052: 22,
 91217598: 49,
 91217736: 9,
 91218151: 5,
 91218558: 6,
 91219111: 14,
 91219139: 65,
 91219615: 9,
 91219718: 16,
 91220093: 7,
 91221086: 13,
 91221101: 7,
 91221104: 64,
 91221163: 18,
 91221526: 29,
 91221817: 6,
 91222235: 8,
 91222278: 5,
 91222515: 5,
 91222551: 7,
 91222934: 16,
 91223571: 5,
 91223771: 67,
 91224970: 15,
 91225335: 5,
 91225610: 37,
 91226000: 2,
 91226337: 6,
 91226476: 6,
 91227037: 5,
 91227327: 7,
 91227566: 14,
 91228398: 18,
 91229161: 4,
 91231328: 8,
 91231420: 6,
 91231576: 9,
 91232072: 11,
 91232219: 7,
 91232585: 14,
 91232894: 7,
 91232967: 9,
 91233414: 22,
 91233950: 9,
 91234905: 65,
 91235367: 25,
 91235405: 2,
 91235629: 10,
 91235692: 13,
 91236074: 37,
 91236775: 73,
 91237043: 17,
 91237152: 5,
 91237195: 5,
 91237694: 9,
 91237786: 20,
 91238876: 4,
 91238984: 9,
 91238986: 94,
 91239687: 12,
 91239704: 19,
 91239771: 8,
 91240634: 4,
 91241390: 17,
 91241811: 19,
 91242879: 27,
 91243130: 18,
 91244066: 23,
 91244536: 8,
 91244804: 5,
 91245240: 123,
 91245267: 17,
 91246103: 19,
 91246282: 12,
 91246838: 47,
 91246887: 12,
 91246947: 13,
 91247704: 24,
 91248405: 26,
 91248959: 121,
 91249743: 25,
 91249995: 24,
 91251954: 46,
 91252723: 106,
 91255340: 20,
 91256380: 40,
 91256987: 2,
 91258468: 45,
 91259530: 30,
 91261340: 31,
 91264691: 3,
 91265598: 28,
 91266264: 3,
 91267959: 17,
 91270211: 57,
 91271363: 5,
 91271923: 111,
 91272763: 27,
 91273007: 23,
 91274157: 9,
 91276922: 4,
 91279108: 23,
 91280241: 11,
 91281111: 47,
 91283051: 13,
 91284772: 33,
 91286382: 7,
 91290466: 48,
 91294936: 27,
 91295850: 28,
 91297486: 8,
 91297805: 19,
 91298011: 25,
 91299342: 28,
 91301011: 17,
 91301024: 23,
 91302576: 38,
 91307951: 31,
 91308238: 8,
 91310424: 26,
 91311531: 15,
 91312728: 25,
 91312830: 7,
 91312950: 7,
 91314446: 28,
 91314516: 35,
 91315744: 62,
 91315935: 43,
 91316000: 5,
 91316399: 16,
 91318537: 20,
 91320926: 14,
 91320948: 52,
 91321256: 10,
 91321867: 9,
 91321990: 34,
 91322129: 8,
 91322440: 9,
 91322677: 3,
 91322694: 18,
 91323205: 3,
 91323353: 3,
 91323421: 4,
 91323537: 11,
 91323834: 6,
 91324526: 12,
 91324664: 11,
 91324923: 12,
 91324948: 6,
 91325398: 6,
 91325697: 4,
 91325739: 6,
 91326114: 8,
 91326259: 9,
 91326388: 2,
 91326566: 4,
 91326652: 18,
 91327045: 7,
 91327079: 8,
 91327182: 4,
 91327511: 3,
 91327628: 4,
 91327692: 3,
 91327704: 3,
 91327824: 17,
 91327836: 6,
 91327902: 7,
 91328341: 41,
 91328542: 4,
 91328593: 4,
 91328622: 33,
 91328685: 3,
 91328693: 2,
 91328866: 3,
 91329655: 4,
 91329656: 18,
 91329781: 27,
 91330301: 5,
 91330871: 18,
 91330878: 8,
 91331162: 9,
 91331698: 20,
 91331703: 7,
 91331705: 13,
 91332079: 24,
 91333487: 16,
 91333581: 6,
 91333625: 5,
 91333704: 13,
 91333905: 11,
 91333998: 9,
 91334470: 2,
 91334472: 7,
 91334657: 15,
 91334908: 15,
 91334957: 3,
 91335335: 15,
 91335497: 7,
 91335803: 15,
 91335949: 33,
 91335954: 4,
 91336005: 5,
 91336843: 4,
 91337319: 16,
 91337325: 7,
 91337751: 2,
 91337870: 4,
 91337935: 5,
 91338182: 9,
 91338381: 13,
 91338631: 3,
 91339078: 5,
 91339433: 11,
 91339647: 5,
 91339870: 3,
 91339970: 35,
 91340065: 7,
 91340066: 2,
 91340275: 23,
 91340365: 6,
 91340835: 4,
 91340866: 4,
 91340960: 4,
 91340973: 6,
 91341055: 5,
 91341211: 9,
 91341367: 30,
 91343526: 39,
 91343527: 5,
 91343565: 11,
 91343591: 4,
 91343812: 2,
 91343992: 4,
 91344089: 3,
 91344421: 7,
 91344528: 38,
 91344973: 14,
 91346171: 5,
 91346557: 4,
 91346596: 4,
 91346778: 4,
 91348051: 6,
 91348071: 13,
 91348369: 10,
 91349317: 3,
 91349350: 2,
 91349988: 3,
 91350548: 4,
 91350662: 3,
 91350716: 6,
 91352162: 3,
 91352172: 9,
 91352301: 20,
 91353336: 4,
 91354125: 34,
 91354784: 9,
 91355850: 5,
 91355961: 4,
 91357443: 12,
 91357835: 4,
 91357976: 3,
 91359077: 12,
 91359533: 5,
 91365483: 26,
 95052532: 8,
 96001016: 10,
 96001061: 8,
 96008964: 33,
 96009080: 38,
 96009202: 17,
 96010251: 35,
 96010286: 13,
 96011639: 12,
 96013368: 13,
 96013957: 34,
 96014070: 36,
 96014235: 30,
 96014916: 23,
 96015161: 6,
 96015208: 5,
 96015227: 35,
 96016161: 28,
 96016204: 7,
 96016382: 10,
 96017106: 14,
 96017395: 20,
 96017534: 32,
 96019137: 24,
 96019242: 11,
 96020195: 51,
 96020306: 21,
 96020320: 30,
 96020385: 4,
 96020473: 11,
 96020568: 17,
 96020585: 6,
 96020693: 17,
 96020731: 2,
 96020759: 5,
 96020873: 37,
 96021066: 80,
 96021096: 12,
 96021112: 11,
 96021195: 5,
 96021274: 36,
 96021353: 4,
 96021409: 9,
 96021820: 23,
 96022005: 29,
 96022280: 15,
 96022781: 6,
 96022817: 6,
 96023021: 24,
 96023171: 12,
 96023619: 51,
 96023755: 50,
 96023981: 18,
 96024009: 15,
 96024041: 44,
 96024295: 4,
 96024337: 49,
 96024603: 3,
 96024826: 35,
 96024853: 24,
 96025327: 14,
 96025378: 11,
 96026338: 62,
 96028252: 2,
 96028508: 15,
 96029004: 7,
 96030892: 21,
 96030916: 4,
 96030997: 5,
 96031089: 18,
 96031545: 9,
 96031631: 28,
 96032479: 7,
 96033894: 11,
 96034221: 5,
 96036415: 8,
 96036417: 8,
 96036716: 18,
 96036797: 16,
 96037052: 17,
 96037747: 11,
 96037808: 18,
 96037944: 8,
 96038701: 17,
 96039594: 26,
 96039686: 20,
 96039695: 5,
 96039703: 29,
 96040062: 5,
 96040238: 7,
 96040310: 19,
 96040500: 15,
 96040502: 4,
 96040566: 51,
 96041106: 4,
 96041352: 5,
 96041721: 18,
 96042047: 5,
 96042093: 5,
 96042606: 3,
 96043168: 32,
 96043717: 28,
 96043908: 13,
 96044271: 3,
 96044321: 20,
 96045700: 15,
 96045780: 32,
 96045854: 54,
 96046050: 8,
 96046702: 15,
 96046803: 3,
 96046830: 67,
 96046863: 4,
 96046885: 3,
 96046905: 3,
 96046939: 7,
 96047086: 5,
 96047228: 12,
 96047343: 7,
 96047381: 17,
 96047490: 8,
 96047522: 9,
 96047933: 40,
 96048070: 40,
 96048183: 5,
 96048369: 3,
 96048431: 15,
 96048890: 5,
 96049136: 9,
 96049306: 10,
 96049394: 4,
 96049542: 46,
 96049697: 49,
 96049728: 12,
 96049729: 8,
 96050003: 10,
 96050148: 16,
 96050300: 4,
 96050774: 20,
 96050794: 3,
 96050932: 23,
 96051014: 17,
 96051029: 12,
 96051033: 9,
 96051186: 4,
 96051529: 39,
 96051774: 5,
 96051904: 7,
 96052003: 7,
 96052209: 3,
 96052807: 29,
 96052861: 23,
 96053152: 28,
 96053448: 3,
 96054146: 4,
 96054513: 22,
 96054549: 3,
 96054832: 13,
 96055188: 7,
 96055212: 4,
 96055270: 7,
 96055355: 13,
 96056271: 4,
 96056388: 6,
 96057057: 5,
 96057519: 34,
 96058548: 22,
 96058557: 12,
 96058973: 29,
 96059313: 18,
 96059442: 4,
 96060518: 32,
 96061044: 10,
 96061551: 9,
 96061905: 17,
 96062160: 9,
 96062189: 3,
 96062255: 6,
 96062310: 27,
 96062819: 4,
 96063483: 4,
 96063511: 8,
 96063830: 14,
 96064560: 5,
 96067714: 10,
 96068515: 14,
 96068806: 9,
 96069669: 9,
 96070032: 3,
 96070480: 8,
 96072220: 4,
 96073219: 4,
 96073466: 12,
 96073573: 18,
 96074965: 3,
 96075378: 3,
 96076131: 4,
 97026270: 5,
 97035910: 3,
 97038964: 37,
 97047268: 77,
 97049075: 6,
 97051092: 5,
 97051261: 3,
 97051504: 11,
 97052268: 2,
 97053114: 4,
 97053728: 84,
 99000492: 2,
 99000785: 17,
 99001136: 3,
 99017461: 7,
 99020623: 8,
 99023141: 6,
 99025501: 13,
 99040195: 25,
 99049833: 52,
 99050637: 5,
 99051486: 6,
 99052437: 47,
 99052958: 69,
 99056327: 45,
 99059947: 17,
 99059996: 8,
 99060734: 43,
 99060963: 11,
 99061762: 9,
 99062975: 3,
 99063331: 3,
 99063414: 9,
 99063528: 3,
 99063589: 3,
 99063701: 26,
 99063712: 49,
 99064117: 10,
 99064193: 3,
 99064858: 3,
 99065100: 7,
 99065167: 12,
 99065784: 7,
 99066148: 4,
 99067186: 6,
 99067230: 6,
 99067513: 43,
 99067523: 4,
 99068202: 4,
 99068348: 59,
 99068614: 10,
 99068619: 6,
 99068891: 3,
 99068913: 4,
 99069163: 51,
 99070375: 34,
 99070502: 21,
 99070584: 6,
 99070770: 13,
 99070845: 7,
 99071312: 3,
 99071437: 4,
 99071450: 14,
 99071605: 3,
 99071814: 14,
 99072210: 7,
 99072220: 7,
 99072226: 7,
 99072581: 5,
 99074188: 4,
 99074801: 8,
 99075344: 13,
 99075346: 5,
 99075528: 16,
 99076089: 16,
 99076273: 13,
 99076776: 6,
 99076780: 1,
 99077184: 18,
 99077678: 4,
 99077850: 15,
 99078312: 8,
 99078777: 13,
 99080188: 10,
 99080759: 11,
 99081024: 4,
 99081162: 62,
 99081247: 6,
 99081914: 7,
 99082990: 10,
 99083063: 35,
 99083131: 6,
 99083280: 7,
 99084028: 90,
 99084497: 5,
 99085971: 98,
 99086102: 51,
 99086315: 42,
 99087386: 20,
 99087444: 16,
 99088230: 30,
 99088423: 14,
 99089392: 102,
 99090019: 16,
 99091238: 43,
 99091544: 21,
 99091548: 14,
 99091914: 48,
 99092271: 10,
 99092352: 20,
 99092357: 13,
 99092438: 6,
 99092460: 35,
 99093336: 12,
 99093795: 29,
 99094029: 7,
 99094737: 24,
 99095119: 28,
 99095384: 5,
 99095598: 19,
 99095907: 25,
 99095964: 25,
 99096012: 20,
 99096484: 16,
 99097008: 24,
 99097078: 7,
 99097717: 21,
 99097938: 24,
 99098219: 19,
 99099112: 13,
 99099833: 9,
 99100326: 26,
 99100386: 17,
 99100395: 11,
 99100396: 9,
 99101304: 7,
 99101578: 25,
 99101699: 15,
 99102454: 29,
 99102937: 10,
 99103199: 14,
 99103366: 6,
 99103446: 10,
 99103839: 22,
 99104572: 26,
 99104641: 6,
 99105218: 2,
 99105527: 10,
 99105840: 5,
 99105937: 11,
 99106094: 75,
 99106644: 12,
 99106858: 23,
 99107275: 16,
 99108161: 5,
 99108232: 10,
 99108238: 17,
 99108600: 4,
 99108657: 7,
 99108914: 4,
 99109239: 30,
 99110206: 4,
 99110464: 18,
 99111618: 19,
 99112656: 3,
 99112732: 4,
 99113077: 10,
 99113196: 9,
 99114065: 21,
 99114188: 26,
 99114708: 6,
 99115852: 7,
 99115913: 8,
 99116507: 37,
 99116515: 12,
 99116719: 15,
 99116810: 20,
 99117008: 45,
 99117245: 6,
 99117493: 20,
 99117551: 6,
 99117578: 16,
 99117595: 37,
 99117744: 12,
 99118149: 26,
 99118457: 4,
 99118563: 6,
 99118591: 17,
 99118708: 6,
 99118987: 15,
 99119009: 12,
 99119292: 69,
 99120357: 4,
 99120361: 5,
 99120435: 13,
 99120806: 3,
 99120890: 3,
 99120951: 5,
 99121012: 12,
 99121095: 4,
 99121254: 17,
 99121604: 29,
 99121655: 19,
 99122375: 12,
 99123147: 11,
 99123429: 12,
 99123570: 70,
 99124322: 7,
 99124500: 8,
 99124810: 3,
 99125097: 21,
 99125523: 2,
 99125653: 17,
 99126178: 20,
 99126705: 14,
 99126856: 2,
 99127228: 7,
 99128112: 6,
 99128154: 31,
 99128253: 6,
 99128556: 31,
 99128790: 17,
 99129343: 6,
 99129899: 16,
 99130006: 6,
 99130064: 16,
 99130730: 6,
 99130752: 6,
 99131319: 78,
 99131517: 6,
 99132016: 9,
 99132241: 24,
 99132842: 9,
 99133051: 14,
 99133148: 23,
 99133401: 5,
 99133858: 21,
 99133945: 9,
 99134037: 28,
 99134079: 34,
 99134164: 5,
 99134363: 9,
 99134882: 9,
 99135179: 23,
 99135307: 7,
 99135333: 23,
 99135966: 18,
 99137288: 3,
 99137311: 2,
 99137684: 9,
 99137923: 4,
 99138200: 4,
 99138370: 5,
 99138792: 3,
 99139001: 11,
 99139223: 7,
 99139570: 2,
 99139740: 6,
 99139745: 4,
 99140025: 43,
 99140239: 9,
 99140264: 9,
 99140369: 4,
 99140569: 3,
 99140606: 14,
 99140875: 25,
 99141307: 10,
 99141636: 10,
 99141736: 4,
 99141835: 4,
 99141906: 29,
 99142371: 9,
 99142773: 3,
 99143109: 4,
 99143769: 3,
 99143920: 10,
 99144034: 6,
 99144137: 16,
 99144344: 4,
 99144924: 5,
 99144989: 22,
 99145194: 30,
 99145583: 19,
 99146210: 8,
 99146317: 6,
 99146570: 21,
 99146711: 33,
 99146744: 6,
 99146760: 3,
 99146929: 7,
 99146974: 5,
 99146997: 23,
 99147104: 3,
 99147548: 12,
 99147667: 5,
 99148072: 19,
 99148723: 6,
 99148746: 8,
 99149170: 5,
 99149540: 4,
 99149852: 5,
 99149875: 4,
 99150586: 29,
 99151069: 43,
 99151141: 6,
 99151718: 11,
 99151801: 37,
 99151850: 6,
 99151873: 8,
 99152163: 5,
 99152522: 37,
 99153161: 9,
 99153705: 7,
 99153838: 25,
 99154078: 3,
 99154324: 6,
 99155567: 13,
 99155711: 4,
 99155824: 43,
 99156027: 6,
 99156081: 5,
 99156095: 4,
 99157108: 10,
 99157221: 26,
 99157426: 4,
 99158360: 11,
 99158424: 8,
 99158603: 9,
 99158880: 6,
 99158909: 17,
 99159128: 8,
 99159666: 5,
 99160102: 4,
 99160111: 3,
 99160840: 6,
 99161240: 26,
 99161504: 3,
 99162014: 5,
 99162193: 39,
 99162851: 8,
 99162909: 4,
 99163003: 12,
 99163427: 17,
 99163910: 6,
 99163990: 4,
 99164089: 7,
 99164384: 20,
 99164911: 8,
 99165056: 18,
 99165303: 2,
 99165395: 10,
 99165698: 11,
 99165725: 7,
 99165874: 3,
 99166146: 3,
 99166173: 3,
 99166445: 4,
 99166674: 3,
 99166828: 8,
 99166848: 6,
 99167177: 4,
 99167454: 5,
 99167519: 4,
 99167645: 5,
 99167735: 3,
 99167908: 5,
 99167961: 4,
 99168369: 3,
 99168400: 10,
 99168413: 4,
 99168484: 7,
 99168509: 5,
 99168573: 4,
 99168649: 4,
 99168770: 6,
 99168846: 3,
 99168887: 2,
 99168916: 13,
 99169094: 5,
 99169106: 5,
 99169492: 8,
 99169576: 2,
 99169586: 7,
 99169952: 3,
 99169978: 3,
 99170300: 10,
 99170431: 3,
 99170600: 10,
 99170659: 3,
 99170818: 3,
 99170869: 7,
 99170896: 15,
 99170946: 12,
 99170981: 25,
 99171401: 5,
 99171780: 7,
 99171798: 10,
 99171984: 9,
 99173128: 3,
 99173349: 3,
 99173535: 2}

In [17]:
cleaned_df.groupby(['patientId'])['resultDateTime'].nunique().sum()

13483

In [102]:
cleaned_df['resultDateTime'].nunique()

1472

In [100]:
cleaned_df['resultDateTime'].value_counts()

resultDateTime
2024-04-22T00:00    2877
2024-04-26T00:00    2840
2024-04-23T00:00    2700
2024-01-08T00:00    2653
2024-03-22T00:00    2622
                    ...
2021-01-09T00:00       1
2020-11-24T00:00       1
2021-02-05T00:00       1
2020-04-08T00:00       1
2021-03-16T00:00       1
Name: count, Length: 1472, dtype: int64

In [86]:
cleaned_df.nunique().sort_values()

gender                                2
abnormal                              2
standardResultType                    3
abnormalIndicator                     3
originalAbnormalIndicator             6
standardSpecimen                     22
departmentName                       47
originalSpecimen                     49
standardUnits                        68
originalUnits                       114
age                                 138
laboratoryName                      754
patientId                           883
laboratoryId                        985
referenceInterval                  1158
originalLaboratoryName             1398
reportDateTime                     1472
resultDateTime                     1472
originalReferenceInterval          1797
standardQuantitativeResult        23749
standardResultNorm                28169
standardResult                    28588
originalResult                    31070
standardNormalizedQuantitative    82905
dtype: int64

In [79]:
cleaned_df['standardResultType'].value_counts()

standardResultType
QUANTIFY       627327
QUALITATIVE     95204
DESCRIPTIVE     59365
Name: count, dtype: int64