In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("/data/home/yansn/naojiye/data/入组患者时间窗内检验清洗数据_20250814.csv")

# df = df[df['error']== False]
df.shape

/tmp/ipykernel_3639194/1318343010.py:1: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/data/home/yansn/naojiye/data/入组患者时间窗内检验清洗数据_20250814.csv")

(441661, 46)

In [3]:
import math
# 检测originalResult和standardResultNorm是否一致
def same_or_not(row):
    if pd.isna(row['originalResult']) and pd.isna(row['standardResultNorm']):
        return 1
    if not pd.isna(row['originalResult']) and not pd.isna(row['standardResultNorm']):
        return 1
    return 0


df['是否一致'] = df.apply(same_or_not, axis=1)
df

,_id,error,errorMsg,visitId,inputNumber,patientId,gender,age,testNo,labResultItemNo,testItemName,originalSpecimen,standardSpecimen,specimenMemo,resultStatus,laboratoryId,laboratoryTree,clinicalDiagnose,laboratoryName,originalLaboratoryName,laboratoryStandardVersion,instrumentId,originalAbnormalIndicator,abnormalIndicator,standardResult,standardResultNorm,originalResult,originalReferenceInterval,referenceInterval,standardUnits,originalUnits,resultDateTime,standardResultType,memo,synchronizeTime,reportDateTime,standardQuantitativeResult,abnormal,originalSpecimenId,originalLaboratoryId,reportApplyTime,specimenCollectTime,cleanState,standardNormalizedQuantitative,departmentName,departmentCode,是否一致
0,99000785_163_99000785_2020-03-20 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD002863,NaN,NaN,"1,3-β-D-葡聚糖",G试验(血浆1-3-B-D葡聚糖),Vb24.33,NaN,M,NaN,"[0,31.25)",31.24,<31.25,"参考值:; 60pg/ml以下,无深部真菌感染;(隐球菌、接合菌除外);60-100pg/m...","[60,100]",pg/ml,pg/ml,2020-03-20T00:00,QUANTIFY,NaN,2025-08-13T15:49:34,2020-03-20T00:00,31.24,True,NaN,NaN,NaN,NaN,清洗成功,-0.719000,西院感染科,NaN,1
1,99000785_164_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD005052,NaN,NaN,抗桥粒芯糖蛋白1抗体,抗桥粒芯糖蛋白1,Vb24.33,NaN,M,NaN,0.70,0.70,0.70,0.1--20,"[0.1,20]",U/ml,U/ml,2020-03-25T00:00,QUANTIFY,NaN,2025-08-13T15:49:37,2020-03-25T00:00,0.70,False,NaN,NaN,NaN,NaN,清洗成功,0.030151,西院感染科,NaN,1
2,99000785_165_99000785_2020-03-25 00:00:00__158...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,血,血,NaN,NaN,LTI_SD005053,NaN,NaN,抗桥粒芯糖蛋白3抗体,抗桥粒芯糖蛋白3,Vb24.33,NaN,M,NaN,0.10,0.10,0.10,0.1--20,"[0.1,20]",U/ml,U/mL,2020-03-25T00:00,QUANTIFY,NaN,2025-08-13T15:49:37,2020-03-25T00:00,0.10,False,NaN,NaN,NaN,NaN,清洗成功,0.000000,西院感染科,NaN,1
3,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,脑脊液,脑脊液,NaN,NaN,LTI_SD002984,NaN,NaN,细菌培养,细菌培养,Vb24.33,NaN,M,NaN,【细菌培养】未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN,1
4,99000785_1_99000785_2020-03-18 00:00:00__15844...,False,NaN,NaN,NaN,99000785,男,36.0,NaN,NaN,NaN,脑脊液,脑脊液,NaN,NaN,LTI_SD002984,NaN,NaN,细菌培养,细菌培养,Vb24.33,NaN,M,NaN,未生长,阴性,培养3天无细菌生长,NaN,NaN,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00,NaN,False,NaN,NaN,NaN,NaN,清洗成功,NaN,西院感染科,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441656,96083865_436294_96083865_2025-07-04 00:00:00__...,True,"黑名单,检验ID标准化失败,化验名称黑名单",NaN,NaN,96083865,男,54.0,NaN,NaN,NaN,血,血,NaN,NaN,NaN,NaN,NaN,NaN,BZ3,Vb24.33,NaN,M,NaN,1.09,1.09,1.09,NaN,NaN,NaN,NaN,2025-07-04T00:00,QUANTIFY,NaN,2025-08-13T19:39:20,2025-07-04T00:00,1.09,False,NaN,NaN,NaN,NaN,黑名单,NaN,北院肿瘤科,NaN,1
441657,96083865_436345_96083865_2025-07-04 00:00:00__...,True,"化验名称标准化失败,检验ID标准化失败",NaN,NaN,96083865,男,54.0,NaN,NaN,NaN,血,血,NaN,NaN,NaN,NaN,NaN,NaN,肌酸激酶同功酶质量,Vb24.33,NaN,M,NaN,0.65,0.65,0.65,男性 ＜4.87|女性 ＜3.61,"[0,4.87)",ng/ml,ng/ml,2025-07-04T00:00,QUANTIFY,NaN,2025-08-13T19:39:20,2025-07-04T00:00,0.65,False,NaN,NaN,NaN,NaN,清洗失败,0.133745,北院肿瘤科,NaN,1
441658,96083865_436364_96083865_2025-07-04 00:00:00__...,True,"黑名单,检验ID标准化失败,化验名称黑名单",NaN,NaN,96083865,男,54.0,NaN,NaN,NaN,血液,血,NaN,NaN,NaN,NaN,NaN,NaN,BZ,Vb24.33,NaN,M,NaN,2.48,2.48,2.48,NaN,NaN,NaN,NaN,2025-07-04T00:00,QUANTIFY,NaN,2025-08-13T19:39:20,2025-07-04T00:00,2.48,False,NaN,NaN,NaN,NaN,黑名单,NaN,北院肿瘤科,NaN,1
441659,96083865_436527_96083865_2025-07-04 00:00:00__...,True,"检验结果标准化失败,黑名单,检验ID标准化失败,化验名称黑名单",NaN,NaN,96083865,男,54.0,NaN,NaN,NaN,血,血,NaN,NaN,NaN,NaN,NaN,NaN,推片状态,Vb24.33,NaN,M,NaN,NaN,NaN,无需推片,NaN,NaN,NaN,NaN,2025-07-04T00:00,NaN,NaN,2025-08-13T19:39:20,2025-07-04T00:00,NaN,NaN,NaN,NaN,NaN,NaN,黑名单,NaN,北院肿瘤科,NaN,0
441660,96083865_436528_96083865_2025-07-04 00:00:00__...,True,"黑名单,检验ID标准化失败,化验名称黑名单",NaN,NaN,96083865,男,54.0,NaN,NaN,NaN,血,血,NaN,NaN,NaN,NaN,NaN,NaN,血细胞分析(三分类以上),Vb24.33,NaN,M,NaN,1.0,1.0,1.0,0--1,"[0,1]",NaN,NaN,2025-07-04T00:00,QUANTIFY,NaN,2025-08-13T19:39:20,2025-07-04T00:00,1.00,False,NaN,NaN,NaN,NaN,黑名单,1.000000,北院肿瘤科,NaN,1

In [4]:
df[df['是否一致']==0][['originalResult','standardResultNorm']].head()

         originalResult standardResultNorm
159                   :                NaN
263                   :                NaN
602                   :                NaN
605                   :                NaN
606  KOH涂片：阴性 (未查见真菌菌体)                NaN

In [5]:
import pandas as pd
import numpy as np

# 传入减少原始列的新csv文件
# 只考虑组合定量、定性的特征

df = pd.read_csv("/data/home/yansn/naojiye/data/all_cleaned_data.csv")  # 根据实际情况读取你的数据

# 步骤1：确保resultDateTime列的格式一致，不修改列名，只取日期部分
df['resultDate'] = pd.to_datetime(df['resultDateTime']).dt.date  # 保留原始的resultDateTime列

# 步骤2：定义一个函数来生成新的列名
def create_column_name(row):
    """
    生成新列名，根据标准样本和实验室名称以及结果类型
    """
    standard_specimen = row['standardSpecimen']
    laboratory_name = row['laboratoryName']
    result_type = row['standardResultType']
    
    # 拼接出新列名
    if pd.isna(result_type):
        return None
    if result_type == 'QUALITATIVE':
        return f"{standard_specimen}_{laboratory_name}_定性"
    if result_type == 'QUANTIFY':
        return f"{standard_specimen}_{laboratory_name}_定量"
    if result_type == 'DESCRIPTIVE':
        return f"{standard_specimen}_{laboratory_name}_描述性"
    return None

# 步骤3：为每一行创建新的列名
df['new_column_name'] = df.apply(create_column_name, axis=1)

# 步骤4：根据patientId和resultDate进行分组，聚合数据
# 用一个字典来保存每个患者每个日期的所有结果
aggregated_data = {}

for _, row in df.iterrows():
    patient_id = row['patientId']
    result_date = row['resultDate']  # 保持一致的日期格式
    age = row['age']  # 获取患者的年龄
    gender = row['gender']  # 获取患者的性别
    new_col_name = row['new_column_name']
    result_type = row['standardResultType']
    value_1 = row['standardQuantitativeResult']
    value_2 = row['standardResultNorm']
    # 如果有新列名，才添加
    if new_col_name:
        # 如果还没有添加该患者该日期的数据，初始化
        if (patient_id, result_date) not in aggregated_data:
            aggregated_data[(patient_id, result_date)] = {
                'patientId': patient_id,
                'resultDateTime': result_date,
                'age': age,
                'gender': gender
            }
        
        # 为该患者该日期添加新的列
        if result_type  == 'QUANTIFY':
            aggregated_data[(patient_id, result_date)][new_col_name] = value_2
        elif result_type in ['DESCRIPTIVE','QUALITATIVE']:
            aggregated_data[(patient_id, result_date)][new_col_name] = value_2

# 步骤5：将聚合的数据转换为DataFrame
# 创建最终的DataFrame
final_data = []
for (patient_id, result_date), values in aggregated_data.items():
    final_data.append(values)

# 转换成DataFrame
final_df = pd.DataFrame(final_data)

# 步骤6：保存为CSV文件
# final_df.to_csv("/home/ruiqitang/naojiye/data/wide_data.csv", index=False)

In [6]:
final_df.to_csv("/data/home/yansn/naojiye/data/wide_data.csv", index=False)

In [6]:
df.head()

,patientId,gender,age,standardSpecimen,laboratoryId,laboratoryName,abnormalIndicator,standardResult,standardResultNorm,referenceInterval,standardUnits,resultDateTime,standardResultType,synchronizeTime,standardQuantitativeResult,abnormal,standardNormalizedQuantitative,departmentName,resultDate,new_column_name
0,99000785,男,36.0,血,LTI_SD002863,"1,3-β-D-葡聚糖",NaN,"[0,31.25)",31.24,"[60,100]",pg/ml,2020-03-20T00:00,QUANTIFY,2025-08-13T15:49:34,31.24,True,-0.719000,西院感染科,2020-03-20,"血_1,3-β-D-葡聚糖_定量"
1,99000785,男,36.0,血,LTI_SD005052,抗桥粒芯糖蛋白1抗体,NaN,0.70,0.70,"[0.1,20]",U/ml,2020-03-25T00:00,QUANTIFY,2025-08-13T15:49:37,0.70,False,0.030151,西院感染科,2020-03-25,血_抗桥粒芯糖蛋白1抗体_定量
2,99000785,男,36.0,血,LTI_SD005053,抗桥粒芯糖蛋白3抗体,NaN,0.10,0.10,"[0.1,20]",U/ml,2020-03-25T00:00,QUANTIFY,2025-08-13T15:49:37,0.10,False,0.000000,西院感染科,2020-03-25,血_抗桥粒芯糖蛋白3抗体_定量
3,99000785,男,36.0,脑脊液,LTI_SD002984,细菌培养,NaN,【细菌培养】未生长,阴性,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,2025-08-13T15:49:41,NaN,False,NaN,西院感染科,2020-03-18,脑脊液_细菌培养_描述性
4,99000785,男,36.0,脑脊液,LTI_SD002984,细菌培养,NaN,未生长,阴性,NaN,NaN,2020-03-18T00:00,DESCRIPTIVE,2025-08-13T15:49:41,NaN,False,NaN,西院感染科,2020-03-18,脑脊液_细菌培养_描述性

In [7]:
df[['standardResultNorm','standardQuantitativeResult','standardResultType','standardUnits','synchronizeTime','resultDateTime']].head()

,standardResultNorm,standardQuantitativeResult,standardResultType,standardUnits,synchronizeTime,resultDateTime
0,31.24,31.24,QUANTIFY,pg/ml,2025-08-13T15:49:34,2020-03-20T00:00
1,0.70,0.70,QUANTIFY,U/ml,2025-08-13T15:49:37,2020-03-25T00:00
2,0.10,0.10,QUANTIFY,U/ml,2025-08-13T15:49:37,2020-03-25T00:00
3,阴性,NaN,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00
4,阴性,NaN,DESCRIPTIVE,NaN,2025-08-13T15:49:41,2020-03-18T00:00

In [8]:
# 对比standardQuantitativeResult和standardResultNorm是否一致
import math
def test2(row):
    if not math.isnan(row['standardQuantitativeResult']):
        if float(row['standardResultNorm']) == row['standardQuantitativeResult']:
            return 1
        return 0
    
    return 0

df['结果对比'] = df.apply(test2, axis=1)

In [9]:
dict(df.groupby(['standardResultType'])['结果对比'].nunique())

{'DESCRIPTIVE': np.int64(1),
 'QUALITATIVE': np.int64(1),
 'QUANTIFY': np.int64(2)}

In [10]:
df[df['standardResultType']=='QUALITATIVE'][['结果对比','standardResultNorm','standardQuantitativeResult']]

        结果对比 standardResultNorm  standardQuantitativeResult
9          0                 阳性                         NaN
11         0                 阳性                         NaN
20         0                 阴性                         NaN
21         0                 阴性                         NaN
29         0                 阴性                         NaN
...      ...                ...                         ...
412039     0                 阴性                         NaN
412040     0                  Ⅱ                         NaN
412041     0                 阴性                         NaN
412044     0                 阴性                         NaN
412047     0                 阴性                         NaN

[51922 rows x 3 columns]

In [11]:
ruzu_df = pd.read_csv('/data/home/yansn/naojiye/data/ruzu_20250814.csv')

In [12]:
# ruzu_df['分组'].value_counts()
ruzu_df = ruzu_df.rename(columns={'PID':'patientId'})
ruzu_df = ruzu_df.rename(columns={'组别':'分组'})
ruzu_df

    patientId        入组时间  分组 性别  年龄 备注说明        组名
0    86600553  2022-07-08   8  男  32  NaN     病毒性脑炎
1    86600617  2022-08-15   2  男  41    优    病毒性脑膜炎
2    86601650  2024-01-04   6  男  25  NaN  自身免疫性脑膜炎
3    86601774  2024-03-19   3  女  47    优    结核性脑膜炎
4    86601850  2024-04-30   0  男  18  NaN       阴性组
..        ...         ...  .. ..  ..  ...       ...
884  96052492  2024-03-27   5  女  45  NaN    肿瘤性脑膜炎
885  96082288  2025-05-20   5  女  62  NaN    肿瘤性脑膜炎
886  96079917  2025-04-17   5  女  42  NaN    肿瘤性脑膜炎
887  96080024  2025-04-17   5  男  59  NaN    肿瘤性脑膜炎
888  B0143585  2021-08-16   5  女  63  NaN    肿瘤性脑膜炎

[889 rows x 7 columns]

In [13]:
#统计日期数

group_data1 = dict(final_df.groupby(['patientId'])['resultDateTime'].nunique())
group_data2 = {}
for key in group_data1:
    group_data2[str(key)] = group_data1[key]


def add_date_count(row):
    a = row['patientId']

    if a not in group_data2.keys():
        print(a)
        return None 
    
    return int(group_data2[a])

    
ruzu_df['日期数'] = ruzu_df.apply(add_date_count, axis=1)

ruzu_df

91195165
B0143585

    patientId        入组时间  分组 性别  年龄 备注说明        组名   日期数
0    86600553  2022-07-08   8  男  32  NaN     病毒性脑炎  16.0
1    86600617  2022-08-15   2  男  41    优    病毒性脑膜炎  10.0
2    86601650  2024-01-04   6  男  25  NaN  自身免疫性脑膜炎   6.0
3    86601774  2024-03-19   3  女  47    优    结核性脑膜炎  12.0
4    86601850  2024-04-30   0  男  18  NaN       阴性组   3.0
..        ...         ...  .. ..  ..  ...       ...   ...
884  96052492  2024-03-27   5  女  45  NaN    肿瘤性脑膜炎   3.0
885  96082288  2025-05-20   5  女  62  NaN    肿瘤性脑膜炎   2.0
886  96079917  2025-04-17   5  女  42  NaN    肿瘤性脑膜炎   7.0
887  96080024  2025-04-17   5  男  59  NaN    肿瘤性脑膜炎   4.0
888  B0143585  2021-08-16   5  女  63  NaN    肿瘤性脑膜炎   NaN

[889 rows x 8 columns]

In [14]:
# 患者来就诊的最小和最大日期
all_dates_dict = {}

def all_dates(row):
    
    if str(row['patientId']) not in all_dates_dict:
        all_dates_dict[str(row['patientId'])] = [row['resultDateTime']]
    
    else:
        all_dates_dict[str(row['patientId'])].append(row['resultDateTime'])

final_df.apply(all_dates, axis=1)
# 患者来就诊的最小日期
def mini_date(row):
    a = row['patientId']

    if a not in all_dates_dict.keys():
        print(a)
        return None 
    
    return sorted(all_dates_dict[a])[0]

# 患者来就诊的最大日期
def max_date(row):
    a = row['patientId']

    if a not in all_dates_dict.keys():
        print(a)
        return None 
    
    return sorted(all_dates_dict[a])[-1]


ruzu_df['最小日期'] = ruzu_df.apply(mini_date, axis=1)
ruzu_df['最大日期'] = ruzu_df.apply(max_date, axis=1)

ruzu_df

91195165
B0143585
91195165
B0143585

,patientId,入组时间,分组,性别,年龄,备注说明,组名,日期数,最小日期,最大日期
0,86600553,2022-07-08,8,男,32,NaN,病毒性脑炎,16.0,2022-07-08,2022-07-27
1,86600617,2022-08-15,2,男,41,优,病毒性脑膜炎,10.0,2022-08-15,2022-08-24
2,86601650,2024-01-04,6,男,25,NaN,自身免疫性脑膜炎,6.0,2024-01-01,2024-01-11
3,86601774,2024-03-19,3,女,47,优,结核性脑膜炎,12.0,2024-03-19,2024-04-15
4,86601850,2024-04-30,0,男,18,NaN,阴性组,3.0,2024-05-01,2024-05-06
...,...,...,...,...,...,...,...,...,...,...
884,96052492,2024-03-27,5,女,45,NaN,肿瘤性脑膜炎,3.0,2024-03-27,2024-03-29
885,96082288,2025-05-20,5,女,62,NaN,肿瘤性脑膜炎,2.0,2025-05-20,2025-05-21
886,96079917,2025-04-17,5,女,42,NaN,肿瘤性脑膜炎,7.0,2025-04-16,2025-04-27
887,96080024,2025-04-17,5,男,59,NaN,肿瘤性脑膜炎,4.0,2025-04-17,2025-04-24
888,B0143585,2021-08-16,5,女,63,NaN,肿瘤性脑膜炎,NaN,None,None

In [15]:
# 患者入组日期距离最小日期的天数
from datetime import datetime
 

def days_count(row):
    if row['最小日期'] is None :
        return None 
    d1 = datetime.strptime(row['入组时间'], "%Y-%m-%d")
    d2 = datetime.strptime(str(row['最小日期']), "%Y-%m-%d")
    return (d1 - d2).days
    
ruzu_df['日期差'] = ruzu_df.apply(days_count, axis=1)
# ruzu_df['日期差'] = ruzu_df['日期差'].astype(int)

ruzu_df

,patientId,入组时间,分组,性别,年龄,备注说明,组名,日期数,最小日期,最大日期,日期差
0,86600553,2022-07-08,8,男,32,NaN,病毒性脑炎,16.0,2022-07-08,2022-07-27,0.0
1,86600617,2022-08-15,2,男,41,优,病毒性脑膜炎,10.0,2022-08-15,2022-08-24,0.0
2,86601650,2024-01-04,6,男,25,NaN,自身免疫性脑膜炎,6.0,2024-01-01,2024-01-11,3.0
3,86601774,2024-03-19,3,女,47,优,结核性脑膜炎,12.0,2024-03-19,2024-04-15,0.0
4,86601850,2024-04-30,0,男,18,NaN,阴性组,3.0,2024-05-01,2024-05-06,-1.0
...,...,...,...,...,...,...,...,...,...,...,...
884,96052492,2024-03-27,5,女,45,NaN,肿瘤性脑膜炎,3.0,2024-03-27,2024-03-29,0.0
885,96082288,2025-05-20,5,女,62,NaN,肿瘤性脑膜炎,2.0,2025-05-20,2025-05-21,0.0
886,96079917,2025-04-17,5,女,42,NaN,肿瘤性脑膜炎,7.0,2025-04-16,2025-04-27,1.0
887,96080024,2025-04-17,5,男,59,NaN,肿瘤性脑膜炎,4.0,2025-04-17,2025-04-24,0.0
888,B0143585,2021-08-16,5,女,63,NaN,肿瘤性脑膜炎,NaN,None,None,NaN

In [177]:
ruzu_df.to_excel('/data/home/yansn/naojiye/data/ruzu_20250825.xlsx',index=False)

In [16]:
# 大特征下面的小特征类
feature = list(final_df.columns)[4:]

feature_dict = {}

for i in feature:
    item = i.split('_')
    if item[0] not in feature_dict.keys():
        feature_dict[item[0]] = [item[1]]
    else:
        feature_dict[item[0]].append(item[1])

feature_df = pd.DataFrame.from_dict(feature_dict, orient='index')
feature_df

# feature_df = pd.DataFrame.from_records([{k: v} for k, v in feature_dict.items()])
# print(feature_df.fillna(method='ffill'))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639
血,"1,3-β-D-葡聚糖",抗桥粒芯糖蛋白1抗体,抗桥粒芯糖蛋白3抗体,隐球菌荚膜抗原,隐球菌荚膜抗原,半乳甘露聚糖,细胞.CD3-CD19+百分比,细胞.CD3+百分比,细胞.CD3+CD4+百分比,细胞.CD4+/CD8+,细胞.CD3+CD8+百分比,细胞.CD3-CD16+CD56+百分比,肌酸激酶.MB型[质量法],B型钠尿肽前体,肌钙蛋白T,肌红蛋白,促甲状腺激素,促甲状腺激素受体抗体,甲状腺过氧化物酶抗体,抗甲状腺球蛋白抗体,甲状腺素,三碘甲状腺原氨酸,游离T4,游离T3,降钙素原,铁蛋白,D-二聚体,活化部分凝血活酶时间,凝血酶原时间国际标准化比值,凝血酶时间,凝血酶原时间,纤维蛋白原,纤维蛋白降解产物,肾小球滤过率,γ谷氨酰转肽酶,白蛋白,白蛋白/球蛋白,丙氨酸氨基转移酶,总胆固醇,低密度脂蛋白胆固醇,二氧化碳结合力,非高密度脂蛋白胆固醇,甘油三酯,高密度脂蛋白胆固醇,肌酐,钾,碱性磷酸酶,氯,钠,尿素,尿酸,前白蛋白,球蛋白,门冬氨酸氨基转移酶,磷,钙,镁,脂蛋白a,直接胆红素,总胆红素,总胆汁酸,总蛋白,葡萄糖[空腹],腺苷脱氨酶,小而密脂蛋白胆固醇,C反应蛋白,白细胞计数,大血小板细胞比率,单核细胞百分比,单核细胞计数,红细胞分布宽度,红细胞计数,红细胞比容,淋巴细胞百分比,淋巴细胞计数,平均红细胞体积,平均红细胞血红蛋白含量,平均红细胞血红蛋白浓度,平均血小板体积,嗜碱性粒细胞百分比,嗜碱性粒细胞计数,嗜酸性粒细胞百分比,嗜酸性粒细胞计数,总血红蛋白浓度,血小板分布宽度,血小板计数,中性粒细胞百分比,中性粒细胞计数,红细胞沉降率,免疫球蛋白A,免疫球蛋白E,免疫球蛋白G,免疫球蛋白M,胱抑素C,抗双链DNA抗体,抗JO-1抗体,抗U1-nRNP抗体/SM抗体,抗PM-SCL抗体,抗RO-52蛋白抗体,抗SCL-70抗体,抗SM抗体,抗核糖体抗体,抗核小体抗体,抗PCNA抗体,载脂蛋白A1,载脂蛋白B,血小板/淋巴细胞比值,中性粒细胞/淋巴细胞比值,雌二醇,睾酮,促黄体生成素,孕酮,促卵泡激素,催乳素,皮质醇,绒毛膜促性腺激素,脱氢表雄酮,性激素结合球蛋白,游离雄激素指数,免疫球蛋白G4亚型,同型半胱氨酸,游离脂肪酸,抗凝血酶III,β2微球蛋白,超敏C反应蛋白,铜蓝蛋白,转铁蛋白,M蛋白,抗双链DNA抗体,抗核抗体,抗胞浆型中性粒细胞抗体,抗环瓜氨酸肽抗体,抗JO-1抗体,髓过氧化物酶,抗U1-nRNP抗体/SM抗体,抗核周型中性粒细胞抗体,抗PCNA抗体,抗PM-SCL抗体,蛋白酶3,抗RO-52蛋白抗体,抗SCL-70抗体,抗SM抗体,抗SS-A抗体,抗SS-B抗体,抗核糖体抗体,抗核小体抗体,抗线粒体M2抗体,抗着丝点B抗体,抗组蛋白抗体,α羟丁酸脱氢酶,肌酸激酶,乳酸脱氢酶,Q热立克次体抗体.IgM,肺炎衣原体抗体.IgM,肺炎支原体抗体.IgM,副流感病毒抗体.IgM,呼吸道合胞病毒抗体.IgM,甲型流感病毒抗体.IgM,抗嗜肺军团菌抗体.IgM,腺病毒抗体.IgM,乙型流感病毒抗体.IgM,梅毒非特异性抗体,梅毒螺旋体抗体,人类免疫缺陷病毒抗体,细菌培养,乳酸,酮体,N端-B型钠尿肽前体,糖化血红蛋白,淀粉酶,抗心磷脂抗体.IgA,抗心磷脂抗体.IgG,抗心磷脂抗体.IgM,EB病毒衣壳抗体.IgA,EB病毒衣壳抗体.IgG,EB病毒衣壳抗体.IgM,丙型肝炎病毒抗体,乙型肝炎病毒E抗体,乙型肝炎病毒E抗原,乙型肝炎病毒表面抗体,乙型肝炎病毒表面抗原,乙型肝炎病毒核心抗体.IgM,乙型肝炎病毒核心抗体,癌胚抗原,甲胎蛋白,鳞状上皮细胞癌抗原,神经元特异性烯醇化酶,糖类抗原125,糖类抗原15-3,糖类抗原19-9,糖类抗原72-4,细胞角蛋白19片段,巨细胞病毒抗体.IgG,巨细胞病毒抗体.IgM,KAP/LAM,轻链.κ型,轻链.λ型,补体C3,补体C4,抗链球菌溶血素O抗体,类风湿因子,ABO血型鉴定,Rh血型,不规则抗体,直接抗人球蛋白试验,类风湿因子.IgA,类风湿因子.IgG,类风湿因子.IgM,α1球蛋白,α2球蛋白,β球蛋白,γ球蛋白,抗SS-A抗体,抗SS-B抗体,抗线粒体M2抗体,抗着丝点抗体,抗组蛋白抗体,抗蛋白酶3抗体.IgG,抗髓过氧化物酶抗体,CD5,中性粒细胞CD64指数,细胞.CD3+CD4+CD8+百分比,初始性B细胞,调节性B细胞,调节性T细胞,记忆性B细胞,原始浆细胞,α-L-岩藻糖苷酶,甘胆酸,亮氨酸氨基肽酶,视黄醇结合蛋白,载脂蛋白A2,载脂蛋白C2,载脂蛋白E,生长激素,甲状腺球蛋白,罗马指数,人附睾蛋白4,轻链κ/λ比值,抗着丝点B抗体,抗心磷脂抗体,间接胆红素,尿素氮,抗核抗体-均质型,唾液酸,淀粉样蛋白A,细胞.CD45+,EB病毒核抗原抗体.IgG,EB病毒早期抗原抗体.IgA,EB病毒早期抗原抗体.IgG,HLA-B27,丙型肝炎病毒抗体,乙型肝炎病毒E抗体,乙型肝炎病毒E抗原,乙型肝炎病毒表面抗原,乙型肝炎病毒核心抗体.IgM,乙型肝炎病毒核心抗体,前列腺特异性抗原,游离前列腺特异性抗原,凝固角Angle,凝血综合指数CI值,纤溶指标EPL值,血栓最大强度G值,凝血速率K值,纤溶指标LY30值,血栓最大幅度MA值,凝血因子反应时间R值,脂肪酶,EB病毒DNA,人类巨细胞病毒DNA,β-羟丁酸,胆碱酯酶,磷脂酶A2,白细胞介素-6,白细胞介素-10,白细胞介素-12p70,白细胞介素-17,白细胞介素-2,白细胞介素-4,干扰素-γ,α肿瘤坏死因子,白细胞介素-2受体,真菌培养,网织红细胞百分比,低荧光强度网织红细胞,高荧光强度网织红细胞,网织红细胞计数,中荧光强度网织红细胞,幼稚网织红细胞百分比,新冠病毒抗体.IgG,新冠病毒抗体.IgM,肝素结合蛋白,B型柯萨奇病毒抗体.IgM,抗中性粒细胞胞质抗体,免疫球蛋白G1亚型,免疫球蛋白G2亚型,免疫球蛋白G3亚型,抗磷脂酶A2受体抗体,抗肾小球基底膜抗体,细胞.CD3-CD19+计数,细胞.CD3-CD16+CD56+计数,细胞.CD3+CD8+计数,细胞.CD3+CD4+计数,细胞.CD3+计数,结核感染T细胞检测,结核感染T细胞测试管,结核感染T细胞阳性对照,结核感染T细胞阴性对照,乙型肝炎病毒DNA,游离/总前列腺特异性抗原,人类巨细胞病毒DNA,肺炎链球菌,抗平滑肌抗体,血管紧张素转换酶,血氨,抗核抗体,抗核抗体-胞浆颗粒型,抗EJ抗体,抗Ku抗体,抗Mi-2抗体,抗PL-12抗体,抗PL-7抗体,C肽,胰岛素,抗肝肾微粒体抗体,抗肝细胞溶质抗原I型抗体,抗核膜糖蛋白210抗体,抗可溶性肝抗原/肝胰抗原抗体,抗可溶性酸性核蛋白抗体,抗早幼粒细胞白血病蛋白抗体,人类免疫缺陷病毒P24抗原,糖类抗原242,糖类抗原50,过敏原特异性IgE检测-霉菌组合(点青/分枝孢/烟曲/交链孢霉),过敏原特异性IgE检测-烟曲霉,IgE总计,胃泌素释放肽前体,维生素B12,维生素B9,甲状旁腺素,心型脂肪酸结合蛋白,转铁蛋白饱和度,不饱和铁结合力,铁,总铁结合力,促红细胞生成素,抗核抗体-颗粒型,异常凝血酶原,葡萄糖[120分钟],中性粒细胞明胶酶相关脂质运载蛋白,硫酸脱氢表雄酮,胃蛋白酶原Ⅰ,胃蛋白酶Ⅰ/胃蛋白酶Ⅱ,胃蛋白酶原Ⅱ,胃泌素-17,中枢神经特异蛋白,丙型肝炎病毒RNA,促肾上腺皮质激素,革兰阳性球菌,溶血葡萄球菌,胰岛素样生长因子-Ⅰ,EB病毒DNA,乙型肝炎病毒DNA,甲胎蛋白异质体,渗透压,抗核抗体-核膜型,抗核抗体-核仁型,红细胞聚集指数,全血低切相对指数,全血高切相对指数,血浆粘度,甲型肝炎病毒抗体.IgM,群体反应性抗体,风疹病毒抗体.IgG,风疹病毒抗体.IgM,降钙素,单纯疱疹病毒Ⅰ型抗体.IgG,单纯疱疹病毒Ⅰ型抗体.IgM,单纯疱疹病毒Ⅱ型抗体.IgG,单纯疱疹病毒Ⅱ型抗体.IgM,维生素A,25-羟维生素D,25-羟基维生素D2,25-羟基维生素D3,维生素E,维生素K,地高辛血药浓度,β-胶原降解产物测定,骨钙素,维生素B1,维生素B2,维生素B3,维生素B5,维生素B6,维生素B7,5甲基四氢叶酸,维生素C,IgG合成指数,血管紧张素Ⅱ,醛固酮/肾素,肾素,醛固酮,抗中性粒细胞胞质抗体,白细胞介素-1β,白细胞介素-5,白细胞介素-8,干扰素-α,幼稚粒细胞百分比,有核红细胞百分比,抗弓形虫抗体.IgG,抗弓形虫抗体.IgM,戊型肝炎病毒抗体.IgG,戊型肝炎病毒抗体.IgM,抗核抗体-线粒体型,抗核抗体-核仁型,晚幼红细胞,疟原虫,乙型肝炎病毒前S1抗原,抗核抗体-均质型,β1球蛋白,β2球蛋白,丙戊酸,结核感染T细胞测试管-阴性对照管,低色素红细胞,网织红细胞血红蛋白含量,A型柯萨奇病毒抗体.IgM,黄疸指数,肌酸激酶.MB型,溶血指数,脂浊指数,红细胞分布宽度标准差,成熟单核细胞,成熟淋巴细胞,EB病毒核抗原抗体.IgG,EB病毒衣壳抗体.IgG,EB病毒早期抗原抗体.IgG,单纯疱疹病毒抗体.IgG,单纯疱疹病毒抗体.IgM,风疹病毒抗体.IgG,Ⅲ型前胶原N端肽,Ⅳ型胶原,层粘连蛋白,透明质酸,补体C1q,谷氨酸脱氢酶,血培养,抗缪勒管激素,α1抗胰蛋白酶,α1酸性糖蛋白,结合珠蛋白,高敏促甲状腺激素,淋巴细胞CD64指数,单核细胞CD64指数,反三碘甲状腺原氨酸,抗Mi-2抗体,抗RNP抗体,抗smD1抗体,抗RO-60蛋白抗体,抗Ku抗体,抗β2-糖蛋白1抗体,抗蛋白酶3抗体,抗EJ抗体,抗PL-12抗体,抗PL-7抗体,葡萄糖[随机],IgG-LAM型M蛋白,血清指数,抗Xa因子活性,谷胱甘肽还原酶,血培养[需氧菌],厌氧菌培养,卡马西平,左乙拉西坦,抗谷氨酸脱羧酶抗体,抗胰岛素抗体,抗胰岛细胞抗体,α2巨球蛋白,抗核抗体-核点型,雄烯二酮,促甲状腺激素受体刺激性抗体,17-羟基孕酮,甲氧基肾上腺素,甲氧基去甲肾上腺素,抗CAGE抗体,抗GAGE7抗体,抗GBU4-5抗体,抗MAGE-A1抗体,抗p53抗体,抗PGP9.5抗体,抗SOX2抗体,游离雌三醇,游离睾酮,丙型肝炎病毒抗体.IgG,梅毒螺旋体抗体,HIV抗原抗体,梅毒非特异性抗体,APOE基因突变分析,糖化白蛋白,β-HCG,抗肝肾微粒体Ⅰ型抗体,抗肝细胞溶质抗原I型抗体,抗核膜糖蛋白210抗体,抗可溶性肝抗原/肝胰抗原抗体,抗可溶性酸性核蛋白抗体,抗线粒体抗体,抗早幼粒细胞白血病蛋白抗体,蛋白C活性,蛋白S活性,总Ⅰ型胶原氨基端延长肽,C肽[120分钟],胰岛素[120分钟],万古霉素血药浓度,氨甲喋呤血药浓度,抗β2-糖蛋白1抗体.IgA,抗β2-糖蛋白1抗体.IgG,抗β2-糖蛋白1抗体.IgM,抗核抗体-胞浆纤维型,超氧物歧化酶,Rh(D)血型鉴定,他克莫司血药浓度,新冠病毒抗体.IgG,新冠病毒抗体.IgM,HIV抗原抗体,抗弓形虫抗体.IgG,酪氨酸磷酸酶抗体,抗胰岛素抗体,抗胰岛细胞抗体,结核感染T细胞阳性对照管-阴性对照管,镉,铅,铜,锌,丙型肝炎病毒RNA,人类免疫缺陷病毒RNA,乙型肝炎病毒DNA,全段甲状旁腺素,黄疸指数,溶血指数,脂浊指数,肌钙蛋白I,有核红细胞计数,可溶性生长刺激表达基因蛋白2,EB病毒DNA,纹带棒状杆菌,丙型肝炎病毒核心抗原,甲型肝炎病毒抗体.IgM,抗核抗体-抗着丝点型,转铁蛋白受体,抗RNP抗体,抗smD1抗体,抗RO-60蛋白抗体,IgG-KAP型M蛋白,革兰阴性杆菌,胰岛素样生长因子结合蛋白3,纤溶酶-抗纤溶酶复合物,凝血酶调节蛋白,卡马西平,葡萄糖[30分钟],葡萄糖[60分钟],葡萄糖[180分钟],狼疮抗凝物初筛试验,狼疮抗凝物确认试验,M蛋白,结核菌培养,C肽[空腹],胰岛素[空腹],血小板最大聚集率,丙型肝炎病毒RNA,3-甲氧酪胺,多巴胺,去甲肾上腺素,肾上腺素,抗核抗体-胞浆颗粒型,Septin9基因甲基化检测,抗突变型瓜氨酸化波形蛋白抗体,抗核抗体-颗粒型,嗜碱性粒细胞百分比,嗜酸性粒细胞百分比,左乙拉西坦,过敏原特异性IgE检测-菠萝,过敏原特异性IgE检测-大豆,过敏原特异性IgE检测-芒果,过敏原特异性IgE检测-牛奶,过敏原特异性IgE检测-牛肉,过敏原特异性IgE检测-蟹类,过敏原特异性IgE检测-虾/对虾,食物不耐受IgG检测-小麦,食物不耐受IgG检测-鳕鱼,过敏原特异性IgE检测-腰果,食物不耐受IgG检测-芝麻,高尔基体蛋白73,异型淋巴细胞百分比,人葡萄球菌,戊型肝炎病毒抗体.IgG,戊型肝炎病毒抗体.IgM,C肽[60分钟],胰岛素[60分钟],抗肝肾微粒体Ⅰ型抗体,金黄色葡萄球菌,IgA-LAM型M蛋白,IgM-KAP型M蛋白,EB病毒RTA蛋白抗体.IgG,HLA位点DR,标准化LAC比值,铜绿假单胞菌,肺炎克雷伯菌,过敏原特异性IgE检测-粉尘螨,过敏原特异性IgE检测-狗皮屑,过敏原特异性IgE检测-屋尘螨,链格孢,过敏原特异性IgE检测-猫皮屑,过敏原特异性IgE检测-牛奶,过敏原特异性IgE检测-虾/对虾,过敏原特异性IgE检测-蟹类,烟曲霉,有核红细胞/100个白细胞,凝血酶原活动度,中幼红细胞,校正钙,大肠埃希菌,肠道病毒EV71抗体.IgM,过敏原特异性IgE检测-热带螨,过敏原特异性IgE检测-蟑螂,过敏原特异性IgE检测-蚕丝,过敏原特异性IgE检测-豚草,过敏原特异性IgE检测-艾蒿,过敏原特异性IgE检测-葎草,过敏原特异性IgE检测-藜/反枝苋,过敏原特异性IgE检测-柏树/榆树/柳树/栎树/桦树/枫树/胡桃树/梧桐树/杨树,过敏原特异性IgE检测-悬铃木/白蜡,过敏原特异性IgE检测-桤/杨/柳/山毛榉/橡/胡桃,过敏原特异性IgE检测-六月禾/黑麦草/梯牧草,过敏原特异性IgE检测-鸡蛋蛋黄,过敏原特异性IgE检测-鸡蛋蛋白,过敏原特异性IgE检测-花生/大豆,过敏原特异性IgE检测-芝麻,过敏原特异性IgE检测-小麦/荞麦,过敏原特异性IgE检测-牛肉/羊肉,过敏原特异性IgE检测-虾/蟹,肺炎支原体抗体.IgG
脑脊液,细菌培养,涂片查细菌,真菌培养,隐球菌荚膜抗原,隐球菌荚膜抗原,抗酸杆菌,分枝杆菌培养,蛋白定量,氯,葡萄糖,红细胞计数,淋巴细胞百分比,巨噬细胞百分比,激活巨噬细胞,激活淋巴细胞,寄生虫镜检,浆细胞,嗜酸性粒细胞百分比,外观,异常细胞百分比,有核细胞计数,幼稚淋巴细胞,真菌涂片检查,中性粒细胞百分比,肿瘤细胞,墨汁染色,蛋白定性,透明度,颜色,"1,3-β-D-葡聚糖",单个核细胞百分比,多个核细胞百分比,半乳甘露聚糖,白蛋白,IgG合成指数,免疫球蛋白G,脑脊液IgG,鞘内IgG合成率[24h],中性粒细胞百分比,结核分枝杆菌DNA,rpoB基因突变分析,脑脊液IgA,脑脊液IgM,癌胚抗原,甲胎蛋白,神经元特异性烯醇化酶,激活淋巴细胞,幼稚淋巴细胞,中性粒细胞百分比,真菌涂片检查,厌氧菌培养,乳酸,浆细胞,有核细胞计数,涂片革兰氏染色,革兰阳性球菌,肺炎链球菌,乳酸脱氢酶,梅毒非特异性抗体,梅毒螺旋体抗体,类酵母菌,激活巨噬细胞,隐球菌,红细胞计数,幼稚淋巴细胞,头状葡萄球菌,巨噬细胞百分比,嗜酸性粒细胞百分比,淋巴细胞百分比,巨噬细胞百分比,淋巴细胞百分比,异常细胞百分比,人葡萄球菌,外观,红细胞计数,单纯疱疹病毒Ⅰ型抗体.IgG,单纯疱疹病毒Ⅰ型抗体.IgM,单纯疱疹病毒Ⅱ型抗体.IgG,单纯疱疹病毒Ⅱ型抗体.IgM,肝素结合蛋白,降钙素原,革兰阴性杆菌,白细胞介素-10,白细胞介素-12p70,白细胞介素-17,白细胞介素-1β,白细胞介素-2,白细胞介素-4,白细胞介素-5,白细胞介素-6,白细胞介素-8,干扰素-α,干扰素-γ,α肿瘤坏死因子,表皮葡萄球菌,EB病毒DNA,EB病毒衣壳抗体.IgA,EB病毒衣壳抗体.IgG,EB病毒衣壳抗体.IgM,EB病毒核抗原抗体.IgG,EB病毒早期抗原抗体.IgA,EB病毒早期抗原抗体.IgG,C反应蛋白,β2微球蛋白,嗜酸性粒细胞百分比,EB病毒核抗原抗体.IgG,EB病毒衣壳抗体.IgG,EB病毒早期抗原抗体.IgG,单纯疱疹病毒抗体.IgG,单纯疱疹病毒抗体.IgM,抗弓形虫抗体.IgG,抗弓形虫抗体.IgM,巨细胞病毒抗体.IgG,巨细胞病毒抗体.IgM,糖类抗原125,糖类抗原15-3,糖类抗原19-9,糖类抗原72-4,细胞角蛋白19片段,巨细胞病毒抗体.IgM,细胞学检查,革兰阳性杆菌,弱抗酸染色涂片,结核菌培养,分枝杆菌培养,细菌培养,厌氧菌培养,糖类抗原50,糖类抗原242,需氧菌培养,异常细胞百分比,涂片查细菌,EB病毒DNA,鲍曼不动杆菌,大肠埃希菌,肺炎克雷伯菌,肺炎链球菌,金黄色葡萄球菌,流感嗜血杆菌,嗜麦芽窄食单胞菌,铜绿假单胞菌,细胞总数,停乳链球菌,溶血葡萄球菌,屎肠球菌,真菌菌丝,嗜碱性粒细胞计数,肿瘤细胞,EB病毒DNA,黏质沙雷菌,肺炎克雷伯菌,α2巨球蛋白,真菌孢子,咽峡炎链球菌,细胞总数,有核细胞计数,科氏葡萄球菌,沃氏葡萄球菌,金黄色葡萄球菌,新型隐球菌,浆细胞,念珠菌属,白色念珠菌,梅毒螺旋体抗体,纹带棒状杆菌,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
粪便,白细胞计数,红细胞计数,粪便性状,粪血液,颜色,隐血,粘液丝,虫卵,寄生虫镜检,原虫,转铁蛋白,幽门螺杆菌抗原,轮状病毒,腺病毒抗原,真菌培养,艰难梭菌抗原,白色念珠菌,霉菌,脓细胞,夏科-雷登结晶,脂肪球,钙卫蛋白,外观,细菌培养,光滑假丝酵母菌,脂肪球,鲍曼不动杆菌,近平滑假丝酵母菌,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
尿,PH值,白细胞计数,白细胞酯酶,病理管型,胆红素,蛋白定性,红细胞计数,酵母菌,结晶,比重,尿胆原,葡萄糖,隐血,上皮细胞,酮体,透明管型,细菌计数,小圆细胞,亚硝酸盐,颜色,透明度,本-周蛋白,白细胞酯酶,管型,红细胞形态镜检,上皮细胞,细菌计数,隐血,红细胞形态镜检,蛋白定性,轻链κ/λ比值,轻链.κ型,轻链.λ型,葡萄糖,蛋白/肌酐,肌酐,蛋白定量,白蛋白,微量白蛋白/肌酐,草酸钙结晶,异型红细胞,β2微球蛋白,α1微球蛋白,免疫球蛋白G,转铁蛋白,白色念珠菌,涂片查细菌,酵母菌,真菌培养,胆红素,上皮细胞,酮体,细菌培养,奇异变形杆菌,革兰阴性杆菌,小圆细胞,钙[24h尿],钾[24h尿],24小时尿量,磷[24h尿],氯[24h尿],钠[24h尿],尿酸[24h尿],葡萄糖[24h尿],蛋白[24h尿],细菌计数,分枝杆菌培养,渗透压,尿胆原,淀粉酶,视黄醇结合蛋白,中性粒细胞明胶酶相关脂质运载蛋白,肌酐[24h尿],肺炎克雷伯菌,琼氏不动杆菌,尿素[24h尿],大肠埃希菌,鲍曼不动杆菌,热带假丝酵母菌,皮质醇[24h尿],钠,屎肠球菌,光滑假丝酵母菌,轻链.κ型,轻链.λ型,类酵母菌,电导率,真菌孢子,光滑假丝酵母菌,尿沉渣定量分析,白细胞计数,细菌培养,红细胞计数,粪肠球菌,克柔假丝酵母菌,类酵母菌,抗酸杆菌,热带假丝酵母菌,绒毛膜促性腺激素,本-周蛋白,鲍曼不动杆菌,大肠埃希菌,肺炎克雷伯菌,金黄色葡萄球菌,嗜麦芽窄食单胞菌,铜绿假单胞菌,雷氏普罗威登斯菌,念珠菌属,透明管型,纹带棒状杆菌,近平滑假丝酵母菌,铜绿假单胞菌,人葡萄球菌,抗坏血酸,尿液精子计数,结晶,表皮葡萄球菌,尿酸结晶,α2巨球蛋白,管型,结核分枝杆菌DNA,卷曲乳杆菌,电导率,革兰阳性球菌,细胞管型,颗粒管型,结晶,金黄色葡萄球菌,淋巴细胞百分比,寄生虫镜检,浆细胞,真菌涂片检查,无乳链球菌[B群],溶血葡萄球菌,含铁血黄素,嗜麦芽窄食单胞菌,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [133]:
feature_df.to_excel("/data/home/yansn/naojiye/data/features.xlsx")

In [17]:
#特征缺失率
none_count = final_df.isna().sum().to_dict()

data_length = final_df.shape[0]
data_length
for key in none_count.keys():
    none_count[key] = none_count[key]/data_length
    # if none_count[key] < 0.5:
    #     print(1)

# 删除没有必要的信息项
none_count.pop('patientId')
none_count.pop('resultDateTime')
none_count.pop('age')
none_count.pop('gender')
none_count

{'血_1,3-β-D-葡聚糖_定量': 0.9247391952309985,
 '血_抗桥粒芯糖蛋白1抗体_定量': 0.9995529061102831,
 '血_抗桥粒芯糖蛋白3抗体_定量': 0.9995529061102831,
 '脑脊液_细菌培养_描述性': 0.8412816691505216,
 '脑脊液_涂片查细菌_描述性': 0.8029806259314456,
 '脑脊液_真菌培养_描述性': 0.9171385991058122,
 '血_隐球菌荚膜抗原_定量': 0.9761549925484352,
 '血_隐球菌荚膜抗原_定性': 0.9400894187779434,
 '脑脊液_隐球菌荚膜抗原_定量': 0.969150521609538,
 '脑脊液_隐球菌荚膜抗原_定性': 0.8988077496274217,
 '血_半乳甘露聚糖_定量': 0.9470938897168405,
 '血_细胞.CD3-CD19+百分比_定量': 0.9157973174366617,
 '血_细胞.CD3+百分比_定量': 0.9087928464977645,
 '血_细胞.CD3+CD4+百分比_定量': 0.9193740685543964,
 '血_细胞.CD4+/CD8+_定量': 0.9157973174366617,
 '血_细胞.CD3+CD8+百分比_定量': 0.9157973174366617,
 '血_细胞.CD3-CD16+CD56+百分比_定量': 0.9157973174366617,
 '脑脊液_抗酸杆菌_描述性': 0.9235469448584203,
 '脑脊液_分枝杆菌培养_定性': 0.9377049180327869,
 '血_肌酸激酶.MB型[质量法]_定量': 0.7242921013412816,
 '血_B型钠尿肽前体_定量': 0.8906110283159463,
 '血_肌钙蛋白T_定量': 0.7239940387481371,
 '血_肌红蛋白_定量': 0.7210134128166915,
 '粪便_白细胞计数_定量': 0.8734724292101341,
 '粪便_红细胞计数_定量': 0.8734724292101341,
 '粪便_粪便性状_描述性': 0.87451564828614,
 '粪便_粪血液_定性': 0.9487332339791357,
 '粪便_颜色_描述性': 0.8737704918032787,
 '粪便_隐血_定性': 0.8761549925484352,
 '粪便_粘液丝_定性': 0.9508196721311475,
 '脑脊液_蛋白定量_定量': 0.7894187779433681,
 '脑脊液_氯_定量': 0.7895678092399404,
 '脑脊液_葡萄糖_定量': 0.7895678092399404,
 '血_促甲状腺激素_定量': 0.9087928464977645,
 '血_促甲状腺激素受体抗体_定量': 0.9201192250372578,
 '血_甲状腺过氧化物酶抗体_定量': 0.8959761549925485,
 '血_抗甲状腺球蛋白抗体_定量': 0.8961251862891207,
 '血_甲状腺素_定量': 0.8853949329359165,
 '血_三碘甲状腺原氨酸_定量': 0.8853949329359165,
 '血_游离T4_定量': 0.8842026825633383,
 '血_游离T3_定量': 0.8842026825633383,
 '血_降钙素原_定量': 0.7666169895678092,
 '血_铁蛋白_定量': 0.8858420268256334,
 '尿_PH值_定量': 0.7718330849478391,
 '尿_白细胞计数_定量': 0.7749627421758569,
 '尿_白细胞酯酶_描述性': 0.9849478390461996,
 '尿_病理管型_定性': 0.7743666169895678,
 '尿_胆红素_定性': 0.7769001490312966,
 '尿_蛋白定性_定性': 0.809538002980626,
 '尿_红细胞计数_定量': 0.7737704918032787,
 '尿_酵母菌_定性': 0.832488822652757,
 '尿_结晶_定性': 0.7742175856929955,
 '尿_比重_定量': 0.7718330849478391,
 '尿_尿胆原_定性': 0.7752608047690015,
 '尿_葡萄糖_定性': 0.78301043219076,
 '尿_隐血_定性': 0.7997019374068555,
 '尿_上皮细胞_定性': 0.9363636363636364,
 '尿_酮体_定性': 0.7779433681073026,
 '尿_透明管型_定性': 0.9254843517138599,
 '尿_细菌计数_定性': 0.9353204172876304,
 '尿_小圆细胞_定性': 0.8320417287630403,
 '尿_亚硝酸盐_定性': 0.7718330849478391,
 '尿_颜色_描述性': 0.7719821162444114,
 '尿_透明度_描述性': 0.7718330849478391,
 '血_D-二聚体_定量': 0.630849478390462,
 '血_活化部分凝血活酶时间_定量': 0.6321907600596125,
 '血_凝血酶原时间国际标准化比值_定量': 0.6318926974664679,
 '血_凝血酶时间_定量': 0.6363636363636364,
 '血_凝血酶原时间_定量': 0.6318926974664679,
 '血_纤维蛋白原_定量': 0.6321907600596125,
 '血_纤维蛋白降解产物_定量': 0.6327868852459017,
 '血_肾小球滤过率_定量': 0.6913561847988078,
 '血_γ谷氨酰转肽酶_定量': 0.6029806259314456,
 '血_白蛋白_定量': 0.5831594634873324,
 '血_白蛋白/球蛋白_定量': 0.6645305514157973,
 '血_丙氨酸氨基转移酶_定量': 0.5998509687034277,
 '血_总胆固醇_定量': 0.8876304023845007,
 '血_低密度脂蛋白胆固醇_定量': 0.8934426229508197,
 '血_二氧化碳结合力_定量': 0.5540983606557377,
 '血_非高密度脂蛋白胆固醇_定量': 0.914903129657228,
 '血_甘油三酯_定量': 0.8874813710879285,
 '血_高密度脂蛋白胆固醇_定量': 0.8913561847988077,
 '血_肌酐_定量': 0.5971684053651267,
 '血_钾_定量': 0.5488822652757079,
 '血_碱性磷酸酶_定量': 0.6029806259314456,
 '血_氯_定量': 0.5514157973174366,
 '血_钠_定量': 0.5491803278688525,
 '血_尿素_定量': 0.6551415797317437,
 '血_尿酸_定量': 0.5997019374068554,
 '血_前白蛋白_定量': 0.7184798807749627,
 '血_球蛋白_定量': 0.6645305514157973,
 '血_门冬氨酸氨基转移酶_定量': 0.6004470938897168,
 '血_磷_定量': 0.5554396423248882,
 '血_钙_定量': 0.5490312965722802,
 '血_镁_定量': 0.5506706408345753,
 '血_脂蛋白a_定量': 0.9065573770491804,
 '血_直接胆红素_定量': 0.6049180327868853,
 '血_总胆红素_定量': 0.6014903129657228,
 '血_总胆汁酸_定量': 0.7415797317436662,
 '血_总蛋白_定量': 0.6076005961251862,
 '血_葡萄糖[空腹]_定量': 0.7201192250372578,
 '血_腺苷脱氨酶_定量': 0.8973174366616989,
 '血_小而密脂蛋白胆固醇_定量': 0.9193740685543964,
 '脑脊液_红细胞计数_定量': 0.7800298062593145,
 '脑脊液_淋巴细胞百分比_定量': 0.8254843517138599,
 '脑脊液_巨噬细胞百分比_定量': 0.8278688524590164,
 '脑脊液_激活巨噬细胞_定性': 0.8293591654247392,
 '脑脊液_激活淋巴细胞_定性': 0.8678092399403875,
 '脑脊液_寄生虫镜检_描述性': 0.8210134128166915,
 '脑脊液_浆细胞_定性': 0.8546944858420268,
 '脑脊液_嗜酸性粒细胞百分比_定性': 0.8403874813710879,
 '脑脊液_外观_描述性': 0.8375558867362146,
 '脑脊液_异常细胞百分比_定性': 0.8445603576751117,
 '脑脊液_有核细胞计数_定量': 0.7783904619970193,
 '脑脊液_幼稚淋巴细胞_定性': 0.8679582712369598,
 '脑脊液_真菌涂片检查_描述性': 0.8195230998509687,
 '脑脊液_中性粒细胞百分比_描述性': 0.9991058122205663,
 '脑脊液_肿瘤细胞_描述性': 0.8245901639344262,
 '血_C反应蛋白_定量': 0.62548435171386,
 '血_白细胞计数_定量': 0.5670640834575261,
 '血_大血小板细胞比率_定量': 0.5719821162444113,
 '血_单核细胞百分比_定量': 0.6685543964232489,
 '血_单核细胞计数_定量': 0.6625931445603577,
 '血_红细胞分布宽度_定量': 0.5698956780923994,
 '血_红细胞计数_定量': 0.5698956780923994,
 '血_红细胞比容_定量': 0.5698956780923994,
 '血_淋巴细胞百分比_定量': 0.6655737704918033,
 '血_淋巴细胞计数_定量': 0.6600596125186289,
 '血_平均红细胞体积_定量': 0.5698956780923994,
 '血_平均红细胞血红蛋白含量_定量': 0.5698956780923994,
 '血_平均红细胞血红蛋白浓度_定量': 0.5698956780923994,
 '血_平均血小板体积_定量': 0.5719821162444113,
 '血_嗜碱性粒细胞百分比_定量': 0.5736214605067064,
 '血_嗜碱性粒细胞计数_定量': 0.5824143070044709,
 '血_嗜酸性粒细胞百分比_定量': 0.5736214605067064,
 '血_嗜酸性粒细胞计数_定量': 0.5807749627421759,
 '血_总血红蛋白浓度_定量': 0.5698956780923994,
 '血_血小板分布宽度_定量': 0.5719821162444113,
 '血_血小板计数_定量': 0.5698956780923994,
 '血_中性粒细胞百分比_定量': 0.5731743666169896,
 '血_中性粒细胞计数_定量': 0.5773472429210134,
 '血_红细胞沉降率_定量': 0.830849478390462,
 '血_免疫球蛋白A_定量': 0.9089418777943368,
 '血_免疫球蛋白E_定量': 0.9347242921013413,
 '血_免疫球蛋白G_定量': 0.9004470938897169,
 '血_免疫球蛋白M_定量': 0.9089418777943368,
 '脑脊液_墨汁染色_描述性': 0.9226527570789866,
 '血_胱抑素C_定量': 0.8497764530551416,
 '脑脊液_蛋白定性_定性': 0.790461997019374,
 '脑脊液_透明度_描述性': 0.790461997019374,
 '脑脊液_颜色_描述性': 0.790461997019374,
 '脑脊液_1,3-β-D-葡聚糖_定量': 0.9655737704918033,
 '血_抗双链DNA抗体_定量': 0.8970193740685544,
 '血_抗JO-1抗体_定量': 0.8985096870342772,
 '血_抗U1-nRNP抗体/SM抗体_定量': 0.9157973174366617,
 '血_抗PM-SCL抗体_定量': 0.8985096870342772,
 '血_抗RO-52蛋白抗体_定量': 0.895230998509687,
 '血_抗SCL-70抗体_定量': 0.9023845007451565,
 '血_抗SM抗体_定量': 0.9157973174366617,
 '血_抗核糖体抗体_定量': 0.9023845007451565,
 '血_抗核小体抗体_定量': 0.9,
 '血_抗PCNA抗体_定量': 0.9023845007451565,
 '血_载脂蛋白A1_定量': 0.9473919523099851,
 '血_载脂蛋白B_定量': 0.9473919523099851,
 '脑脊液_单个核细胞百分比_定量': 0.8734724292101341,
 '脑脊液_多个核细胞百分比_定量': 0.8736214605067064,
 '血_血小板/淋巴细胞比值_定量': 0.6710879284649777,
 '血_中性粒细胞/淋巴细胞比值_定量': 0.6710879284649777,
 '血_雌二醇_定量': 0.9622950819672131,
 '血_睾酮_定量': 0.9619970193740686,
 '血_促黄体生成素_定量': 0.9624441132637854,
 '血_孕酮_定量': 0.9636363636363636,
 '血_促卵泡激素_定量': 0.9624441132637854,
 '血_催乳素_定量': 0.9611028315946348,
 '血_皮质醇_定量': 0.9561847988077496,
 '血_绒毛膜促性腺激素_定量': 0.9695976154992548,
 '血_脱氢表雄酮_定量': 0.9976154992548435,
 '血_性激素结合球蛋白_定量': 0.9666169895678093,
 '血_游离雄激素指数_定量': 0.9736214605067064,
 '血_免疫球蛋白G4亚型_定量': 0.9055141579731744,
 '血_同型半胱氨酸_定量': 0.9342771982116245,
 '血_游离脂肪酸_定量': 0.940983606557377,
 '血_抗凝血酶III_定量': 0.6695976154992549,
 '血_β2微球蛋白_定量': 0.9640834575260805,
 '血_超敏C反应蛋白_定量': 0.9879284649776453,
 '血_铜蓝蛋白_定量': 0.9713859910581222,
 '血_转铁蛋白_定量': 0.9636363636363636,
 '脑脊液_半乳甘露聚糖_定量': 0.9791356184798807,
 '粪便_虫卵_描述性': 0.9,
 '粪便_寄生虫镜检_描述性': 0.9241430700447094,
 '粪便_原虫_描述性': 0.9230998509687034,
 '粪便_转铁蛋白_定性': 0.910581222056632,
 '脑脊液_白蛋白_定量': 0.9493293591654247,
 '脑脊液_IgG合成指数_定量': 0.9523099850968704,
 '脑脊液_免疫球蛋白G_定量': 0.9523099850968704,
 '脑脊液_脑脊液IgG_定量': 0.9496274217585693,
 '脑脊液_鞘内IgG合成率[24h]_定量': 0.9536512667660209,
 '血_M蛋白_描述性': 0.9342771982116245,
 '尿_本-周蛋白_描述性': 0.9578241430700447,
 '血_抗双链DNA抗体_定性': 0.9436661698956781,
 '血_抗核抗体_定性': 0.9023845007451565,
 '血_抗胞浆型中性粒细胞抗体_定性': 0.9053651266766021,
 '血_抗环瓜氨酸肽抗体_定量': 0.9400894187779434,
 '血_抗JO-1抗体_定性': 0.9913561847988077,
 '血_髓过氧化物酶_定量': 0.9324888226527571,
 '血_抗U1-nRNP抗体/SM抗体_定性': 0.9998509687034277,
 '血_抗核周型中性粒细胞抗体_定性': 0.9053651266766021,
 '血_抗PCNA抗体_定性': 0.995230998509687,
 '血_抗PM-SCL抗体_定性': 0.9913561847988077,
 '血_蛋白酶3_定量': 0.9324888226527571,
 '血_抗RO-52蛋白抗体_定性': 0.9898658718330849,
 '血_抗SCL-70抗体_定性': 0.995230998509687,
 '血_抗SM抗体_定性': 0.9998509687034277,
 '血_抗SS-A抗体_定性': 0.9998509687034277,
 '血_抗SS-B抗体_定性': 0.995230998509687,
 '血_抗核糖体抗体_定性': 0.995230998509687,
 '血_抗核小体抗体_定性': 0.995230998509687,
 '血_抗线粒体M2抗体_定性': 0.9918032786885246,
 '血_抗着丝点B抗体_定性': 0.995230998509687,
 '血_抗组蛋白抗体_定性': 0.995230998509687,
 '血_α羟丁酸脱氢酶_定量': 0.8685543964232488,
 '血_肌酸激酶_定量': 0.7631892697466468,
 '血_乳酸脱氢酶_定量': 0.7673621460506707,
 '尿_白细胞酯酶_定性': 0.7865871833084948,
 '尿_管型_定量': 0.848435171385991,
 '尿_红细胞形态镜检_描述性': 0.9712369597615499,
 '尿_上皮细胞_定量': 0.8481371087928465,
 '尿_细菌计数_定量': 0.857973174366617,
 '血_Q热立克次体抗体.IgM_定性': 0.9850968703427719,
 '血_肺炎衣原体抗体.IgM_定性': 0.9780923994038748,
 '血_肺炎支原体抗体.IgM_定性': 0.9780923994038748,
 '血_副流感病毒抗体.IgM_定性': 0.9850968703427719,
 '血_呼吸道合胞病毒抗体.IgM_定性': 0.9780923994038748,
 '血_甲型流感病毒抗体.IgM_定性': 0.9847988077496275,
 '血_抗嗜肺军团菌抗体.IgM_定性': 0.9847988077496275,
 '血_腺病毒抗体.IgM_定性': 0.9780923994038748,
 '血_乙型流感病毒抗体.IgM_定性': 0.9847988077496275,
 '血_梅毒非特异性抗体_定性': 0.9005961251862892,
 '血_梅毒螺旋体抗体_定性': 0.8970193740685544,
 '血_人类免疫缺陷病毒抗体_定性': 0.8964232488822653,
 '血_细菌培养_描述性': 0.9348733233979135,
 '血_乳酸_定量': 0.8761549925484352,
 '血_酮体_定性': 0.9584202682563339,
 '血_N端-B型钠尿肽前体_定量': 0.8353204172876304,
 '血_糖化血红蛋白_定量': 0.892548435171386,
 '尿_隐血_描述性': 0.9707898658718331,
 '血_淀粉酶_定量': 0.9602086438152012,
 '血_抗心磷脂抗体.IgA_定量': 0.9728763040238451,
 '血_抗心磷脂抗体.IgG_定量': 0.9727272727272728,
 '血_抗心磷脂抗体.IgM_定量': 0.9731743666169895,
 '血_EB病毒衣壳抗体.IgA_定性': 0.9856929955290611,
 '血_EB病毒衣壳抗体.IgG_定性': 0.9907600596125187,
 '血_EB病毒衣壳抗体.IgM_定性': 0.9834575260804769,
 '血_丙型肝炎病毒抗体_定性': 0.9625931445603577,
 '血_乙型肝炎病毒E抗体_定性': 0.9576751117734724,
 '血_乙型肝炎病毒E抗原_定性': 0.9567809239940388,
 '血_乙型肝炎病毒表面抗体_定量': 0.9023845007451565,
 '血_乙型肝炎病毒表面抗原_定性': 0.9605067064083458,
 '血_乙型肝炎病毒核心抗体.IgM_定性': 0.9688524590163935,
 '血_乙型肝炎病毒核心抗体_定性': 0.9576751117734724,
 '血_癌胚抗原_定量': 0.8843517138599106,
 '血_甲胎蛋白_定量': 0.8842026825633383,
 '血_鳞状上皮细胞癌抗原_定量': 0.8870342771982116,
 '血_神经元特异性烯醇化酶_定量': 0.8859910581222057,
 '血_糖类抗原125_定量': 0.885096870342772,
 '血_糖类抗原15-3_定量': 0.8880774962742176,
 '血_糖类抗原19-9_定量': 0.885096870342772,
 '血_糖类抗原72-4_定量': 0.8892697466467958,
 '血_细胞角蛋白19片段_定量': 0.8904619970193741,
 '血_巨细胞病毒抗体.IgG_定量': 0.9842026825633383,
 '血_巨细胞病毒抗体.IgM_定性': 0.9842026825633383,
 '血_KAP/LAM_定量': 0.9418777943368107,
 '血_轻链.κ型_定量': 0.9205663189269747,
 '血_轻链.λ型_定量': 0.9205663189269747,
 '血_补体C3_定量': 0.9265275707898659,
 '血_补体C4_定量': 0.9265275707898659,
 '血_抗链球菌溶血素O抗体_定量': 0.9463487332339792,
 '血_类风湿因子_定量': 0.9459016393442623,
 '血_ABO血型鉴定_描述性': 0.9490312965722801,
 '血_Rh血型_定性': 0.9864381520119225,
 '血_不规则抗体_定性': 0.9490312965722801,
 '血_直接抗人球蛋白试验_定性': 0.9490312965722801,
 '血_类风湿因子.IgA_定量': 0.9712369597615499,
 '血_类风湿因子.IgG_定量': 0.9712369597615499,
 '血_类风湿因子.IgM_定量': 0.9712369597615499,
 '脑脊液_中性粒细胞百分比_定量': 0.924441132637854,
 '血_α1球蛋白_定量': 0.9397913561847988,
 '血_α2球蛋白_定量': 0.9397913561847988,
 '血_β球蛋白_定量': 0.9986587183308495,
 '血_γ球蛋白_定量': 0.9397913561847988,
 '粪便_幽门螺杆菌抗原_定性': 0.9611028315946348,
 '尿_红细胞形态镜检_定性': 0.9354694485842027,
 '血_抗SS-A抗体_定量': 0.915946348733234,
 '血_抗SS-B抗体_定量': 0.9025335320417288,
 '血_抗线粒体M2抗体_定量': 0.8986587183308494,
 '血_抗着丝点抗体_定量': 0.9864381520119225,
 '血_抗组蛋白抗体_定量': 0.9025335320417288,
 '血_抗蛋白酶3抗体.IgG_定量': 0.9882265275707899,
 '血_抗髓过氧化物酶抗体_定量': 0.9728763040238451,
 '血_CD5_定量': 0.9983606557377049,
 '血_中性粒细胞CD64指数_定量': 0.9524590163934427,
 '血_细胞.CD3+CD4+CD8+百分比_定量': 0.9891207153502235,
 '血_初始性B细胞_定量': 0.9719821162444113,
 '血_调节性B细胞_定量': 0.9719821162444113,
 '血_调节性T细胞_定量': 0.971833084947839,
 '血_记忆性B细胞_定量': 0.9719821162444113,
 '血_原始浆细胞_定量': 0.9675111773472429,
 '血_α-L-岩藻糖苷酶_定量': 0.8928464977645305,
 '血_甘胆酸_定量': 0.8681073025335321,
 '血_亮氨酸氨基肽酶_定量': 0.8998509687034277,
 '血_视黄醇结合蛋白_定量': 0.8997019374068554,
 '血_载脂蛋白A2_定量': 0.9454545454545454,
 '血_载脂蛋白C2_定量': 0.9456035767511177,
 '血_载脂蛋白E_定量': 0.9307004470938898,
 '尿_蛋白定性_描述性': 0.9614008941877794,
 '血_生长激素_定量': 0.9825633383010433,
 '血_甲状腺球蛋白_定量': 0.9078986587183309,
 '血_罗马指数_定量': 0.9870342771982116,
 '血_人附睾蛋白4_定量': 0.9581222056631893,
 '血_轻链κ/λ比值_定量': 0.9661698956780924,
 '尿_轻链κ/λ比值_定量': 0.992548435171386,
 '尿_轻链.κ型_定量': 0.9748137108792847,
 '尿_轻链.λ型_定量': 0.9748137108792847,
 '血_抗着丝点B抗体_定量': 0.9156482861400894,
 '血_抗心磷脂抗体_定量': 0.9447093889716841,
 '脑脊液_结核分枝杆菌DNA_定性': 0.9484351713859911,
 '脑脊液_rpoB基因突变分析_定性': 0.9484351713859911,
 '血_间接胆红素_定量': 0.9150521609538003,
 '血_尿素氮_定量': 0.9418777943368107,
 '血_抗核抗体-均质型_定量': 0.9992548435171386,
 '鼻/咽拭子_新冠病毒核酸检测_定性': 0.7959761549925485,
 '血_唾液酸_定量': 0.9856929955290611,
 '血_淀粉样蛋白A_定量': 0.8114754098360656,
 '血_细胞.CD45+_定量': 0.9989567809239941,
 '血_EB病毒核抗原抗体.IgG_定性': 0.9918032786885246,
 '血_EB病毒早期抗原抗体.IgA_定性': 0.9867362146050671,
 '血_EB病毒早期抗原抗体.IgG_定性': 0.9918032786885246,
 '血_HLA-B27_定性': 0.9940387481371088,
 '血_丙型肝炎病毒抗体_定量': 0.936661698956781,
 '血_乙型肝炎病毒E抗体_定量': 0.9435171385991058,
 '血_乙型肝炎病毒E抗原_定量': 0.9439642324888227,
 '血_乙型肝炎病毒表面抗原_定量': 0.9217585692995529,
 '血_乙型肝炎病毒核心抗体.IgM_定量': 0.9417287630402384,
 '血_乙型肝炎病毒核心抗体_定量': 0.9436661698956781,
 '血_前列腺特异性抗原_定量': 0.9350223546944858,
 '血_游离前列腺特异性抗原_定量': 0.9350223546944858,
 '血_凝固角Angle_定量': 0.995230998509687,
 '血_凝血综合指数CI值_定量': 0.9953800298062593,
 '血_纤溶指标EPL值_定量': 0.995230998509687,
 '血_血栓最大强度G值_定量': 0.995230998509687,
 '血_凝血速率K值_定量': 0.995230998509687,
 '血_纤溶指标LY30值_定量': 0.995230998509687,
 '血_血栓最大幅度MA值_定量': 0.995230998509687,
 '血_凝血因子反应时间R值_定量': 0.995230998509687,
 '血_脂肪酶_定量': 0.9080476900149032,
 '血_EB病毒DNA_描述性': 0.9554396423248882,
 '血_人类巨细胞病毒DNA_定量': 0.9995529061102831,
 '血_β-羟丁酸_定量': 0.9500745156482862,
 '血_胆碱酯酶_定量': 0.8172876304023845,
 '血_磷脂酶A2_定量': 0.9442622950819672,
 '血_白细胞介素-6_定量': 0.8374068554396423,
 '骨髓_细菌培养_描述性': 0.9986587183308495,
 '动脉血_50%血氧饱和度的氧分压_定量': 0.9728763040238451,
 '动脉血_标准碳酸氢盐浓度_定量': 0.95424739195231,
 '动脉血_二氧化碳分压_定量': 0.9467958271236959,
 '动脉血_血浆二氧化碳总浓度_定量': 0.9809239940387481,
 '动脉血_全血二氧化碳总浓度_定量': 0.9809239940387481,
 '动脉血_肺泡氧分压_定量': 0.9891207153502235,
 '动脉血_离子钙_定量': 0.9470938897168405,
 '动脉血_高铁血红蛋白_定量': 0.9806259314456036,
 '动脉血_呼吸指数_定量': 0.9891207153502235,
 '动脉血_去氧血红蛋白_定量': 0.9806259314456036,
 '动脉血_钾_定量': 0.9470938897168405,
 '动脉血_氯_定量': 0.9469448584202682,
 '动脉血_钠_定量': 0.9469448584202682,
 '动脉血_葡萄糖_定量': 0.9472429210134128,
 '动脉血_氢离子浓度_定量': 0.9891207153502235,
 '动脉血_乳酸_定量': 0.9478390461997019,
 '动脉血_渗透压_定量': 0.9733233979135618,
 '动脉血_实际碱剩余_定量': 0.9576751117734724,
 '动脉血_总血红蛋白浓度_定量': 0.9466467958271237,
 '动脉血_实际碳酸氢盐浓度_定量': 0.9561847988077496,
 '动脉血_PH值_定量': 0.9466467958271237,
 '动脉血_碳氧血红蛋白_定量': 0.9806259314456036,
 '动脉血_标准碱剩余_定量': 0.9596125186289121,
 '动脉血_红细胞比容_定量': 0.9552906110283159,
 '动脉血_有效氧饱和度_定量': 0.9466467958271237,
 '动脉血_氧分压_定量': 0.9466467958271237,
 '动脉血_氧总含量_定量': 0.9722801788375559,
 '动脉血_氧合血红蛋白_定量': 0.9889716840536512,
 '动脉血_阴离子隙_定量': 0.9649776453055141,
 '脑脊液_脑脊液IgA_定量': 0.9953800298062593,
 '脑脊液_脑脊液IgM_定量': 0.9953800298062593,
 '尿_葡萄糖_描述性': 0.9883755588673622,
 '血_白细胞介素-10_定量': 0.9399403874813711,
 '血_白细胞介素-12p70_定量': 0.9412816691505216,
 '血_白细胞介素-17_定量': 0.9412816691505216,
 '血_白细胞介素-2_定量': 0.9412816691505216,
 '血_白细胞介素-4_定量': 0.9412816691505216,
 '血_干扰素-γ_定量': 0.9390461997019374,
 '血_α肿瘤坏死因子_定量': 0.9399403874813711,
 '尿_蛋白/肌酐_定量': 0.9959761549925484,
 '尿_肌酐_定量': 0.994634873323398,
 '尿_蛋白定量_定量': 0.9959761549925484,
 '尿_白蛋白_定量': 0.995230998509687,
 '尿_微量白蛋白/肌酐_定量': 0.9955290611028316,
 '尿_草酸钙结晶_定性': 0.9988077496274218,
 '尿_异型红细胞_描述性': 0.9997019374068554,
 '血_白细胞介素-2受体_定量': 0.9828614008941878,
 '尿_β2微球蛋白_定量': 0.9944858420268257,
 '尿_α1微球蛋白_定量': 0.9949329359165425,
 '尿_免疫球蛋白G_定量': 0.9971684053651266,
 '尿_转铁蛋白_定量': 0.9967213114754099,
 '血_真菌培养_描述性': 0.9895678092399404,
 '血_网织红细胞百分比_定量': 0.9524590163934427,
 '血_低荧光强度网织红细胞_定量': 0.9524590163934427,
 '血_高荧光强度网织红细胞_定量': 0.9524590163934427,
 '血_网织红细胞计数_定量': 0.9524590163934427,
 '血_中荧光强度网织红细胞_定量': 0.9524590163934427,
 '血_幼稚网织红细胞百分比_定量': 0.9524590163934427,
 '脑脊液_癌胚抗原_定量': 0.9845007451564829,
 '脑脊液_甲胎蛋白_定量': 0.9873323397913562,
 '脑脊液_神经元特异性烯醇化酶_定量': 0.9819672131147541,
 '粪便_轮状病毒_定性': 0.9639344262295082,
 '粪便_腺病毒抗原_定性': 0.9712369597615499,
 '尿_白色念珠菌_描述性': 0.9961251862891207,
 '尿_涂片查细菌_描述性': 0.9982116244411326,
 '尿_酵母菌_描述性': 0.9979135618479881,
 '尿_真菌培养_描述性': 0.984053651266766,
 '血_新冠病毒抗体.IgG_定性': 0.9977645305514158,
 '血_新冠病毒抗体.IgM_定性': 0.9977645305514158,
 '鼻/咽拭子_真菌培养_描述性': 0.9998509687034277,
 '粪便_真菌培养_描述性': 0.9992548435171386,
 '血_肝素结合蛋白_定量': 0.9611028315946348,
 '血_B型柯萨奇病毒抗体.IgM_定性': 0.9871833084947839,
 '尿_胆红素_描述性': 0.9947839046199702,
 '尿_上皮细胞_描述性': 0.9883755588673622,
 '尿_酮体_描述性': 0.9937406855439642,
 '脑脊液_激活淋巴细胞_定量': 0.9535022354694486,
 '脑脊液_幼稚淋巴细胞_定量': 0.9543964232488823,
 '脑脊液_中性粒细胞百分比_定性': 0.8977645305514158,
 '脑脊液_真菌涂片检查_定性': 0.9211624441132638,
 '脑脊液_厌氧菌培养_描述性': 0.9998509687034277,
 '脑脊液_乳酸_定量': 0.805812220566319,
 '血_抗中性粒细胞胞质抗体_定性': 0.9988077496274218,
 '尿_细菌培养_描述性': 0.9549925484351713,
 '尿_奇异变形杆菌_描述性': 0.9998509687034277,
 '尿_革兰阴性杆菌_描述性': 0.9994038748137108,
 '血_免疫球蛋白G1亚型_定量': 0.9892697466467958,
 '血_免疫球蛋白G2亚型_定量': 0.9892697466467958,
 '血_免疫球蛋白G3亚型_定量': 0.9892697466467958,
 '血_抗磷脂酶A2受体抗体_定量': 0.9983606557377049,
 '血_抗肾小球基底膜抗体_定量': 0.9868852459016394,
 '血_细胞.CD3-CD19+计数_定量': 0.9320417287630403,
 '血_细胞.CD3-CD16+CD56+计数_定量': 0.9342771982116245,
 '血_细胞.CD3+CD8+计数_定量': 0.9320417287630403,
 '血_细胞.CD3+CD4+计数_定量': 0.9320417287630403,
 '血_细胞.CD3+计数_定量': 0.9320417287630403,
 '血_结核感染T细胞检测_定性': 0.9181818181818182,
 '血_结核感染T细胞测试管_定量': 0.9204172876304024,
 '血_结核感染T细胞阳性对照_定量': 0.9204172876304024,
 '血_结核感染T细胞阴性对照_定量': 0.9180327868852459,
 '血_乙型肝炎病毒DNA_描述性': 0.9947839046199702,
 '血_游离/总前列腺特异性抗原_定量': 0.9362146050670641,
 '血_人类巨细胞病毒DNA_描述性': 0.96274217585693,
 '血_肺炎链球菌_描述性': 0.9998509687034277,
 '脑脊液_浆细胞_定量': 0.9669150521609537,
 '血_抗平滑肌抗体_定性': 0.9937406855439642,
 '尿_小圆细胞_描述性': 0.9997019374068554,
 '尿_钙[24h尿]_定量': 0.9974664679582712,
 '尿_钾[24h尿]_定量': 0.9971684053651266,
 '尿_24小时尿量_定量': 0.9922503725782414,
 '尿_磷[24h尿]_定量': 0.9974664679582712,
 '尿_氯[24h尿]_定量': 0.9974664679582712,
 '尿_钠[24h尿]_定量': 0.9955290611028316,
 '尿_尿酸[24h尿]_定量': 0.9994038748137108,
 '尿_葡萄糖[24h尿]_定量': 0.9983606557377049,
 '尿_蛋白[24h尿]_定量': 0.9958271236959761,
 '血_血管紧张素转换酶_定量': 0.9228017883755588,
 '血_血氨_定量': 0.9530551415797317,
 '脑脊液_有核细胞计数_定性': 0.9953800298062593,
 '脑脊液_涂片革兰氏染色_描述性': 0.9931445603576751,
 '脑脊液_革兰阳性球菌_描述性': 0.9971684053651266,
 '脑脊液_肺炎链球菌_描述性': 0.9998509687034277,
 '尿_细菌计数_描述性': 0.978688524590164,
 'nan_细菌培养_描述性': 0.9989567809239941,
 '痰_抗酸杆菌_描述性': 0.9894187779433681,
 '痰_结核分枝杆菌DNA_定性': 0.9973174366616989,
 '尿_分枝杆菌培养_定性': 0.9994038748137108,
 '脑脊液_乳酸脱氢酶_定量': 0.8059612518628912,
 '血_抗核抗体_描述性': 0.9779433681073025,
 '血_抗核抗体-胞浆颗粒型_定性': 0.9931445603576751,
 '痰_细菌培养_描述性': 0.9742175856929955,
 '痰_类酵母菌_描述性': 0.9995529061102831,
 '痰_分枝杆菌培养_定性': 0.9955290611028316,
 '胃液_隐血_定性': 0.9944858420268257,
 '脑脊液_梅毒非特异性抗体_定性': 0.978688524590164,
 '脑脊液_梅毒螺旋体抗体_定性': 0.9791356184798807,
 '脑脊液_类酵母菌_描述性': 0.9973174366616989,
 '脑脊液_激活巨噬细胞_定量': 0.9919523099850969,
 '尿_渗透压_定量': 0.9958271236959761,
 '血_抗EJ抗体_定量': 0.9941877794336811,
 '血_抗Ku抗体_定量': 0.9812220566318927,
 '血_抗Mi-2抗体_定量': 0.9812220566318927,
 '血_抗PL-12抗体_定量': 0.9941877794336811,
 '血_抗PL-7抗体_定量': 0.9941877794336811,
 '痰_细菌培养_定性': 0.9926974664679583,
 '脑脊液_隐球菌_描述性': 0.9746646795827124,
 '血_C肽_定量': 0.9979135618479881,
 '血_胰岛素_定量': 0.9979135618479881,
 '脑脊液_红细胞计数_描述性': 0.980327868852459,
 '血_抗肝肾微粒体抗体_定量': 0.994634873323398,
 '血_抗肝细胞溶质抗原I型抗体_定量': 0.9935916542473919,
 '血_抗核膜糖蛋白210抗体_定量': 0.9935916542473919,
 '血_抗可溶性肝抗原/肝胰抗原抗体_定量': 0.9935916542473919,
 '血_抗可溶性酸性核蛋白抗体_定量': 0.9935916542473919,
 '血_抗早幼粒细胞白血病蛋白抗体_定量': 0.9935916542473919,
 '血_人类免疫缺陷病毒P24抗原_定性': 0.9096870342771982,
 '血_糖类抗原242_定量': 0.9129657228017883,
 '血_糖类抗原50_定量': 0.9205663189269747,
 '血_过敏原特异性IgE检测-霉菌组合(点青/分枝孢/烟曲/交链孢霉)_定量': 0.9965722801788376,
 '血_过敏原特异性IgE检测-烟曲霉_定量': 0.996274217585693,
 '血_IgE总计_定量': 0.9818181818181818,
 '血_胃泌素释放肽前体_定量': 0.9262295081967213,
 '血_维生素B12_定量': 0.9459016393442623,
 '血_维生素B9_定量': 0.9459016393442623,
 '血_甲状旁腺素_定量': 0.9736214605067064,
 'nan_真菌培养_描述性': 0.9994038748137108,
 '尿_尿胆原_描述性': 0.9964232488822653,
 '脑脊液_幼稚淋巴细胞_描述性': 0.9985096870342772,
 '血_心型脂肪酸结合蛋白_定量': 0.9377049180327869,
 '血_转铁蛋白饱和度_定量': 0.9758569299552906,
 '血_不饱和铁结合力_定量': 0.9749627421758569,
 '血_铁_定量': 0.9719821162444113,
 '血_总铁结合力_定量': 0.9749627421758569,
 '血_促红细胞生成素_定量': 0.9867362146050671,
 '尿_淀粉酶_定量': 0.9964232488822653,
 '血_抗核抗体-颗粒型_定性': 0.9853949329359165,
 '血_异常凝血酶原_定量': 0.9675111773472429,
 '脑脊液_头状葡萄球菌_描述性': 0.9992548435171386,

In [19]:
none_count_df = pd.DataFrame.from_dict(none_count, columns=['缺失率'],orient='index')
none_count_df['缺失率'] = none_count_df['缺失率'].apply(lambda x: '{:.2%}'.format(x))

none_count_df.to_excel("/data/home/yansn/naojiye/data/none_rate.xlsx")

In [18]:
# 关键特征缺失率
feature_dict.keys()

blood_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "血":
        blood_dict[key] = "{:.2%}".format(none_count[key])

naojiye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "脑脊液":
        naojiye_dict[key] = "{:.2%}".format(none_count[key])

niao_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "尿":
        niao_dict[key] = "{:.2%}".format(none_count[key])

tan_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "痰":
        tan_dict[key] = "{:.2%}".format(none_count[key])

fenbian_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "粪便":
        fenbian_dict[key] = "{:.2%}".format(none_count[key])

bi_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "鼻/咽拭子":
        bi_dict[key] = "{:.2%}".format(none_count[key])


gusui_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "骨髓":
        gusui_dict[key] = "{:.2%}".format(none_count[key])

dongmaixue_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "动脉血":
        dongmaixue_dict[key] = "{:.2%}".format(none_count[key])


nan_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "nan":
        nan_dict[key] = "{:.2%}".format(none_count[key])

weiye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "胃液":
        weiye_dict[key] = "{:.2%}".format(none_count[key])

gangshizi_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "肛拭子":
        gangshizi_dict[key] = "{:.2%}".format(none_count[key])


nongzhongye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "脓肿液":
        nongzhongye_dict[key] = "{:.2%}".format(none_count[key])

chuanciye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "穿刺液":
        chuanciye_dict[key] = "{:.2%}".format(none_count[key])

zhishua_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "支刷":
        zhishua_dict[key] = "{:.2%}".format(none_count[key])

daoguan_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "导管":
        daoguan_dict[key] = "{:.2%}".format(none_count[key])

zhiqiguan_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "支气管肺泡灌洗液":
        zhiqiguan_dict[key] = "{:.2%}".format(none_count[key])

tiye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "体液":
        tiye_dict[key] = "{:.2%}".format(none_count[key])

outuwu_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "呕吐物":
        outuwu_dict[key] = "{:.2%}".format(none_count[key])

pixie_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "皮屑":
        pixie_dict[key] = "{:.2%}".format(none_count[key])

pifu_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "皮肤":
        pifu_dict[key] = "{:.2%}".format(none_count[key])

danzhi_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "胆汁":
        danzhi_dict[key] = "{:.2%}".format(none_count[key])

erdao_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "耳道分泌物":
        erdao_dict[key] = "{:.2%}".format(none_count[key])

xiongqiangye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "胸腔液":
        xiongqiangye_dict[key] = "{:.2%}".format(none_count[key])

yinliuye_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "引流液":
        yinliuye_dict[key] = "{:.2%}".format(none_count[key])

yanbu_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "眼部分泌物":
        yanbu_dict[key] = "{:.2%}".format(none_count[key])

fenmiwu_dict = {}
for key in none_count.keys():
    if key.split("_")[0] == "分泌物":
        fenmiwu_dict[key] = "{:.2%}".format(none_count[key])

all_outer_features = [blood_dict,naojiye_dict,fenbian_dict,niao_dict,bi_dict,gusui_dict,dongmaixue_dict,nan_dict,tan_dict,weiye_dict,gangshizi_dict,nongzhongye_dict,chuanciye_dict,zhishua_dict,
                      daoguan_dict,zhiqiguan_dict,tiye_dict,outuwu_dict,pixie_dict,pifu_dict,danzhi_dict,erdao_dict,xiongqiangye_dict,yinliuye_dict,yanbu_dict,fenmiwu_dict]

len(all_outer_features)

26

In [21]:
excel_name = list(feature_dict.keys())
excel_name[4] = "鼻-咽拭子"
excel_count = 0

for item in all_outer_features:
    
    pd.DataFrame.from_dict(item, columns=['缺失率'],orient='index').to_excel("/data/home/yansn/naojiye/data/"+excel_name[excel_count]+".xlsx")
    excel_count += 1

In [19]:
# 患者是否做了关键检测

all_features = list(final_df.columns)[4:]
blood_features =[]
naojiye_features = []
niaojian_features = []
tan_features = []

inter_features = {}
outer_features = list(feature_dict.keys())

for i in outer_features:
    inter_features[i] = []


for i in all_features:
    for a in outer_features:
        if i.split("_")[0] == a:
            inter_features[a].append(i)
inter_features

def check_features(row):
    
    for i in inter_features[feature_name]:
        if (isinstance(row[i],str) and row[i] is not None) or (isinstance(row[i],float) and not math.isnan(row[i])):
            return 1
    return 0


for i in outer_features:
    feature_name = i
    final_df[feature_name] = final_df.apply(check_features, axis=1)

In [20]:
guanjianjiance_final_df = final_df[['patientId','resultDateTime','age','gender']+outer_features]
guanjianjiance_final_df = guanjianjiance_final_df.rename(columns={'resultDateTime': '报告时间'})
guanjianjiance_final_df.head()

,patientId,报告时间,age,gender,血,脑脊液,粪便,尿,鼻/咽拭子,骨髓,动脉血,nan,痰,胃液,肛拭子,脓肿液,穿刺液,支刷,导管,支气管肺泡灌洗液,体液,呕吐物,皮屑,皮肤,胆汁,耳道分泌物,胸腔液,引流液,眼部分泌物,分泌物
0,99000785,2020-03-20,36.0,男,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,99000785,2020-03-25,36.0,男,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,99000785,2020-03-18,36.0,男,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,91101790,2020-04-30,45.0,男,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,91148248,2020-05-08,25.0,女,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [22]:
guanjianjiance_final_df.to_excel("/data/home/yansn/naojiye/data/是否做过关键检测.xlsx")

In [42]:
guanjianjiance_final_df = pd.read_excel("/data/home/yansn/naojiye/data/是否做过关键检测.xlsx")

In [43]:
selected_ruzu_df = ruzu_df[['patientId','入组时间','分组','组名']]
guanjianjiance_final_df['报告时间'] = guanjianjiance_final_df['报告时间'].astype(str)
guanjianjiance_final_df['patientId'] = guanjianjiance_final_df['patientId'].astype(str)
result_df = pd.merge(guanjianjiance_final_df, selected_ruzu_df, on='patientId')
result_df

,patientId,报告时间,age,gender,血,脑脊液,粪便,尿,鼻/咽拭子,骨髓,动脉血,nan,痰,胃液,肛拭子,脓肿液,穿刺液,支刷,导管,支气管肺泡灌洗液,体液,呕吐物,皮屑,皮肤,胆汁,耳道分泌物,胸腔液,引流液,眼部分泌物,分泌物,入组时间,分组,组名
0,99000785,2020-03-20,36.0,男,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-03-17,4,真菌性脑膜炎
1,99000785,2020-03-25,36.0,男,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-03-17,4,真菌性脑膜炎
2,99000785,2020-03-18,36.0,男,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-03-17,4,真菌性脑膜炎
3,91101790,2020-04-30,45.0,男,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-04-30,4,真菌性脑膜炎
4,91148248,2020-05-08,25.0,女,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2020-05-07,4,真菌性脑膜炎
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6705,96006636,2025-06-15,57.0,男,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-05-26,5,肿瘤性脑膜炎
6706,96083016,2025-06-04,75.0,女,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-05-30,5,肿瘤性脑膜炎
6707,96083865,2025-06-11,54.0,男,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-06-11,5,肿瘤性脑膜炎
6708,96083865,2025-07-05,54.0,男,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-06-11,5,肿瘤性脑膜炎
6709,96083865,2025-07-04,54.0,男,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-06-11,5,肿瘤性脑膜炎

In [46]:
sorted_result_df = result_df.sort_values(by='报告时间')
sorted_result_df = sorted_result_df.groupby('patientId')
sorted_result_df = sorted_result_df.apply(lambda x: x).reset_index(drop=True)
sorted_result_df = sorted_result_df.reindex(columns=['patientId', '报告时间', '入组时间', 'age', 'gender', '分组', '组名']+ outer_features)
# sorted_result_df = sorted_result_df.rename(columns={'resultDateTime': '报告时间'})
sorted_result_df

/tmp/ipykernel_319957/2927048618.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sorted_result_df = sorted_result_df.apply(lambda x: x).reset_index(drop=True)

,patientId,报告时间,入组时间,age,gender,分组,组名,血,脑脊液,粪便,尿,鼻/咽拭子,骨髓,动脉血,nan,痰,胃液,肛拭子,脓肿液,穿刺液,支刷,导管,支气管肺泡灌洗液,体液,呕吐物,皮屑,皮肤,胆汁,耳道分泌物,胸腔液,引流液,眼部分泌物,分泌物
0,86600553,2022-07-08,2022-07-08,32.0,男,8,病毒性脑炎,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,86600553,2022-07-09,2022-07-08,32.0,男,8,病毒性脑炎,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,86600553,2022-07-10,2022-07-08,32.0,男,8,病毒性脑炎,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,86600553,2022-07-11,2022-07-08,32.0,男,8,病毒性脑炎,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,86600553,2022-07-12,2022-07-08,32.0,男,8,病毒性脑炎,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6705,99174645,2025-03-12,2025-03-11,31.0,女,8,病毒性脑炎,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6706,99174645,2025-03-13,2025-03-11,31.0,女,8,病毒性脑炎,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6707,99174645,2025-03-14,2025-03-11,31.0,女,8,病毒性脑炎,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6708,99174645,2025-03-17,2025-03-11,31.0,女,8,病毒性脑炎,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6709,99174645,2025-03-18,2025-03-11,31.0,女,8,病毒性脑炎,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# 加入所有需要的数据
sorted_result_df.to_excel("/data/home/yansn/naojiye/data/是否做过关键检测.xlsx")

In [24]:
# 增加每位患者每日检查项目数和检查项目
import math
final_df = pd.read_csv("/data/home/yansn/naojiye/data/wide_data.csv")
check_project = final_df.columns[4:]

def exam_project(row):
    all_exam = []
    for i in check_project:
        if not(isinstance(row[i],float) and np.isnan(row[i])):
            all_exam.append(i)
    return all_exam

final_df['检查项目'] = final_df.apply(exam_project,axis=1)

def exam_project_numbe(row):
    return len(row['检查项目'])

final_df['检查项目数量'] = final_df.apply(lambda x:len(x['检查项目']),axis=1)

final_df.head()
    
# final_df

/tmp/ipykernel_319957/2104873310.py:3: DtypeWarning: Columns (21,22,33,49,60,62,120,150,193,202,207,209,211,212,214,215,216,217,218,219,220,221,222,223,229,232,235,241,242,243,244,254,255,256,261,274,283,294,329,330,338,339,340,341,359,365,397,410,411,417,428,429,430,431,432,433,434,435,436,439,440,441,445,446,448,449,450,451,466,468,469,471,472,484,485,486,487,488,489,490,491,492,494,495,496,497,498,499,500,501,502,510,511,521,531,532,533,541,543,547,548,549,550,558,559,561,564,565,568,569,570,571,576,577,579,584,585,586,587,588,590,591,592,593,595,596,597,598,599,600,607,608,609,613,622,624,625,626,627,628,630,636,637,648,649,650,651,664,665,667,668,669,671,672,673,674,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,698,699,700,702,703,704,707,708,719,720,721,725,726,727,728,730,737,738,747,748,749,750,751,752,753,754,755,758,759,760,762,763,771,772,773,774,775,776,777,778,779,781,783,784,785,786,787,788,789,790,791,792,795,796,799,806,808,812,815,816,818,819,820,821,822,824,825,826,827,836,837,838,839,840,841,842,843,844,845,846,847,853,854,855,858,859,860,861,862,863,864,867,869,874,876,877,878,879,880,881,882,884,888,890,896,901,904,906,907,913,914,915,916,919,920,921,925,926,927,928,929,930,931,932,933,934,937,938,939,940,941,944,945,946,947,948,953,954,955,956,957,959,960,961,962,963,964,965,966,970,971,972,973,974,975,976,977,978,979,980,981,985,988,989,990,991,992,994,996,997,998,1001,1002,1006,1007,1008,1009,1010,1011,1013,1014,1020,1021,1022,1023,1025,1026,1028,1029,1030,1031,1032,1033,1035,1036,1037,1038,1039,1040,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1063,1064,1067,1068,1071,1072,1073,1074,1076,1077,1079,1081,1082,1083,1084,1085,1086,1087,1088,1089,1104,1105,1106,1107,1112,1113,1114,1115,1116,1117,1119,1120,1121,1122,1123,1124,1125,1126,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1142,1143,1144,1145,1156,1157,1160,1161,1162,1163,1164,1166,1167,1169,1170,1171,1172,1191,1192,1193,1194,1195,1196,1197) have mixed types. Specify dtype option on import or set low_memory=False.
  final_df = pd.read_csv("/data/home/yansn/naojiye/data/wide_data.csv")

,patientId,resultDateTime,age,gender,"血_1,3-β-D-葡聚糖_定量",血_抗桥粒芯糖蛋白1抗体_定量,血_抗桥粒芯糖蛋白3抗体_定量,脑脊液_细菌培养_描述性,脑脊液_涂片查细菌_描述性,脑脊液_真菌培养_描述性,血_隐球菌荚膜抗原_定量,血_隐球菌荚膜抗原_定性,脑脊液_隐球菌荚膜抗原_定量,脑脊液_隐球菌荚膜抗原_定性,血_半乳甘露聚糖_定量,血_细胞.CD3-CD19+百分比_定量,血_细胞.CD3+百分比_定量,血_细胞.CD3+CD4+百分比_定量,血_细胞.CD4+/CD8+_定量,血_细胞.CD3+CD8+百分比_定量,血_细胞.CD3-CD16+CD56+百分比_定量,脑脊液_抗酸杆菌_描述性,脑脊液_分枝杆菌培养_定性,血_肌酸激酶.MB型[质量法]_定量,血_B型钠尿肽前体_定量,血_肌钙蛋白T_定量,血_肌红蛋白_定量,粪便_白细胞计数_定量,粪便_红细胞计数_定量,粪便_粪便性状_描述性,粪便_粪血液_定性,粪便_颜色_描述性,粪便_隐血_定性,粪便_粘液丝_定性,脑脊液_蛋白定量_定量,脑脊液_氯_定量,脑脊液_葡萄糖_定量,血_促甲状腺激素_定量,血_促甲状腺激素受体抗体_定量,血_甲状腺过氧化物酶抗体_定量,血_抗甲状腺球蛋白抗体_定量,血_甲状腺素_定量,血_三碘甲状腺原氨酸_定量,血_游离T4_定量,血_游离T3_定量,血_降钙素原_定量,血_铁蛋白_定量,尿_PH值_定量,尿_白细胞计数_定量,尿_白细胞酯酶_描述性,尿_病理管型_定性,尿_胆红素_定性,尿_蛋白定性_定性,尿_红细胞计数_定量,尿_酵母菌_定性,尿_结晶_定性,尿_比重_定量,尿_尿胆原_定性,尿_葡萄糖_定性,尿_隐血_定性,尿_上皮细胞_定性,尿_酮体_定性,尿_透明管型_定性,尿_细菌计数_定性,尿_小圆细胞_定性,尿_亚硝酸盐_定性,尿_颜色_描述性,尿_透明度_描述性,血_D-二聚体_定量,血_活化部分凝血活酶时间_定量,血_凝血酶原时间国际标准化比值_定量,血_凝血酶时间_定量,血_凝血酶原时间_定量,血_纤维蛋白原_定量,血_纤维蛋白降解产物_定量,血_肾小球滤过率_定量,血_γ谷氨酰转肽酶_定量,血_白蛋白_定量,血_白蛋白/球蛋白_定量,血_丙氨酸氨基转移酶_定量,血_总胆固醇_定量,血_低密度脂蛋白胆固醇_定量,血_二氧化碳结合力_定量,血_非高密度脂蛋白胆固醇_定量,血_甘油三酯_定量,血_高密度脂蛋白胆固醇_定量,血_肌酐_定量,血_钾_定量,血_碱性磷酸酶_定量,血_氯_定量,血_钠_定量,血_尿素_定量,血_尿酸_定量,血_前白蛋白_定量,血_球蛋白_定量,血_门冬氨酸氨基转移酶_定量,血_磷_定量,血_钙_定量,血_镁_定量,血_脂蛋白a_定量,血_直接胆红素_定量,血_总胆红素_定量,血_总胆汁酸_定量,血_总蛋白_定量,血_葡萄糖[空腹]_定量,血_腺苷脱氨酶_定量,血_小而密脂蛋白胆固醇_定量,脑脊液_红细胞计数_定量,脑脊液_淋巴细胞百分比_定量,脑脊液_巨噬细胞百分比_定量,脑脊液_激活巨噬细胞_定性,脑脊液_激活淋巴细胞_定性,脑脊液_寄生虫镜检_描述性,脑脊液_浆细胞_定性,脑脊液_嗜酸性粒细胞百分比_定性,脑脊液_外观_描述性,脑脊液_异常细胞百分比_定性,脑脊液_有核细胞计数_定量,脑脊液_幼稚淋巴细胞_定性,脑脊液_真菌涂片检查_描述性,脑脊液_中性粒细胞百分比_描述性,脑脊液_肿瘤细胞_描述性,血_C反应蛋白_定量,血_白细胞计数_定量,血_大血小板细胞比率_定量,血_单核细胞百分比_定量,血_单核细胞计数_定量,血_红细胞分布宽度_定量,血_红细胞计数_定量,血_红细胞比容_定量,血_淋巴细胞百分比_定量,血_淋巴细胞计数_定量,血_平均红细胞体积_定量,血_平均红细胞血红蛋白含量_定量,血_平均红细胞血红蛋白浓度_定量,血_平均血小板体积_定量,血_嗜碱性粒细胞百分比_定量,血_嗜碱性粒细胞计数_定量,血_嗜酸性粒细胞百分比_定量,血_嗜酸性粒细胞计数_定量,血_总血红蛋白浓度_定量,血_血小板分布宽度_定量,血_血小板计数_定量,血_中性粒细胞百分比_定量,血_中性粒细胞计数_定量,血_红细胞沉降率_定量,血_免疫球蛋白A_定量,血_免疫球蛋白E_定量,血_免疫球蛋白G_定量,血_免疫球蛋白M_定量,脑脊液_墨汁染色_描述性,血_胱抑素C_定量,脑脊液_蛋白定性_定性,脑脊液_透明度_描述性,脑脊液_颜色_描述性,"脑脊液_1,3-β-D-葡聚糖_定量",血_抗双链DNA抗体_定量,血_抗JO-1抗体_定量,血_抗U1-nRNP抗体/SM抗体_定量,血_抗PM-SCL抗体_定量,血_抗RO-52蛋白抗体_定量,血_抗SCL-70抗体_定量,血_抗SM抗体_定量,血_抗核糖体抗体_定量,血_抗核小体抗体_定量,血_抗PCNA抗体_定量,血_载脂蛋白A1_定量,血_载脂蛋白B_定量,脑脊液_单个核细胞百分比_定量,脑脊液_多个核细胞百分比_定量,血_血小板/淋巴细胞比值_定量,血_中性粒细胞/淋巴细胞比值_定量,血_雌二醇_定量,血_睾酮_定量,血_促黄体生成素_定量,血_孕酮_定量,血_促卵泡激素_定量,血_催乳素_定量,血_皮质醇_定量,血_绒毛膜促性腺激素_定量,血_脱氢表雄酮_定量,血_性激素结合球蛋白_定量,血_游离雄激素指数_定量,血_免疫球蛋白G4亚型_定量,血_同型半胱氨酸_定量,血_游离脂肪酸_定量,血_抗凝血酶III_定量,血_β2微球蛋白_定量,血_超敏C反应蛋白_定量,血_铜蓝蛋白_定量,血_转铁蛋白_定量,脑脊液_半乳甘露聚糖_定量,粪便_虫卵_描述性,粪便_寄生虫镜检_描述性,粪便_原虫_描述性,粪便_转铁蛋白_定性,脑脊液_白蛋白_定量,脑脊液_IgG合成指数_定量,脑脊液_免疫球蛋白G_定量,脑脊液_脑脊液IgG_定量,脑脊液_鞘内IgG合成率[24h]_定量,血_M蛋白_描述性,尿_本-周蛋白_描述性,血_抗双链DNA抗体_定性,血_抗核抗体_定性,血_抗胞浆型中性粒细胞抗体_定性,血_抗环瓜氨酸肽抗体_定量,血_抗JO-1抗体_定性,血_髓过氧化物酶_定量,血_抗U1-nRNP抗体/SM抗体_定性,血_抗核周型中性粒细胞抗体_定性,血_抗PCNA抗体_定性,血_抗PM-SCL抗体_定性,血_蛋白酶3_定量,血_抗RO-52蛋白抗体_定性,血_抗SCL-70抗体_定性,血_抗SM抗体_定性,血_抗SS-A抗体_定性,血_抗SS-B抗体_定性,血_抗核糖体抗体_定性,血_抗核小体抗体_定性,血_抗线粒体M2抗体_定性,血_抗着丝点B抗体_定性,血_抗组蛋白抗体_定性,血_α羟丁酸脱氢酶_定量,血_肌酸激酶_定量,血_乳酸脱氢酶_定量,尿_白细胞酯酶_定性,尿_管型_定量,尿_红细胞形态镜检_描述性,尿_上皮细胞_定量,尿_细菌计数_定量,血_Q热立克次体抗体.IgM_定性,血_肺炎衣原体抗体.IgM_定性,血_肺炎支原体抗体.IgM_定性,血_副流感病毒抗体.IgM_定性,血_呼吸道合胞病毒抗体.IgM_定性,血_甲型流感病毒抗体.IgM_定性,血_抗嗜肺军团菌抗体.IgM_定性,血_腺病毒抗体.IgM_定性,血_乙型流感病毒抗体.IgM_定性,血_梅毒非特异性抗体_定性,血_梅毒螺旋体抗体_定性,血_人类免疫缺陷病毒抗体_定性,血_细菌培养_描述性,血_乳酸_定量,血_酮体_定性,血_N端-B型钠尿肽前体_定量,血_糖化血红蛋白_定量,尿_隐血_描述性,血_淀粉酶_定量,血_抗心磷脂抗体.IgA_定量,血_抗心磷脂抗体.IgG_定量,血_抗心磷脂抗体.IgM_定量,血_EB病毒衣壳抗体.IgA_定性,血_EB病毒衣壳抗体.IgG_定性,血_EB病毒衣壳抗体.IgM_定性,血_丙型肝炎病毒抗体_定性,血_乙型肝炎病毒E抗体_定性,血_乙型肝炎病毒E抗原_定性,血_乙型肝炎病毒表面抗体_定量,血_乙型肝炎病毒表面抗原_定性,血_乙型肝炎病毒核心抗体.IgM_定性,血_乙型肝炎病毒核心抗体_定性,血_癌胚抗原_定量,血_甲胎蛋白_定量,血_鳞状上皮细胞癌抗原_定量,血_神经元特异性烯醇化酶_定量,血_糖类抗原125_定量,血_糖类抗原15-3_定量,血_糖类抗原19-9_定量,血_糖类抗原72-4_定量,血_细胞角蛋白19片段_定量,血_巨细胞病毒抗体.IgG_定量,血_巨细胞病毒抗体.IgM_定性,血_KAP/LAM_定量,血_轻链.κ型_定量,血_轻链.λ型_定量,血_补体C3_定量,血_补体C4_定量,血_抗链球菌溶血素O抗体_定量,血_类风湿因子_定量,血_ABO血型鉴定_描述性,血_Rh血型_定性,血_不规则抗体_定性,血_直接抗人球蛋白试验_定性,血_类风湿因子.IgA_定量,血_类风湿因子.IgG_定量,血_类风湿因子.IgM_定量,脑脊液_中性粒细胞百分比_定量,血_α1球蛋白_定量,血_α2球蛋白_定量,血_β球蛋白_定量,血_γ球蛋白_定量,粪便_幽门螺杆菌抗原_定性,尿_红细胞形态镜检_定性,血_抗SS-A抗体_定量,血_抗SS-B抗体_定量,血_抗线粒体M2抗体_定量,血_抗着丝点抗体_定量,血_抗组蛋白抗体_定量,血_抗蛋白酶3抗体.IgG_定量,血_抗髓过氧化物酶抗体_定量,血_CD5_定量,血_中性粒细胞CD64指数_定量,血_细胞.CD3+CD4+CD8+百分比_定量,血_初始性B细胞_定量,血_调节性B细胞_定量,血_调节性T细胞_定量,血_记忆性B细胞_定量,血_原始浆细胞_定量,血_α-L-岩藻糖苷酶_定量,血_甘胆酸_定量,血_亮氨酸氨基肽酶_定量,血_视黄醇结合蛋白_定量,血_载脂蛋白A2_定量,血_载脂蛋白C2_定量,血_载脂蛋白E_定量,尿_蛋白定性_描述性,血_生长激素_定量,血_甲状腺球蛋白_定量,血_罗马指数_定量,血_人附睾蛋白4_定量,血_轻链κ/λ比值_定量,尿_轻链κ/λ比值_定量,尿_轻链.κ型_定量,尿_轻链.λ型_定量,血_抗着丝点B抗体_定量,血_抗心磷脂抗体_定量,脑脊液_结核分枝杆菌DNA_定性,脑脊液_rpoB基因突变分析_定性,血_间接胆红素_定量,血_尿素氮_定量,血_抗核抗体-均质型_定量,鼻/咽拭子_新冠病毒核酸检测_定性,血_唾液酸_定量,血_淀粉样蛋白A_定量,血_细胞.CD45+_定量,血_EB病毒核抗原抗体.IgG_定性,血_EB病毒早期抗原抗体.IgA_定性,血_EB病毒早期抗原抗体.IgG_定性,血_HLA-B27_定性,血_丙型肝炎病毒抗体_定量,血_乙型肝炎病毒E抗体_定量,血_乙型肝炎病毒E抗原_定量,血_乙型肝炎病毒表面抗原_定量,血_乙型肝炎病毒核心抗体.IgM_定量,血_乙型肝炎病毒核心抗体_定量,血_前列腺特异性抗原_定量,血_游离前列腺特异性抗原_定量,血_凝固角Angle_定量,血_凝血综合指数CI值_定量,血_纤溶指标EPL值_定量,血_血栓最大强度G值_定量,血_凝血速率K值_定量,血_纤溶指标LY30值_定量,血_血栓最大幅度MA值_定量,血_凝血因子反应时间R值_定量,血_脂肪酶_定量,血_EB病毒DNA_描述性,血_人类巨细胞病毒DNA_定量,血_β-羟丁酸_定量,血_胆碱酯酶_定量,血_磷脂酶A2_定量,血_白细胞介素-6_定量,骨髓_细菌培养_描述性,动脉血_50%血氧饱和度的氧分压_定量,动脉血_标准碳酸氢盐浓度_定量,动脉血_二氧化碳分压_定量,动脉血_血浆二氧化碳总浓度_定量,动脉血_全血二氧化碳总浓度_定量,动脉血_肺泡氧分压_定量,动脉血_离子钙_定量,动脉血_高铁血红蛋白_定量,动脉血_呼吸指数_定量,动脉血_去氧血红蛋白_定量,动脉血_钾_定量,动脉血_氯_定量,动脉血_钠_定量,动脉血_葡萄糖_定量,动脉血_氢离子浓度_定量,动脉血_乳酸_定量,动脉血_渗透压_定量,动脉血_实际碱剩余_定量,动脉血_总血红蛋白浓度_定量,动脉血_实际碳酸氢盐浓度_定量,动脉血_PH值_定量,动脉血_碳氧血红蛋白_定量,动脉血_标准碱剩余_定量,动脉血_红细胞比容_定量,动脉血_有效氧饱和度_定量,动脉血_氧分压_定量,动脉血_氧总含量_定量,动脉血_氧合血红蛋白_定量,动脉血_阴离子隙_定量,脑脊液_脑脊液IgA_定量,脑脊液_脑脊液IgM_定量,尿_葡萄糖_描述性,血_白细胞介素-10_定量,血_白细胞介素-12p70_定量,血_白细胞介素-17_定量,血_白细胞介素-2_定量,血_白细胞介素-4_定量,血_干扰素-γ_定量,血_α肿瘤坏死因子_定量,尿_蛋白/肌酐_定量,尿_肌酐_定量,尿_蛋白定量_定量,尿_白蛋白_定量,尿_微量白蛋白/肌酐_定量,尿_草酸钙结晶_定性,尿_异型红细胞_描述性,血_白细胞介素-2受体_定量,尿_β2微球蛋白_定量,尿_α1微球蛋白_定量,尿_免疫球蛋白G_定量,尿_转铁蛋白_定量,血_真菌培养_描述性,血_网织红细胞百分比_定量,血_低荧光强度网织红细胞_定量,血_高荧光强度网织红细胞_定量,血_网织红细胞计数_定量,血_中荧光强度网织红细胞_定量,血_幼稚网织红细胞百分比_定量,脑脊液_癌胚抗原_定量,脑脊液_甲胎蛋白_定量,脑脊液_神经元特异性烯醇化酶_定量,粪便_轮状病毒_定性,粪便_腺病毒抗原_定性,尿_白色念珠菌_描述性,尿_涂片查细菌_描述性,尿_酵母菌_描述性,尿_真菌培养_描述性,血_新冠病毒抗体.IgG_定性,血_新冠病毒抗体.IgM_定性,鼻/咽拭子_真菌培养_描述性,粪便_真菌培养_描述性,血_肝素结合蛋白_定量,血_B型柯萨奇病毒抗体.IgM_定性,尿_胆红素_描述性,尿_上皮细胞_描述性,尿_酮体_描述性,脑脊液_激活淋巴细胞_定量,脑脊液_幼稚淋巴细胞_定量,脑脊液_中性粒细胞百分比_定性,脑脊液_真菌涂片检查_定性,脑脊液_厌氧菌培养_描述性,脑脊液_乳酸_定量,血_抗中性粒细胞胞质抗体_定性,尿_细菌培养_描述性,尿_奇异变形杆菌_描述性,尿_革兰阴性杆菌_描述性,血_免疫球蛋白G1亚型_定量,血_免疫球蛋白G2亚型_定量,血_免疫球蛋白G3亚型_定量,血_抗磷脂酶A2受体抗体_定量,血_抗肾小球基底膜抗体_定量,血_细胞.CD3-CD19+计数_定量,血_细胞.CD3-CD16+CD56+计数_定量,血_细胞.CD3+CD8+计数_定量,血_细胞.CD3+CD4+计数_定量,血_细胞.CD3+计数_定量,血_结核感染T细胞检测_定性,血_结核感染T细胞测试管_定量,血_结核感染T细胞阳性对照_定量,血_结核感染T细胞阴性对照_定量,血_乙型肝炎病毒DNA_描述性,血_游离/总前列腺特异性抗原_定量,血_人类巨细胞病毒DNA_描述性,血_肺炎链球菌_描述性,脑脊液_浆细胞_定量,血_抗平滑肌抗体_定性,尿_小圆细胞_描述性,尿_钙[24h尿]_定量,尿_钾[24h尿]_定量,尿_24小时尿量_定量,尿_磷[24h尿]_定量,尿_氯[24h尿]_定量,尿_钠[24h尿]_定量,尿_尿酸[24h尿]_定量,尿_葡萄糖[24h尿]_定量,尿_蛋白[24h尿]_定量,血_血管紧张素转换酶_定量,血_血氨_定量,脑脊液_有核细胞计数_定性,脑脊液_涂片革兰氏染色_描述性,脑脊液_革兰阳性球菌_描述性,脑脊液_肺炎链球菌_描述性,尿_细菌计数_描述性,nan_细菌培养_描述性,痰_抗酸杆菌_描述性,痰_结核分枝杆菌DNA_定性,尿_分枝杆菌培养_定性,脑脊液_乳酸脱氢酶_定量,血_抗核抗体_描述性,血_抗核抗体-胞浆颗粒型_定性,痰_细菌培养_描述性,痰_类酵母菌_描述性,痰_分枝杆菌培养_定性,胃液_隐血_定性,脑脊液_梅毒非特异性抗体_定性,脑脊液_梅毒螺旋体抗体_定性,脑脊液_类酵母菌_描述性,脑脊液_激活巨噬细胞_定量,尿_渗透压_定量,血_抗EJ抗体_定量,血_抗Ku抗体_定量,血_抗Mi-2抗体_定量,血_抗PL-12抗体_定量,血_抗PL-7抗体_定量,痰_细菌培养_定性,脑脊液_隐球菌_描述性,血_C肽_定量,血_胰岛素_定量,脑脊液_红细胞计数_描述性,血_抗肝肾微粒体抗体_定量,血_抗肝细胞溶质抗原I型抗体_定量,血_抗核膜糖蛋白210抗体_定量,血_抗可溶性肝抗原/肝胰抗原抗体_定量,血_抗可溶性酸性核蛋白抗体_定量,血_抗早幼粒细胞白血病蛋白抗体_定量,血_人类免疫缺陷病毒P24抗原_定性,血_糖类抗原242_定量,血_糖类抗原50_定量,血_过敏原特异性IgE检测-霉菌组合(点青/分枝孢/烟曲/交链孢霉)_定量,血_过敏原特异性IgE检测-烟曲霉_定量,血_IgE总计_定量,血_胃泌素释放肽前体_定量,血_维生素B12_定量,血_维生素B9_定量,血_甲状旁腺素_定量,nan_真菌培养_描述性,尿_尿胆原_描述性,脑脊液_幼稚淋巴细胞_描述性,血_心型脂肪酸结合蛋白_定量,血_转铁蛋白饱和度_定量,血_不饱和铁结合力_定量,血_铁_定量,血_总铁结合力_定量,血_促红细胞生成素_定量,尿_淀粉酶_定量,血_抗核抗体-颗粒型_定性,血_异常凝血酶原_定量,脑脊液_头状葡萄球菌_描述性,尿_视黄醇结合蛋白_定量,尿_中性粒细胞明胶酶相关脂质运载蛋白_定量,血_葡萄糖[120分钟]_定量,脑脊液_巨噬细胞百分比_定性,痰_真菌培养_描述性,痰_肺炎克雷伯菌_描述性,痰_革兰阴性杆菌_描述性,血_中性粒细胞明胶酶相关脂质运载蛋白_定量,血_硫酸脱氢表雄酮_定量,血_胃蛋白酶原Ⅰ_定量,血_胃蛋白酶Ⅰ/胃蛋白酶Ⅱ_定量,血_胃蛋白酶原Ⅱ_定量,血_胃泌素-17_定量,血_中枢神经特异蛋白_定量,痰_真菌涂片检查_定性,血_丙型肝炎病毒RNA_描述性,脑脊液_嗜酸性粒细胞百分比_定量,痰_金黄色葡萄球菌_描述性,尿_肌酐[24h尿]_定量,血_促肾上腺皮质激素_定量,血_革兰阳性球菌_描述性,血_溶血葡萄球菌_描述性,血_胰岛素样生长因子-Ⅰ_定量,血_EB病毒DNA_定量,脑脊液_淋巴细胞百分比_描述性,脑脊液_巨噬细胞百分比_描述性,尿_肺炎克雷伯菌_描述性,尿_琼氏不动杆菌_描述性,血_乙型肝炎病毒DNA_定量,血_甲胎蛋白异质体_定量,尿_尿素[24h尿]_定量,血_渗透压_定量,痰_白色念珠菌_描述性,血_抗核抗体-核膜型_定性,血_抗核抗体-核仁型_定量,尿_大肠埃希菌_描述性,血_红细胞聚集指数_定量,血_全血低切相对指数_定量,血_全血高切相对指数_定量,血_血浆粘度_定量,血_甲型肝炎病毒抗体.IgM_定性,脑脊液_淋巴细胞百分比_定性,脑脊液_异常细胞百分比_描述性,血_群体反应性抗体_定性,脑脊液_人葡萄球菌_描述性,血_风疹病毒抗体.IgG_定量,血_风疹病毒抗体.IgM_定性,尿_鲍曼不动杆菌_描述性,肛拭子_细菌培养_描述性,肛拭子_肺炎克雷伯菌_描述性,血_降钙素_定量,脑脊液_外观_定性,脑脊液_红细胞计数_定性,血_单纯疱疹病毒Ⅰ型抗体.IgG_定性,血_单纯疱疹病毒Ⅰ型抗体.IgM_定性,血_单纯疱疹病毒Ⅱ型抗体.IgG_定性,血_单纯疱疹病毒Ⅱ型抗体.IgM_定性,血_维生素A_定量,血_25-羟维生素D_定量,血_25-羟基维生素D2_定量,血_25-羟基维生素D3_定量,血_维生素E_定量,血_维生素K_定量,痰_鲍曼不动杆菌_描述性,痰_流感嗜血杆菌_描述性,痰_嗜麦芽窄食单胞菌_描述性,血_地高辛血药浓度_定量,血_β-胶原降解产物测定_定量,血_骨钙素_定量,尿_热带假丝酵母菌_描述性,血_维生素B1_定量,血_维生素B2_定量,血_维生素B3_定量,血_维生素B5_定量,血_维生素B6_定量,血_维生素B7_定量,血_5甲基四氢叶酸_定量,血_维生素C_定量,痰_革兰阳性球菌_描述性,血_IgG合成指数_定量,痰_铜绿假单胞菌_描述性,脑脊液_单纯疱疹病毒Ⅰ型抗体.IgG_定性,脑脊液_单纯疱疹病毒Ⅰ型抗体.IgM_定性,脑脊液_单纯疱疹病毒Ⅱ型抗体.IgG_定性,脑脊液_单纯疱疹病毒Ⅱ型抗体.IgM_定性,尿_皮质醇[24h尿]_定量,粪便_艰难梭菌抗原_定性,尿_钠_定量,血_血管紧张素Ⅱ_定量,血_醛固酮/肾素_定量,血_肾素_定量,血_醛固酮_定量,尿_屎肠球菌_描述性,脓肿液_细菌培养_描述性,血_抗中性粒细胞胞质抗体_定量,脑脊液_肝素结合蛋白_定量,脑脊液_降钙素原_定量,血_白细胞介素-1β_定量,血_白细胞介素-5_定量,血_白细胞介素-8_定量,血_干扰素-α_定量,血_幼稚粒细胞百分比_定量,血_有核红细胞百分比_定量,血_抗弓形虫抗体.IgG_定量,血_抗弓形虫抗体.IgM_定性,血_戊型肝炎病毒抗体.IgG_定性,血_戊型肝炎病毒抗体.IgM_定性,脑脊液_革兰阴性杆菌_描述性,脑脊液_白细胞介素-10_定量,脑脊液_白细胞介素-12p70_定量,脑脊液_白细胞介素-17_定量,脑脊液_白细胞介素-1β_定量,脑脊液_白细胞介素-2_定量,脑脊液_白细胞介素-4_定量,脑脊液_白细胞介素-5_定量,脑脊液_白细胞介素-6_定量,脑脊液_白细胞介素-8_定量,脑脊液_干扰素-α_定量,脑脊液_干扰素-γ_定量,脑脊液_α肿瘤坏死因子_定量,血_抗核抗体-线粒体型_定性,血_抗核抗体-核仁型_定性,血_晚幼红细胞_定量,血_疟原虫_描述性,尿_光滑假丝酵母菌_描述性,脑脊液_表皮葡萄球菌_描述性,血_乙型肝炎病毒前S1抗原_定量,鼻/咽拭子_呼吸道合胞病毒RNA_定性,鼻/咽拭子_甲型流感病毒RNA_定性,鼻/咽拭子_乙型流感病毒RNA_定性,血_抗核抗体-均质型_定性,血_β1球蛋白_定量,血_β2球蛋白_定量,穿刺液_细菌培养_描述性,脓肿液_涂片查细菌_描述性,脓肿液_表皮葡萄球菌_描述性,脑脊液_EB病毒DNA_描述性,痰_鲍曼不动杆菌_定性,痰_大肠埃希菌_定性,痰_肺炎克雷伯菌_定性,痰_肺炎链球菌_定性,痰_金黄色葡萄球菌_定性,痰_流感嗜血杆菌_定性,痰_嗜麦芽窄食单胞菌_定性,痰_铜绿假单胞菌_定性,脑脊液_EB病毒衣壳抗体.IgA_定性,脑脊液_EB病毒衣壳抗体.IgG_定性,脑脊液_EB病毒衣壳抗体.IgM_定性,脑脊液_EB病毒核抗原抗体.IgG_定性,脑脊液_EB病毒早期抗原抗体.IgA_定性,脑脊液_EB病毒早期抗原抗体.IgG_定性,血_丙戊酸_定量,脑脊液_C反应蛋白_定量,脑脊液_β2微球蛋白_定量,脑脊液_嗜酸性粒细胞百分比_描述性,鼻/咽拭子_细菌培养_描述性,痰_热带假丝酵母菌_描述性,血_结核感染T细胞测试管-阴性对照管_定量,支刷_白色念珠菌_描述性,支刷_细菌培养_描述性,支刷_肺炎克雷伯菌_描述性,血_低色素红细胞_定量,血_网织红细胞血红蛋白含量_定量,鼻/咽拭子_新冠病毒核酸检测_定量,血_A型柯萨奇病毒抗体.IgM_定性,血_黄疸指数_定量,血_肌酸激酶.MB型_定量,血_溶血指数_定量,血_脂浊指数_定量,血_红细胞分布宽度标准差_定量,血_成熟单核细胞_定量,血_成熟淋巴细胞_定量,血_EB病毒核抗原抗体.IgG_定量,血_EB病毒衣壳抗体.IgG_定量,血_EB病毒早期抗原抗体.IgG_定量,血_单纯疱疹病毒抗体.IgG_定性,血_单纯疱疹病毒抗体.IgM_定性,血_风疹病毒抗体.IgG_定性,脑脊液_EB病毒核抗原抗体.IgG_定量,脑脊液_EB病毒衣壳抗体.IgG_定量,脑脊液_EB病毒早期抗原抗体.IgG_定量,脑脊液_单纯疱疹病毒抗体.IgG_定性,脑脊液_单纯疱疹病毒抗体.IgM_定性,脑脊液_抗弓形虫抗体.IgG_定性,脑脊液_抗弓形虫抗体.IgM_定性,脑脊液_巨细胞病毒抗体.IgG_定量,脑脊液_巨细胞病毒抗体.IgM_定性,血_Ⅲ型前胶原N端肽_定量,血_Ⅳ型胶原_定量,血_层粘连蛋白_定量,血_透明质酸_定量,血_补体C1q_定量,血_谷氨酸脱氢酶_定量,nan_真菌孢子_描述性,血_血培养_描述性,血_抗缪勒管激素_定量,血_α1抗胰蛋白酶_定量,血_α1酸性糖蛋白_定量,血_结合珠蛋白_定量,血_高敏促甲状腺激素_定量,血_淋巴细胞CD64指数_定量,血_单核细胞CD64指数_定量,血_反三碘甲状腺原氨酸_定量,尿_轻链.κ型_描述性,尿_轻链.λ型_描述性,尿_类酵母菌_定性,尿_电导率_定性,血_抗Mi-2抗体_定性,血_抗RNP抗体_定性,血_抗smD1抗体_定性,血_抗RO-60蛋白抗体_定性,血_抗Ku抗体_定性,血_抗β2-糖蛋白1抗体_定量,血_抗蛋白酶3抗体_定量,血_抗EJ抗体_定性,血_抗PL-12抗体_定性,血_抗PL-7抗体_定性,血_葡萄糖[随机]_定量,尿_真菌孢子_描述性,粪便_白色念珠菌_描述性,尿_光滑假丝酵母菌_定量,脑脊液_糖类抗原125_定量,脑脊液_糖类抗原15-3_定量,脑脊液_糖类抗原19-9_定量,脑脊液_糖类抗原72-4_定量,脑脊液_细胞角蛋白19片段_定量,脑脊液_巨细胞病毒抗体.IgM_定量,鼻/咽拭子_新冠病毒抗原检测_定性,导管_细菌培养_描述性,血_IgG-LAM型M蛋白_描述性,血_血清指数_描述性,鼻/咽拭子_人鼻病毒RNA_定性,鼻/咽拭子_肺炎支原体DNA_定性,鼻/咽拭子_副流感病毒RNA_定性,鼻/咽拭子_腺病毒DNA_定性,鼻/咽拭子_衣原体_定性,血_抗Xa因子活性_定量,脑脊液_细胞学检查_定性,血_谷胱甘肽还原酶_定量,脑脊液_革兰阳性杆菌_描述性,血_血培养[需氧菌]_定性,血_厌氧菌培养_定性,尿_尿沉渣定量分析_定性,尿_白细胞计数_描述性,脑脊液_弱抗酸染色涂片_定性,脑脊液_结核菌培养_定性,脑脊液_分枝杆菌培养_描述性,脑脊液_细菌培养_定性,脑脊液_厌氧菌培养_定性,粪便_霉菌_定量,粪便_脓细胞_定量,粪便_夏科-雷登结晶_描述性,尿_细菌培养_定性,血_卡马西平_定量,血_左乙拉西坦_定量,尿_红细胞计数_描述性,血_抗谷氨酸脱羧酶抗体_定量,血_抗胰岛素抗体_定量,血_抗胰岛细胞抗体_定量,血_α2巨球蛋白_定量,脑脊液_糖类抗原50_定量,脑脊液_糖类抗原242_定量,脑脊液_需氧菌培养_定性,脑脊液_异常细胞百分比_定量,血_抗核抗体-核点型_定性,血_雄烯二酮_定量,血_促甲状腺激素受体刺激性抗体_定量,血_17-羟基孕酮_定量,尿_粪肠球菌_描述性,血_甲氧基肾上腺素_定量,血_甲氧基去甲肾上腺素_定量,支气管肺泡灌洗液_涂片查细菌_描述性,支气管肺泡灌洗液_真菌培养_描述性,支气管肺泡灌洗液_红细胞计数_定量,支气管肺泡灌洗液_淋巴细胞百分比_定性,支气管肺泡灌洗液_浆细胞百分比_定性,支气管肺泡灌洗液_嗜酸性粒细胞百分比_定性,支气管肺泡灌洗液_革兰阳性球菌_描述性,支气管肺泡灌洗液_有核细胞计数_定性,支气管肺泡灌洗液_中性粒细胞百分比_定量,尿_克柔假丝酵母菌_描述性,尿_类酵母菌_描述性,脑脊液_涂片查细菌_定性,痰_克柔假丝酵母菌_描述性,脑脊液_EB病毒DNA_定量,血_抗CAGE抗体_定量,血_抗GAGE7抗体_定量,血_抗GBU4-5抗体_定量,血_抗MAGE-A1抗体_定量,血_抗p53抗体_定量,血_抗PGP9.5抗体_定量,血_抗SOX2抗体_定量,体液_真菌培养_描述性,脑脊液_鲍曼不动杆菌_定性,脑脊液_大肠埃希菌_定性,脑脊液_肺炎克雷伯菌_定性,脑脊液_肺炎链球菌_定性,脑脊液_金黄色葡萄球菌_定性,脑脊液_流感嗜血杆菌_定性,脑脊液_嗜麦芽窄食单胞菌_定性,脑脊液_铜绿假单胞菌_定性,支气管肺泡灌洗液_抗酸杆菌_描述性,支刷_鲍曼不动杆菌_描述性,支刷_真菌培养_描述性,血_游离雌三醇_定量,血_游离睾酮_定量,血_丙型肝炎病毒抗体.IgG_定量,血_梅毒螺旋体抗体_定量,血_HIV抗原抗体_定量,呕吐物_隐血_定性,血_梅毒非特异性抗体_描述性,血_APOE基因突变分析_描述性,血_糖化白蛋白_定量,血_β-HCG_定量,血_抗肝肾微粒体Ⅰ型抗体_定性,血_抗肝细胞溶质抗原I型抗体_定性,血_抗核膜糖蛋白210抗体_定性,血_抗可溶性肝抗原/肝胰抗原抗体_定性,血_抗可溶性酸性核蛋白抗体_定性,血_抗线粒体抗体_定性,血_抗早幼粒细胞白血病蛋白抗体_定性,血_蛋白C活性_定量,血_蛋白S活性_定量,粪便_脂肪球_描述性,粪便_钙卫蛋白_定量,尿_抗酸杆菌_描述性,血_总Ⅰ型胶原氨基端延长肽_定量,血_C肽[120分钟]_定量,血_胰岛素[120分钟]_定量,尿_热带假丝酵母菌_定量,尿_绒毛膜促性腺激素_定性,血_万古霉素血药浓度_定量,尿_本-周蛋白_定性,尿_鲍曼不动杆菌_定性,尿_大肠埃希菌_定性,尿_肺炎克雷伯菌_定性,尿_金黄色葡萄球菌_定性,尿_嗜麦芽窄食单胞菌_定性,尿_铜绿假单胞菌_定性,血_氨甲喋呤血药浓度_定量,尿_雷氏普罗威登斯菌_描述性,血_抗β2-糖蛋白1抗体.IgA_定量,血_抗β2-糖蛋白1抗体.IgG_定量,血_抗β2-糖蛋白1抗体.IgM_定量,血_抗核抗体-胞浆纤维型_定性,血_超氧物歧化酶_定量,血_Rh(D)血型鉴定_定性,脑脊液_细胞总数_定量,动脉血_二氧化碳分压[实际体温]_定量,动脉血_肺泡动脉氧分压差_定量,动脉血_二氧化碳总浓度_定量,血_他克莫司血药浓度_定量,痰_痰培养_描述性,血_新冠病毒抗体.IgG_定量,血_新冠病毒抗体.IgM_定量,动脉血_体温_定量,动脉血_吸氧流量_定量,血_HIV抗原抗体_定性,鼻/咽拭子_新冠病毒N基因检测_定量,鼻/咽拭子_新冠病毒ORF1ab基因检测_定量,血_抗弓形虫抗体.IgG_定性,血_酪氨酸磷酸酶抗体_定量,血_抗胰岛素抗体_定性,血_抗胰岛细胞抗体_定性,血_结核感染T细胞阳性对照管-阴性对照管_定量,血_镉_定量,血_铅_定量,血_铜_定量,血_锌_定量,尿_念珠菌属_描述性,血_丙型肝炎病毒RNA_定性,血_人类免疫缺陷病毒RNA_定性,血_乙型肝炎病毒DNA_定性,尿_透明管型_定量,血_全段甲状旁腺素_定量,血_黄疸指数_描述性,血_溶血指数_描述性,血_脂浊指数_描述性,血_肌钙蛋白I_定量,血_有核红细胞计数_定量,血_可溶性生长刺激表达基因蛋白2_定量,血_EB病毒DNA_定性,导管_细菌培养_定性,痰_涂片查细菌_描述性,尿_纹带棒状杆菌_描述性,导管_真菌培养_描述性,导管_表皮葡萄球菌_描述性,鼻/咽拭子_甲型流感病毒抗原_定性,鼻/咽拭子_乙型流感病毒抗原_定性,血_纹带棒状杆菌_描述性,血_丙型肝炎病毒核心抗原_定性,血_甲型肝炎病毒抗体.IgM_定量,支气管肺泡灌洗液_半乳甘露聚糖_定量,痰_结核菌培养_定性,痰_分枝杆菌培养_描述性,支气管肺泡灌洗液_细菌培养_描述性,支气管肺泡灌洗液_结核菌培养_定性,支气管肺泡灌洗液_革兰阴性杆菌_描述性,支气管肺泡灌洗液_淋巴细胞百分比_定量,支气管肺泡灌洗液_有核细胞计数_定量,皮屑_真菌涂片检查_定性,血_抗核抗体-抗着丝点型_定性,尿_近平滑假丝酵母菌_描述性,支气管肺泡灌洗液_结核分枝杆菌DNA_定性,脑脊液_停乳链球菌_描述性,血_转铁蛋白受体_定量,血_抗RNP抗体_定量,血_抗smD1抗体_定量,血_抗RO-60蛋白抗体_定量,痰_念珠菌属_描述性,尿_铜绿假单胞菌_描述性,血_IgG-KAP型M蛋白_描述性,脑脊液_溶血葡萄球菌_描述性,血_革兰阴性杆菌_描述性,血_胰岛素样生长因子结合蛋白3_定量,尿_人葡萄球菌_描述性,皮肤_真菌培养_描述性,尿_抗坏血酸_定性,脑脊液_屎肠球菌_描述性,脑脊液_真菌菌丝_描述性,皮肤_真菌孢子_描述性,脑脊液_嗜碱性粒细胞计数_描述性,脑脊液_肿瘤细胞_定性,血_纤溶酶-抗纤溶酶复合物_定量,血_凝血酶调节蛋白_定量,"支气管肺泡灌洗液_1,3-β-D-葡聚糖_定量",支气管肺泡灌洗液_白色念珠菌_描述性,支气管肺泡灌洗液_鲍曼不动杆菌_定性,支气管肺泡灌洗液_肺炎克雷伯菌_定性,支气管肺泡灌洗液_肺炎链球菌_定性,支气管肺泡灌洗液_金黄色葡萄球菌_定性,支气管肺泡灌洗液_流感嗜血杆菌_定性,支气管肺泡灌洗液_嗜麦芽窄食单胞菌_定性,支气管肺泡灌洗液_铜绿假单胞菌_定性,支气管肺泡灌洗液_肺炎克雷伯菌_描述性,支气管肺泡灌洗液_流感嗜血杆菌_描述性,血_卡马西平_描述性,尿_尿液精子计数_定性,血_葡萄糖[30分钟]_定量,血_葡萄糖[60分钟]_定量,血_葡萄糖[180分钟]_定量,脑脊液_EB病毒DNA_定性,血_狼疮抗凝物初筛试验_定量,血_狼疮抗凝物确认试验_定量,脑脊液_黏质沙雷菌_描述性,痰_白色念珠菌_定性,脑脊液_肺炎克雷伯菌_描述性,尿_结晶_描述性,粪便_外观_描述性,血_M蛋白_定量,尿_表皮葡萄球菌_描述性,脑脊液_α2巨球蛋白_定量,皮屑_真菌培养_描述性,血_结核菌培养_定性,尿_尿酸结晶_定性,血_C肽[空腹]_定量,血_胰岛素[空腹]_定量,穿刺液_真菌培养_描述性,脑脊液_真菌孢子_描述性,动脉血_吸氧浓度_定量,动脉血_氧合指数_定量,血_血小板最大聚集率_定量,nan_涂片查细菌_描述性,胆汁_细菌培养_描述性,胆汁_头状葡萄球菌_描述性,支刷_金黄色葡萄球菌_描述性,粪便_细菌培养_描述性,粪便_光滑假丝酵母菌_描述性,尿_α2巨球蛋白_定量,胆汁_真菌培养_描述性,痰_烟曲霉_描述性,血_丙型肝炎病毒RNA_定量,血_3-甲氧酪胺_定量,血_多巴胺_定量,血_去甲肾上腺素_定量,血_肾上腺素_定量,支气管肺泡灌洗液_隐球菌荚膜抗原_定性,脑脊液_咽峡炎链球菌_描述性,尿_管型_描述性,尿_结核分枝杆菌DNA_定性,血_抗核抗体-胞浆颗粒型_定量,脑脊液_细胞总数_定性,血_Septin9基因甲基化检测_定性,血_抗突变型瓜氨酸化波形蛋白抗体_定量,肛拭子_表皮葡萄球菌_描述性,痰_洋葱伯克霍尔德菌_描述性,尿_卷曲乳杆菌_描述性,耳道分泌物_鸟肠球菌_描述性,耳道分泌物_铜绿假单胞菌_描述性,耳道分泌物_真菌培养_描述性,血_抗核抗体-颗粒型_定量,耳道分泌物_肠球菌属_描述性,肛拭子_粪肠球菌_描述性,血_嗜碱性粒细胞百分比_定性,血_嗜酸性粒细胞百分比_定性,支气管肺泡灌洗液_鲍曼不动杆菌_描述性,粪便_脂肪球_定性,尿_电导率_定量,脑脊液_有核细胞计数_描述性,血_左乙拉西坦_描述性,血_过敏原特异性IgE检测-菠萝_定性,血_过敏原特异性IgE检测-大豆_定性,血_过敏原特异性IgE检测-芒果_定性,血_过敏原特异性IgE检测-牛奶_定性,血_过敏原特异性IgE检测-牛肉_定性,血_过敏原特异性IgE检测-蟹类_定性,血_过敏原特异性IgE检测-虾/对虾_定性,血_食物不耐受IgG检测-小麦_定性,血_食物不耐受IgG检测-鳕鱼_定性,血_过敏原特异性IgE检测-腰果_定性,血_食物不耐受IgG检测-芝麻_定性,支气管肺泡灌洗液_红细胞计数_描述性,脑脊液_科氏葡萄球菌_描述性,痰_曲霉菌属_定性,痰_耶氏肺孢子菌_定性,血_高尔基体蛋白73_定量,胸腔液_葡萄糖_定量,胸腔液_乳酸脱氢酶_定量,胸腔液_蛋白定量_定量,胸腔液_结核分枝杆菌DNA_定性,胸腔液_真菌培养_描述性,胸腔液_红细胞计数_定量,胸腔液_淋巴细胞百分比_定量,胸腔液_浆细胞百分比_定性,胸腔液_外观_描述性,胸腔液_有核细胞计数_定量,胸腔液_中性粒细胞百分比_定量,痰_大肠埃希菌_描述性,胸腔液_涂片查细菌_描述性,胸腔液_细菌培养_描述性,胸腔液_抗酸杆菌_描述性,血_异型淋巴细胞百分比_定量,血_人葡萄球菌_描述性,尿_革兰阳性球菌_描述性,尿_细胞管型_定量,痰_表皮葡萄球菌_描述性,尿_颗粒管型_定量,引流液_细菌培养_描述性,引流液_白色念珠菌_描述性,引流液_鲍曼不动杆菌_描述性,脑脊液_沃氏葡萄球菌_描述性,支刷_肺炎克雷伯菌_定性,支刷_流感嗜血杆菌_描述性,nan_白色念珠菌_描述性,支刷_光滑假丝酵母菌_描述性,痰_光滑假丝酵母菌_描述性,血_戊型肝炎病毒抗体.IgG_定量,血_戊型肝炎病毒抗体.IgM_定量,胸腔液_癌胚抗原_定量,胸腔液_甲胎蛋白_定量,胸腔液_鳞状上皮细胞癌抗原_定量,胸腔液_神经元特异性烯醇化酶_定量,胸腔液_糖类抗原125_定量,胸腔液_糖类抗原15-3_定量,胸腔液_糖类抗原19-9_定量,胸腔液_糖类抗原72-4_定量,胸腔液_胃泌素释放肽前体_定量,胸腔液_细胞角蛋白19片段_定量,胸腔液_单个核细胞百分比_定量,胸腔液_多个核细胞百分比_定量,胸腔液_李凡它试验_定性,胸腔液_透明度_描述性,胸腔液_颜色_描述性,胸腔液_中性粒细胞百分比_定性,血_C肽[60分钟]_定量,血_胰岛素[60分钟]_定量,血_抗肝肾微粒体Ⅰ型抗体_定量,尿_结晶_定量,血_金黄色葡萄球菌_描述性,尿_金黄色葡萄球菌_描述性,脑脊液_金黄色葡萄球菌_描述性,动脉血_标准碱剩余_定性,血_IgA-LAM型M蛋白_描述性,血_IgM-KAP型M蛋白_描述性,尿_淋巴细胞百分比_定量,尿_寄生虫镜检_描述性,尿_浆细胞_定性,尿_真菌涂片检查_描述性,支气管肺泡灌洗液_曲霉菌属_定性,血_EB病毒RTA蛋白抗体.IgG_定性,支气管肺泡灌洗液_有核细胞计数_描述性,血_HLA位点DR_描述性,尿_无乳链球菌[B群]_描述性,血_标准化LAC比值_定量,痰_阴沟肠杆菌复合菌_描述性,尿_溶血葡萄球菌_描述性,耳道分泌物_白色念珠菌_描述性,耳道分泌物_类酵母菌_描述性,耳道分泌物_念珠菌属_描述性,粪便_鲍曼不动杆菌_描述性,眼部分泌物_表皮葡萄球菌_描述性,眼部分泌物_真菌培养_描述性,痰_路邓葡萄球菌_描述性,支气管肺泡灌洗液_真菌孢子_描述性,血_铜绿假单胞菌_描述性,血_肺炎克雷伯菌_描述性,尿_含铁血黄素_定性,胸腔液_浆细胞百分比_定量,支气管肺泡灌洗液_铜绿假单胞菌_描述性,脑脊液_新型隐球菌_定性,粪便_近平滑假丝酵母菌_描述性,支刷_洋葱伯克霍尔德菌_描述性,血_过敏原特异性IgE检测-粉尘螨_定量,血_过敏原特异性IgE检测-狗皮屑_定量,血_过敏原特异性IgE检测-屋尘螨_定量,血_链格孢_定量,血_过敏原特异性IgE检测-猫皮屑_定量,血_过敏原特异性IgE检测-牛奶_定量,血_过敏原特异性IgE检测-虾/对虾_定量,血_过敏原特异性IgE检测-蟹类_定量,血_烟曲霉_定量,血_有核红细胞/100个白细胞_定量,导管_厌氧菌培养_描述性,尿_嗜麦芽窄食单胞菌_描述性,血_凝血酶原活动度_定量,血_中幼红细胞_定量,脑脊液_浆细胞_描述性,肛拭子_鲍曼不动杆菌_描述性,脑脊液_念珠菌属_描述性,脑脊液_白色念珠菌_描述性,分泌物_真菌培养_描述性,血_校正钙_定量,血_大肠埃希菌_描述性,血_肠道病毒EV71抗体.IgM_定性,脑脊液_梅毒螺旋体抗体_定量,脑脊液_纹带棒状杆菌_描述性,导管_纹带棒状杆菌_描述性,痰_纹带棒状杆菌_描述性,nan_表皮葡萄球菌_描述性,血_过敏原特异性IgE检测-热带螨_定量,血_过敏原特异性IgE检测-蟑螂_定量,血_过敏原特异性IgE检测-蚕丝_定量,血_过敏原特异性IgE检测-豚草_定量,血_过敏原特异性IgE检测-艾蒿_定量,血_过敏原特异性IgE检测-葎草_定量,血_过敏原特异性IgE检测-藜/反枝苋_定量,血_过敏原特异性IgE检测-柏树/榆树/柳树/栎树/桦树/枫树/胡桃树/梧桐树/杨树_定量,血_过敏原特异性IgE检测-悬铃木/白蜡_定量,血_过敏原特异性IgE检测-桤/杨/柳/山毛榉/橡/胡桃_定量,血_过敏原特异性IgE检测-六月禾/黑麦草/梯牧草_定量,血_过敏原特异性IgE检测-鸡蛋蛋黄_定量,血_过敏原特异性IgE检测-鸡蛋蛋白_定量,血_过敏原特异性IgE检测-花生/大豆_定量,血_过敏原特异性IgE检测-芝麻_定量,血_过敏原特异性IgE检测-小麦/荞麦_定量,血_过敏原特异性IgE检测-牛肉/羊肉_定量,血_过敏原特异性IgE检测-虾/蟹_定量,支气管肺泡灌洗液_中性粒细胞百分比_定性,血_肺炎支原体抗体.IgG_定性,胸腔液_肺炎克雷伯菌_定性,胸腔液_铜绿假单胞菌_定性,胸腔液_金黄色葡萄球菌_定性,胸腔液_大肠埃希菌_定性,胸腔液_红细胞计数_描述性,检查项目,检查项目数量

In [49]:
# sorted_result_df.rename(columns={'resultDateTime':'报告时间'}, inplace=True)
sorted_result_df = pd.read_excel("/data/home/yansn/naojiye/data/是否做过关键检测.xlsx")
sorted_result_df['报告时间'] = sorted_result_df['报告时间'].astype(str)
sorted_result_df

,Unnamed: 0,patientId,报告时间,入组时间,age,gender,分组,组名,血,脑脊液,粪便,尿,鼻/咽拭子,骨髓,动脉血,nan,痰,胃液,肛拭子,脓肿液,穿刺液,支刷,导管,支气管肺泡灌洗液,体液,呕吐物,皮屑,皮肤,胆汁,耳道分泌物,胸腔液,引流液,眼部分泌物,分泌物
0,0,86600553,2022-07-08,2022-07-08,32,男,8,病毒性脑炎,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,86600553,2022-07-09,2022-07-08,32,男,8,病毒性脑炎,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,86600553,2022-07-10,2022-07-08,32,男,8,病毒性脑炎,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,86600553,2022-07-11,2022-07-08,32,男,8,病毒性脑炎,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,86600553,2022-07-12,2022-07-08,32,男,8,病毒性脑炎,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6705,6705,99174645,2025-03-12,2025-03-11,31,女,8,病毒性脑炎,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6706,6706,99174645,2025-03-13,2025-03-11,31,女,8,病毒性脑炎,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6707,6707,99174645,2025-03-14,2025-03-11,31,女,8,病毒性脑炎,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6708,6708,99174645,2025-03-17,2025-03-11,31,女,8,病毒性脑炎,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6709,6709,99174645,2025-03-18,2025-03-11,31,女,8,病毒性脑炎,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [50]:
check_df = pd.merge(sorted_result_df,final_df[['patientId','resultDateTime','检查项目数量','检查项目']],left_on=['patientId','报告时间'], right_on=['patientId','resultDateTime'])

In [51]:
check_df.drop(['resultDateTime','Unnamed: 0'], axis=1, inplace=True)

In [52]:
check_df = check_df.reindex(columns=['patientId', '报告时间', '入组时间', 'age', 'gender', '分组', '组名', '检查项目数量', '检查项目', '血', '脑脊液',
       '粪便', '尿', '鼻/咽拭子', '骨髓', '动脉血', 'nan', '痰', '胃液', '肛拭子', '脓肿液', '穿刺液',
       '支刷', '导管', '支气管肺泡灌洗液', '体液', '呕吐物', '皮屑', '皮肤', '胆汁', '耳道分泌物', '胸腔液',
       '引流液', '眼部分泌物', '分泌物'])

In [54]:
def check_range(row):
    if row['检查项目数量'] == 1:
        return 1
    elif row['检查项目数量'] == 2:
        return 2
    elif row['检查项目数量'] == 3:
        return 3
    elif row['检查项目数量'] > 3 and row['检查项目数量'] <=10:
        return 4
    elif row['检查项目数量'] > 10 and row['检查项目数量'] <=50:
        return 10
    elif row['检查项目数量'] > 50 and row['检查项目数量'] <= 100:
        return 50
    elif row['检查项目数量'] > 100:
        return 100
    
check_df['检查项目数量区域'] = check_df.apply(check_range,axis=1)

In [55]:
check_df = check_df.reindex(columns=['patientId', '报告时间', '入组时间', 'age', 'gender', '分组', '组名', '检查项目数量','检查项目数量区域', '检查项目', '血', '脑脊液',
       '粪便', '尿', '鼻/咽拭子', '骨髓', '动脉血', 'nan', '痰', '胃液', '肛拭子', '脓肿液', '穿刺液',
       '支刷', '导管', '支气管肺泡灌洗液', '体液', '呕吐物', '皮屑', '皮肤', '胆汁', '耳道分泌物', '胸腔液',
       '引流液', '眼部分泌物', '分泌物'])

In [56]:
new_df = check_df.groupby(['检查项目数量区域'])['patientId'].count().to_frame()

In [ ]:

new_df = check_df.groupby(['检查项目数量区域'])['patientId'].count().to_frame()
new_df = new_df.reset_index()

import pandas as pd
import matplotlib.pyplot as plt


categories = [1,2,3,'4-10','11-50','50-100','>100']
values = new_df['patientId']
x = range(len(categories))
plt.bar(x,values, width=0.4, label='count')
# plt.bar_label(plt.bar(categories, new_df['patientId'])) 
for i, v in enumerate(values):
    plt.text(i, v + 0.5, str(v), ha='center', va='bottom')
     
plt.xticks(x, categories)
plt.xlabel('check_number')
plt.ylabel('count')
plt.title('patient check_project count')
plt.legend()
plt.show()

生成数据集1至数据集5

In [28]:
import math
import numpy as np
import pandas as pd
# 根据医生的依据进一步整理数据
df2 = pd.read_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/wide_data.csv")

# 将脑脊液中重要数据的定性结果按照医生的依据和定量结果合并

list1 = ['脑脊液_中性粒细胞百分比_定性', '脑脊液_激活淋巴细胞_定性', '脑脊液_幼稚淋巴细胞_定性', '脑脊液_异常细胞百分比_定性','脑脊液_浆细胞_定性','脑脊液_嗜酸性粒细胞百分比_定性','脑脊液_激活巨噬细胞_定性']
list2 = ['脑脊液_中性粒细胞百分比_定量', '脑脊液_激活淋巴细胞_定量', '脑脊液_幼稚淋巴细胞_定量', '脑脊液_异常细胞百分比_定量','脑脊液_浆细胞_定量','脑脊液_嗜酸性粒细胞百分比_定量','脑脊液_激活巨噬细胞_定量']


for i in range(len(list1)):
    df2[list1[i]] = df2[list1[i]].map({'阴性': 0})

    def change(row):
        if row[list1[i]] == 0 and math.isnan(row[list2[i]]):
            return  0
        if not math.isnan(row[list2[i]]):
            return row[list2[i]]
        return math.nan

    df2[list2[i]] = df2.apply(change,axis=1)

# 脑脊液_红细胞计数_定量中无法检测的内容为脑脊液_红细胞计数_描述
# 性中的满视野，将两项合并

def change1(row):
    if row['脑脊液_红细胞计数_描述性'] == '满视野' and math.isnan(row['脑脊液_红细胞计数_定量']):
        return 100000
    else:
        return row['脑脊液_红细胞计数_定量']

df2['脑脊液_红细胞计数_定量'] = df2.apply(change1,axis=1)

/var/folders/1n/vp7g9rg94717gbh8l98slmfh0000gn/T/ipykernel_16268/789651362.py:5: DtypeWarning: Columns (21,22,33,49,60,62,120,150,193,202,207,209,211,212,214,215,216,217,218,219,220,221,222,223,229,232,235,241,242,243,244,254,255,256,261,274,283,294,329,330,338,339,340,341,359,365,397,410,411,417,428,429,430,431,432,433,434,435,436,439,440,441,445,446,448,449,450,451,466,468,469,471,472,484,485,486,487,488,489,490,491,492,494,495,496,497,498,499,500,501,502,510,511,521,531,532,533,541,543,547,548,549,550,558,559,561,564,565,568,569,570,571,576,577,579,584,585,586,587,588,590,591,592,593,595,596,597,598,599,600,607,608,609,613,622,624,625,626,627,628,630,636,637,648,649,650,651,664,665,667,668,669,671,672,673,674,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,698,699,700,702,703,704,707,708,719,720,721,725,726,727,728,730,737,738,747,748,749,750,751,752,753,754,755,758,759,760,762,763,771,772,773,774,775,776,777,778,779,781,783,784,785,786,787,788,789,790,791,792,795,796,799,806,808,812,815,816,818,819,820,821,822,824,825,826,827,836,837,838,839,840,841,842,843,844,845,846,847,853,854,855,858,859,860,861,862,863,864,867,869,874,876,877,878,879,880,881,882,884,888,890,896,901,904,906,907,913,914,915,916,919,920,921,925,926,927,928,929,930,931,932,933,934,937,938,939,940,941,944,945,946,947,948,953,954,955,956,957,959,960,961,962,963,964,965,966,970,971,972,973,974,975,976,977,978,979,980,981,985,988,989,990,991,992,994,996,997,998,1001,1002,1006,1007,1008,1009,1010,1011,1013,1014,1020,1021,1022,1023,1025,1026,1028,1029,1030,1031,1032,1033,1035,1036,1037,1038,1039,1040,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1063,1064,1067,1068,1071,1072,1073,1074,1076,1077,1079,1081,1082,1083,1084,1085,1086,1087,1088,1089,1104,1105,1106,1107,1112,1113,1114,1115,1116,1117,1119,1120,1121,1122,1123,1124,1125,1126,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1142,1143,1144,1145,1156,1157,1160,1161,1162,1163,1164,1166,1167,1169,1170,1171,1172,1191,1192,1193,1194,1195,1196,1197) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/wide_data.csv")

In [29]:
# 将脑脊液_透明度_描述性特征转换为数字特征
def change2(row):
    if row['脑脊液_透明度_描述性'] == '清':
        return 0
    elif row['脑脊液_透明度_描述性'] == '微浊':
        return 1
    elif row['脑脊液_透明度_描述性'] == '混浊':
        return 2
    return row['脑脊液_透明度_描述性']

df2['脑脊液_透明度_描述性'] = df2.apply(change2,axis=1)


#将脑脊液_肿瘤细胞_描述性特征转换为数字特征
def change2(row):
    if row['脑脊液_肿瘤细胞_描述性'] == '[肿瘤细胞]少量' or row['脑脊液_肿瘤细胞_描述性'] == '【嗜碱性粒细胞计数】偶见' or row['脑脊液_肿瘤细胞_描述性'] == '【幼稚淋巴细胞】中量' or row['脑脊液_肿瘤细胞_描述性'] == '【幼稚淋巴细胞】大量':
        return math.nan
    elif row['脑脊液_肿瘤细胞_描述性'] == '阳性':
        return 1
    elif row['脑脊液_肿瘤细胞_描述性'] == '阴性':
        return 0
    return row['脑脊液_肿瘤细胞_描述性']

df2['脑脊液_肿瘤细胞_描述性'] = df2.apply(change2,axis=1)

# 将脑脊液_蛋白定性_定性特征转换为数字特征

def change3(row):
    if row['脑脊液_蛋白定性_定性'] == '阴性':
        return 0
    elif row['脑脊液_蛋白定性_定性'] == '阳性':
        return 1
    return row['脑脊液_蛋白定性_定性']

df2['脑脊液_蛋白定性_定性'] = df2.apply(change3,axis=1)

# df2.groupby(['脑脊液_透明度_描述性'])['patientId'].count()

In [30]:
change_features = ['血_隐球菌荚膜抗原_定性', '血_抗双链DNA抗体_定性', '血_抗核抗体_定性', '血_抗胞浆型中性粒细胞抗体_定性', '血_抗核周型中性粒细胞抗体_定性', '血_梅毒非特异性抗体_定性', '血_梅毒螺旋体抗体_定性',
                    '血_人类免疫缺陷病毒抗体_定性', '血_不规则抗体_定性', '血_直接抗人球蛋白试验_定性', '血_结核感染T细胞检测_定性', '血_人类免疫缺陷病毒P24抗原_定性',"血_M蛋白_描述性"]

# 将change_features中的定性特征转换为数字特征

for i in change_features:

    def change4(row):
        if row[i] == '阴性':
            return 0
        elif row[i] == '阳性':
            return 1
        return row[i]

    df2[i] = df2.apply(change4,axis=1)

In [31]:
df2.groupby(['脑脊液_颜色_描述性'])['patientId'].count()

脑脊液_颜色_描述性
无色     1183
浅黄色     166
淡红色      23
红色        5
黄色       29
Name: patientId, dtype: int64

In [32]:
# 将每位病人每天的检查数据 合并为 一位患者只保留一条数据，如果有重复检测项目 保留为最早日期的检测结果

def merge_group(group):

    group = group.sort_values('resultDateTime')
    result = {}
    for col in group.columns:
        if col == 'patientId':  
            result[col] = group[col].iloc[0]
        elif col == 'resultDateTime':  
            result[col] = group[col].min()
        if col == 'age':  
            result[col] = group[col].iloc[0]
        elif col == 'gender':  
            result[col] = group[col].min()
        else:
            non_null = group[col].dropna()
            if len(non_null) == 0: 
                result[col] = np.nan
            elif len(non_null) == 1:  
                result[col] = non_null.iloc[0]
            else: 
                min_date_idx = group.loc[group[col].notna(), 'resultDateTime'].idxmin()
                result[col] = group.loc[min_date_idx, col]
    
    return pd.Series(result)

result = df2.groupby(['patientId']).apply(merge_group).reset_index(drop=True)

/var/folders/1n/vp7g9rg94717gbh8l98slmfh0000gn/T/ipykernel_16268/2810738574.py:28: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df2.groupby(['patientId']).apply(merge_group).reset_index(drop=True)

In [12]:
missing_rate_df = pd.DataFrame.from_dict(dict(result.isna().sum()/887), orient='index')
missing_rate_df.to_excel("/data/home/yansn/naojiye/data/缺失值.xlsx")

In [33]:
# 根据筛选后 需要保留的特征

blood_features = ['血_白细胞计数_定量','血_红细胞比容_定量','血_红细胞分布宽度_定量','血_红细胞计数_定量','血_平均红细胞体积_定量','血_平均红细胞血红蛋白含量_定量','血_平均红细胞血红蛋白浓度_定量','血_血小板计数_定量',
                  '血_总血红蛋白浓度_定量','血_嗜碱性粒细胞百分比_定量','血_嗜碱性粒细胞计数_定量','血_嗜酸性粒细胞百分比_定量','血_嗜酸性粒细胞计数_定量','血_中性粒细胞百分比_定量','血_中性粒细胞计数_定量',
                  '血_大血小板细胞比率_定量','血_平均血小板体积_定量','血_血小板分布宽度_定量','血_C反应蛋白_定量','血_单核细胞计数_定量','血_淋巴细胞计数_定量','血_单核细胞百分比_定量','血_淋巴细胞百分比_定量',
                  '血_血小板/淋巴细胞比值_定量','血_中性粒细胞/淋巴细胞比值_定量','血_淀粉样蛋白A_定量','血_降钙素原_定量','血_白细胞介素-6_定量','血_白细胞介素-10_定量','血_白细胞介素-12p70_定量','血_白细胞介素-17_定量',
                  '血_白细胞介素-2_定量','血_白细胞介素-4_定量','血_白细胞介素-1β_定量','血_白细胞介素-8_定量','血_白细胞介素-5_定量','血_有核红细胞百分比_定量','血_幼稚粒细胞百分比_定量',
                  '血_红细胞分布宽度标准差_定量','血_高荧光强度网织红细胞_定量']
naojiye_features = ['脑脊液_红细胞计数_定量','脑脊液_有核细胞计数_定量','脑脊液_蛋白定量_定量','脑脊液_氯_定量','脑脊液_葡萄糖_定量','脑脊液_蛋白定性_定性','脑脊液_透明度_描述性','脑脊液_颜色_描述性','脑脊液_激活巨噬细胞_定量',
                    '脑脊液_激活淋巴细胞_定量','脑脊液_嗜酸性粒细胞百分比_定量','脑脊液_幼稚淋巴细胞_定量','脑脊液_浆细胞_定量','脑脊液_中性粒细胞百分比_定量','脑脊液_淋巴细胞百分比_定量',
                    '脑脊液_巨噬细胞百分比_定量','脑脊液_单个核细胞百分比_定量','脑脊液_多个核细胞百分比_定量']

naojiye_selected_features = ['脑脊液_红细胞计数_定量','脑脊液_有核细胞计数_定量','脑脊液_蛋白定量_定量','脑脊液_氯_定量','脑脊液_葡萄糖_定量','脑脊液_蛋白定性_定性','脑脊液_透明度_描述性','脑脊液_颜色_描述性']

In [34]:
final_features_df = result[['patientId', 'resultDateTime', 'age', 'gender']+blood_features+naojiye_features]

In [ ]:
final_features_df2 = pd.DataFrame.from_dict(dict(final_features_df.isna().sum()/887), orient='index')
final_features_df2.to_excel("/data/home/yansn/naojiye/data/最终缺失值.xlsx")

In [35]:
final_features_df['patientId'] = final_features_df['patientId'].astype(str)

/var/folders/1n/vp7g9rg94717gbh8l98slmfh0000gn/T/ipykernel_16268/1591861133.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_features_df['patientId'] = final_features_df['patientId'].astype(str)

In [39]:
ruzu_df = pd.read_excel('/Users/yanjieni/Desktop/脑脊液/naojiye/data/ruzu_20250825.xlsx')
final_data_df = pd.merge(final_features_df,ruzu_df[['patientId','分组','组名']])
final_data_df = final_data_df.drop(['patientId','resultDateTime'], axis=1)

In [40]:
# 生成最终特征数据
final_data_df.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient1.csv", index=False)

In [41]:

needed_feature = dict(result.isna().mean()[result.isna().mean() < 0.66])

columns_to_keep1 = [item for item in needed_feature if item.startswith('血_')]
# temp_df = pd.DataFrame.from_dict(dict(result[columns_to_keep1+naojiye_features].isna().sum()/887),orient='index')

In [49]:
# 血常规特征缺失率<0.65 和 重要的脑脊液特征 (去除血_隐球菌荚膜抗原_定性，血_维生素B12_定量，血_轻链.λ型_定量 )

needed_feature = dict(result.isna().mean()[result.isna().mean() < 0.66])

columns_to_keep1 = [item for item in needed_feature if item.startswith('血_')]

columns_to_keep1.remove('血_隐球菌荚膜抗原_定性')
columns_to_keep1.remove('血_维生素B12_定量')
columns_to_keep1.remove('血_轻链.λ型_定量')


result['patientId'] = result['patientId'].astype(str)
temp_df = pd.merge(result[['patientId']+columns_to_keep1+naojiye_features],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df = temp_df.rename(columns={'年龄':'age','性别':'gender'})
temp_df = temp_df.drop(['patientId'], axis=1)
temp_df.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient2.csv", index=False)

In [50]:
# 只保留重要的血常规特征
# temp_df2 = pd.DataFrame.from_dict(dict(result[blood_features].isna().sum()/887),orient='index')

result['patientId'] = result['patientId'].astype(str)
temp_df2 = pd.merge(result[['patientId']+blood_features],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df2 = temp_df2.rename(columns={'年龄':'age','性别':'gender'})
temp_df2 = temp_df2.drop(['patientId'], axis=1)
temp_df2.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient3.csv", index=False)

In [51]:
# 只保留缺失率小于65%的血常规特征
# temp_df3 = pd.DataFrame.from_dict(dict(result[columns_to_keep1].isna().sum()/887),orient='index')

result['patientId'] = result['patientId'].astype(str)
temp_df3 = pd.merge(result[['patientId']+columns_to_keep1],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df3 = temp_df3.rename(columns={'年龄':'age','性别':'gender'})
temp_df3 = temp_df3.drop(['patientId'], axis=1)
temp_df3.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient4.csv", index=False)

In [52]:
# 只保留重要的脑脊液特征
# temp_df4 = pd.DataFrame.from_dict(dict(result[naojiye_features].isna().sum()/887),orient='index')

result['patientId'] = result['patientId'].astype(str)
temp_df4 = pd.merge(result[['patientId']+naojiye_features],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df4 = temp_df4.rename(columns={'年龄':'age','性别':'gender'})
temp_df4 = temp_df4.drop(['patientId'], axis=1)
temp_df4.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient5.csv", index=False)

In [53]:
# 只保留去除脑脊液细胞形态学分类的脑脊液特征
# temp_df4 = pd.DataFrame.from_dict(dict(result[naojiye_features].isna().sum()/887),orient='index')

result['patientId'] = result['patientId'].astype(str)
temp_df5 = pd.merge(result[['patientId']+naojiye_selected_features],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df5 = temp_df5.rename(columns={'年龄':'age','性别':'gender'})
temp_df5 = temp_df5.drop(['patientId'], axis=1)
temp_df5.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient6.csv", index=False)

In [54]:
# 只保留8项脑脊液特征+40项血液特征
# temp_df4 = pd.DataFrame.from_dict(dict(result[naojiye_features].isna().sum()/887),orient='index')

result['patientId'] = result['patientId'].astype(str)
temp_df6 = pd.merge(result[['patientId']+blood_features+naojiye_selected_features],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df6 = temp_df6.rename(columns={'年龄':'age','性别':'gender'})
temp_df6 = temp_df6.drop(['patientId'], axis=1)
temp_df6.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient7.csv", index=False)

In [55]:
# 只保留8项脑脊液特征+206项血液特征
# temp_df4 = pd.DataFrame.from_dict(dict(result[naojiye_features].isna().sum()/887),orient='index')

result['patientId'] = result['patientId'].astype(str)
temp_df7 = pd.merge(result[['patientId']+columns_to_keep1+naojiye_selected_features],ruzu_df[['patientId','性别','年龄','分组','组名']])
temp_df7 = temp_df7.rename(columns={'年龄':'age','性别':'gender'})
temp_df7 = temp_df7.drop(['patientId'], axis=1)
temp_df7.to_csv("/Users/yanjieni/Desktop/脑脊液/naojiye/data/final_data2/filtered_patient8.csv", index=False)